### ISSUE TITLE
 API key no longer +  pixel already installed (pixel works): shop can't be created

### ISSUE THREAD

**Issue by Xentar** [facebookincubator/facebook-for-woocommerce#159] opened 2017-11-21 20:18 UTC
Well... i have these two issues. First, while doint the setup, where i select the pixel, i get an error msg telling me that i have already installed a pixel... Thing i did with this plugin. (i didn't add the code in header or anything). Ok, if i ignore that, i guess no accuerate data, but at the end all looks fine, till i reload the integration tab and find the resync product missing and the message:

>  Your API key is no longer valid. Please click "Re-configure Facebook Settings > Advanced Options > Delete Settings" and setup Facebook for WooCommerce again.

I followed the instruction, but nothing happen, same errors. Tryed deactivating plugin, deleting and reuploading but still same issue. Any suggestion? Right now i'm out of ideas, hehe. Thanks in advance

**Comment by mengyingdu** [comment] 2017-11-21 23:04
Hi,

There are 2 cases for 'pixel already installed'. Does it say"A pixel is already installed on this site. If you continue, you will replace the existing pixel with ...?  "or something else? If you can send us a screenshot to help us better investigate your issue?

Can you tell us your Facebook page or site url?

Thanks!

**Comment by Xentar** [comment] 2017-11-22 00:17
the screen is here (sadly is in spanish, but is something like: "your pixel, Pixel de 4pets is already installed on your website. We recommend you to delete the actual version before continue. On the contrary, there will be two versions of Pixel de 4Pets in your site and and the results of your campaigns will not be accurate")
http://www.4pets.cl/wp-content/uploads/images/issue.png

The website is http://www.4pets.cl and the fb is https://www.facebook.com/4PetsCL/
I left the plugin "configured" just in case. If i check the code with inspecto i just find 1 pixel... Could be i'm doing something wrong?

**Comment by mengyingdu** [comment] 2017-11-22 01:03
Hi,

This is very weird. I checked your website url and the setting id is fine. However, your page link doesn't work. Can you check on your site? https://www.facebook.com/4PetsCL/
![page not work](https://user-images.githubusercontent.com/24535640/33104614-e3a52f70-cedd-11e7-98c7-fe42610d24fe.jpeg)

**Comment by Xentar** [comment] 2017-11-22 01:43
Try now. Looks like the owner (i'm helping him) set to just Chile visitors. Deactivated so is worldwide now.

**Comment by mengyingdu** [comment] 2017-11-22 02:17
Hi, 

I checked your Facebook page and it seems you haven't successfully set up shop. I deleted your setting in our backend. Can you try to set up now? 
Let me know whether it works.

Thanks.

**Comment by Xentar** [comment] 2017-11-22 02:43
Ok, did it, now at least say that the pixel already instaled but going to use that one (with a green box). But still appear the "Your API key is no longer valid."

**Comment by mengyingdu** [comment] 2017-11-22 02:54
Thanks for your patience and try. I will look into your problem.

**Comment by mengyingdu** [comment] 2017-11-22 19:51
Hi, 

Did you use Adblock ? It will cause problem with plugin and pixel. If so, can you try disable and then try sync products?

**Comment by Xentar** [comment] 2017-11-22 22:33
hey, sadly didn't work
Ok, disabled it and reconfigured. Got the duplicated pixel message again and when i finished the setup and returned to the integration, i had the same "Your API key is no longer valid." message. This is kinda... extrange. Could be a setup on the hosting? the reqs are ok, but something on the php config?

**Comment by mengyingdu** [comment] 2017-11-22 22:46
What other plugins are you using now?

**Comment by Xentar** [comment] 2017-11-22 22:56
Must say, a lot of them. Right now running (21):
-Admin menu editor
-Ajax search for woocommerce
-Elementor
-Custom galery wp links
-Facebook for woocommerce
-Pirateforms
-Loco translate
-Meta Box
-Perfect woocommerce brands
-Post Thumbnail editor
-Regenerate Thumbnails
-States, cities and places for woocommerce
-User role editor
-Woocommerce
-Woocommerce added to cart popup
-Woocommerce advanced free shipping
-Woocommerce flow servipag
-Woocommerce flow webpay
-Wordpress media library folders
-Yith woocommerce ajax product filter
-Yith Woocommerce ajax search

I think no one really affect the woocomerce products except some custom fields with Meta Box, but the default ones are still there.

**Comment by mengyingdu** [comment] 2017-11-29 18:25
Hi,

I checked your remote log which shows that your setting created successfully this time. However, the API key problem usually happens if you have reset your FB password recently. If you follow the steps described in the error message and delete the plugin and set up again, you can get a new API key.

But keep in mind that disabled Adblock when you fix it.

Let me know whether it works.

Thanks.

**Comment by mengyingdu** [comment] 2017-11-29 18:26
I realize this is a hassle, which is why we are working on building a way to do this without having to delete everything, but that will not be ready for some time yet.

**Comment by Xentar** [comment] 2017-12-02 17:15
Nop, no luck: Deleted configurartion, deactivated plugin, deleted it, downloaded the last one from here, deleted adblock from firefox, uploaded plugin... did the full set up again, and the same issue. "Your API key is no longer valid." and, btw, the fb password was never reseted, is the same from the start... Looks like we going to need to wait for a new version and give it a try again...

**Comment by dmitridr** [comment] 2017-12-04 22:41
Hello,

Thanks for trying all of Mengying's suggestions. I have some more that you can try : 

- Could you try to temporarily deactivate every other plugin except WooCommerce and FB for Woo. Then try the reset steps again. Does the problem persist? This should rule out the possibility that other plugins are interfering somehow.

- From our internal logs, we can tell that we sent a valid API token to you, so either something is wrongly flagging an API error, or the token was not properly saved in the DB. If you have DB access, can you double check the table `wp_options` for the entry `woocommerce_facebookcommerce_settings` has an API key? (It should start with `EAA...` don't paste the full thing here though!). If the API key is not there, it could indicate that there was a problem with saving it.

**Comment by Xentar** [comment] 2017-12-05 01:34
-Checked de options table and is there (but the wp_options is had diferent suffix for security)
-Going to give a try the plugins idea tommorrow late night during a maintence.
Lets wish is something like that... well, is the most feasible option, anyways

**Comment by dmitridr** [comment] 2017-12-14 23:48
Following up here : 
In order to display the API key error, we check two things 1. The API key is in the DB. 2. The API key can be used to fetch the page name.

The code for that can be seen [here](https://github.com/facebookincubator/facebook-for-woocommerce/blob/master/facebook-commerce.php#L2157).

Since you verified the API key is in the DB it is likely this second step failed in this case. So if the plugin compatibility test does not help, it may be a problem with the settings of the page. If the page is only accessible in Chile, for example, the API call may fail outside of Chile. 

You may be further able to pinpoint the problem by trying to set up with a brand new page. If there is no API key problem in such a case, the problem is likely with the specific page.

**Comment by mengyingdu** [comment] 2017-12-20 19:29
Hi @Xentar ,

Just want to check, do you still have problem to set up?

Let me know if you need more help.

Thanks.

**Comment by Xentar** [comment] 2017-12-20 20:57
Sorry, i dissapeared for some time cause the dates. I could not do the tests deactivating the others plugins, but did an update of the plugin (latest version 1.7.3) and the issue is still there. Going to try tonight to do the test deactivating all the plugins, so stay alert (hehe). Thanks alot for the concern.

**Comment by Kewayne** [comment] 2017-12-20 23:19
Hey @Xentar I had the same problem yesterday and I just got it fixed

**Comment by Xentar** [comment] 2017-12-21 02:24
@Kewayne and how you fixed it?

@mengyingdu  no luck, deactivated all plugins and got the same message if i went back to "integrations".

**Comment by Kewayne** [comment] 2017-12-21 02:42
I think it is something deactivated by your hosting company "**The Outgoing Connections**". That was what happened to mine. I contacted my hosting provider last night after testing the facebook-woocommerce on another site on a different host and it worked.

Attached is the ticked i submitted to them.


I hope this will help fix your problem. Please consider giving me a small donation. Thanks my PayPal is [https://www.paypal.me/Shaq2000](url)  I would greatly appreciate it.

![image](https://user-images.githubusercontent.com/34725741/34238229-9a3592be-e5ce-11e7-844e-b9e50f64ce90.png)

**Comment by Xentar** [comment] 2017-12-21 16:14
@Kewayne  sadly i already did that some time ago. I have full control over cpanel and php, so i activated the allow_url_fopen, and all the same... so is no the same-same. But still could be something with the hosting, and is probably, because...

@mengyingdu  i did some test and found out that, like you suggested some time ago, don't fetch the page name. Looking out why.

**Comment by mengyingdu** [comment] 2017-12-21 17:19
Did you ever try to set up with a brand new page without visibility restrict (which is suggested by @dmitridr )?  If there is no API key problem in such a case, the problem is likely with the specific page.

**Comment by mengyingdu** [comment] 2018-01-10 17:36
Hi @Xentar ,

I go to your website and found your pixel fired correctly. It seems you have already figured it out!

**Comment by Xentar** [comment] 2018-01-10 18:22
@mengyingdu believe or not, i did nothing. The page have the same msg and there is no shop in facebook. My guess is that at least the pixel is working fine, hehe. Thanks for the concern!

**Comment by mengyingdu** [comment] 2018-01-10 18:42
As for your previous question about the warning:
"your pixel, Pixel de 4pets is already installed on your website. We recommend you to delete the actual version before continue. On the contrary, there will be two versions of Pixel de 4Pets in your site and and the results of your campaigns will not be accurate"

We detect this by your latest pixel traffic on your site, rather than real time setting (Since you are in editing mode). It's fine to ignore this warning. 

If you checked set up facebook shop in the last step, it should automatically created one for you. I check our remote logging, the last setup on your site in 20 Dec and it is true. I will flag this to our shop team.

Congrats!

**Comment by mengyingdu** [comment] 2018-01-12 03:24
Hi @Xentar ,

I got follow-up for your shop from shop team, and it 'WAS' created. Can you try to login and check? See screen shot.
<img width="1060" alt="screen shot 2018-01-11 at 7 19 24 pm" src="https://user-images.githubusercontent.com/24535640/34858368-d1b925ec-f704-11e7-9100-a8e71afac84f.png">

I also found I can't see your shop section which I think I was in some experience to view specific page. However, as admin, you should be able to see your page's shop section. 

Let me know if you can see it or need other help.

Thanks.

**Comment by mengyingdu** [comment] 2018-01-18 20:30
Close this issue for now since it works. If you have any questions, feel free to open a new issue.

**Closed by mengyingdu** 2018-01-18 20:30 UTC
Labels: question, shop-bug

**Comment by gervet** [comment] 2018-03-13 19:43
Hi @mengyingdu  I having the same problem with the token. I deleted the plugin, re installed, deleted the info in the DDBB and still having the same problem. So you know how to fix it? We don't have any restriction on our facebook page. 

Thanks

**Comment by Huyeng** [comment] 2018-03-16 09:23
I have the same problem too, I tried to figure out following the message above, but it doesn't work.  Could you help?
