### ISSUE TITLE
PHP Warning : Calling User Func on Null Woo Object?

### ISSUE THREAD

**Issue by HW-Siew** [facebookincubator/facebook-for-woocommerce#348] opened 2018-03-27 00:12 UTC
Consistently show PHP warning in my log file as follow. What is wrong?

`PHP Warning: call_user_func_array() expects parameter 1 to be a valid callback, first array member is not a valid class name or object in /wp-content/plugins/facebook-for-woocommerce/includes/fbproduct.php on line 50`

**Comment by mengyingdu** [comment] 2018-03-28 22:16
Hi @HW-Siew ,

Can you follow the support section on the front page of this repository and give us useful information in order to help you?

eg. your store url, or fb page, version
If you just told me this , I have no idea which version you are using, or what could be the cause.

Thank you.

**Comment by ttjs82** [comment] 2018-03-30 20:09
I'm seeing the same issue. Plugin version 1.8.2. Woocommerce v3.3.4 and WP 4.9.4. PHP 7.2.2, nginx/1.12.2

Actually we have seen this error notice also with earlier versions of the plugin. And also before jumping from PHP 7.0 to the current one.

**Comment by mengyingdu** [comment] 2018-03-31 03:05
Hi @HW-Siew ,

Besides that, did you find related stack trace ? Caller?

Thanks.

**Comment by marc-one** [comment] 2018-04-01 10:11
Same problem:
call_user_func_array() expects parameter 1 to be a valid callback, first array member is not a valid class name or object
 Type: PHP Warning Line: 50
 File: /home/wp-content/plugins/facebook-for-woocommerce/includes/fbproduct.php

And also:

Trying to get property of non-object
 Type: PHP Notice Line: 662
 File: home/wp-content/plugins/facebook-for-woocommerce/facebook-commerce.php

Thanks for any suggestion

**Comment by mengyingdu** [comment] 2018-04-02 14:34
Hi @marc-one ,

When did you see the second php warning? like  you change the visibility of a certain product? Or when you sync all products?

Thanks.

**Comment by marc-one** [comment] 2018-04-02 14:37
Hi 
Just after update some product
Thanks a lot

**Comment by mengyingdu** [comment] 2018-04-02 14:47
Hi @HW-Siew ,

When did you see this error? initial sync all products? or change any product info? 
Can you upload a screenshot of this error log (more context above and after)?

Thanks.

**Comment by marc-one** [comment] 2018-04-02 15:22
So I trade to update one product and insert new one but nothing happen ! Should I synchronize all product?

**Comment by marc-one** [comment] 2018-04-02 16:33
So I trade to force sync and nothing happen any more I mean:

First message:
Starting background sync to Facebook: 139 products…
Than :
Pushing post to queue: 19721  and a lot more 

Than:
Nothing to update for product group for 1643288649070445 and a lot more 

And only one message :
{"headers":{},"body":"{"success":true}","response":{"code":200,"message":"OK"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}

Total message 176 

It same all is working fine ?

Thanks a lot

**Comment by iamajayyadav** [comment] 2018-04-11 22:37
Same issue with multiple entries /html/wp-content/plugins/facebook-for-woocommerce/includes/fbproduct.php on line 50 everything is working fine. Only with pages when i am going to edit published pages.

**Comment by dmitridr** [comment] 2018-04-12 23:58
Unfortunately I can't reproduce this warning, we would need a stack trace (usually in the error logs it's right under the exception) to see what the caller of that method is doing, that's where the problem lies.

If anyone has a stack trace, please post it here. In the meantime, we will fix where we *think* the warning is coming from and include that in the next version. That may address the issue.

The problem is [here](https://github.com/facebookincubator/facebook-for-woocommerce/blob/master/includes/fbproduct.php#L50), and it looks like `$this->woo_product` is somehow null. So I'm guessing we incorrectly identified the wp_id as a woo product somewhere in the code.

**Comment by ttjs82** [comment] 2018-04-18 10:24
I'll install the update today @dmitridr and will let you know if this fixes the issue.

**Comment by dmitridr** [comment] 2018-04-18 18:38
Thanks @ttjs82 even if it doesn't fix the issue, we added logging to FB to send us a stack trace if the warning occurs, so we should be able to track down the problem. Will check the logs tomorrow.

**Comment by ttjs82** [comment] 2018-04-24 12:27
I forgot to report that the update did fix the issue for us at least. We haven't seen the error since v.1.8.5 update. Thanks @dmitridr

**Comment by dmitridr** [comment] 2018-04-25 01:27
Thanks for confirming. I followed up and figured out what was going on here: 

We were trying to delete and update the visibility of non-products. We have a fix ready should be out in the next version, though the current version suppresses the warning.

**Comment by mengyingdu** [comment] 2018-04-26 19:05
Hi @HW-Siew @ttjs82 @marc-one @iamajayyadav ,

This has been fixed in v1.8.6.

Also, we had a quality room first half of this week and just released [v1.8.6](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.8.6) We have 10 fixes plus 1 content enhancement. I do recommend you upgrade.

If you like **Facebook-for-WooCommerce**  please leave us a [*****](https://woocommerce.com/products/facebook/) rating. A huge thanks in advance!

**Closed by mengyingdu** 2018-04-26 19:05 UTC
Labels: bug, follow-up for next release
