### ISSUE TITLE
API Key is no longer valid

### ISSUE THREAD

**Issue by morethanwords1980** [facebookincubator/facebook-for-woocommerce#538] opened 2018-06-11 13:29 UTC
Hi, I saw a previous topic but it was closed. I was wondering if you had any news on this because periodically we all have to change Facebook password, does every time we do this the plugin get disconnected?

The problem is the only solution is to unlink and relink the site to Facebook, but doing this all the catalogue gets erased and recreated, resulting in all previous campaigns and posts being useless. Isn't there a fix that avoids redoing all the work from the beginning?

Thank you for your help!

**Comment by sammul** [comment] 2018-06-11 17:14
[Note : This is an Automated Message]

Hello,

Thanks for your interest in our plugin!
Due to a high volume of issues we may not be able to get to yours immediately.

If this is a feature request, or feedback, please reply with
`Feature Request` or `Feedback` and it will be categorized accordingly, and
we will read it and reply when we can.

If you are experiencing problems, read on.

First. Please check to see if your issue is not a duplicate of another one.
To search our issues, use the search feature at the top of the GitHub issues page.
We have nearly 500 existing and past issues, so it is fairly likely someone else has already reported your problem.
If you do find a relevant issue, please comment in that issue, and close this one.
It helps us prioritize issues to tackle by looking at the number of people with the same problem.

If your issue is unique, and you are sure, then read on.
We require the following information in order to help you:
- WooCommerce Version
- Wordpress Version
- Plugin Version. Please Note that we do not support outdated versions of the plugin.
- A Screenshot of where you see the problem. If it is on Facebook, a screenshot of Facebook,
if it is on WooCommerce, a screenshot of WooCommerce. If it is in multiple places, multiple screenshots.
- The URL of your website.
- The URL of your page.
- The URL(s) where you took your screenshot(s).
- (If applicable) Detailed steps you took in order to see the problem.

Please be advised, it may take us some time to get to your issue.
In the meantime, below are generic approaches you can take that may solve the issue :
- Upgrade to the latest version.
- Force Resync
- Reset the plugin using `Reconfigure > Advanced Options > Delete` and setup again.
- Try to deactivate other plugins which you think could be interfering and repeating the above.

When you have the above data for us, please include
`Debug Ready` in your reply. We will get to it and debug it as soon as we can.

Thanks for your patience,
Dev Team (@mengyingdu, @sammul, @jieminz22, @dmitridr)

**Comment by morethanwords1980** [comment] 2018-06-12 10:31
- Woocommerce version: 3.4.2
- Wordpress version: 4.9.6
- Plugin version: 1.8.7
- The issue has now been solved by reconfiguring the settings as indicated, removing and adding again the link between the site to the catalogue. The point is that erased the previous catalogue and shop on the Facebook page, resulting in losing all the previous campaigns and linked posts! Will this happen every time I change my Facebook password?
- URL: http://www.peliniarreda.com
- FB: http://facebook.com/peliniarreda/
- The problem was indicated in the Facebook for Wordpress plugin configuration page
- The steps I think created the problem are 1) I changed my FB password; 2) the plugin said the API key was no longer valid so I had to restore the settings; 3) I restored the settings as indicated but it erased all the previous catalogue, the products, the shop on the facebook shop and the related links and posts; 4) it's not possible to tag the products from the catalogue to Instagram as it used to be, despite both FB page, catalogue and instagram profile are owned by the same Business Manager.

Thank you!

**Comment by mengyingdu** [comment] 2018-06-19 00:36
Hi @morethanwords1980 ,

Did you see the update token message?

![update token](https://user-images.githubusercontent.com/24535640/41569082-0e92a412-731e-11e8-86be-06838fbb9f45.png)

**Comment by morethanwords1980** [comment] 2018-06-19 07:41
Hello and thank you for your answer.

I had the “Reconfigure Facebook Settings” button and that’s the procedure I followed but I didn’t have the “Update Token” message it forced me to wipe out all the previous configuration, which meant having to redo all the work from the beginning.

Should it happen again - hopefully not :P - I will get in touch with you BEFORE doing the procedure so in case the issue is still there we’ll try to debug it before hand.

Thank you for your help anyway :)

--
Simone Minzi
Product & Digital Marketing Manager
Araundu
Via Giuseppe Vasi, 5
00162 - Roma
06 99259960
simone.minzi@araundu.it
skype: morethanwords1980

**Comment by dmitridr** [comment] 2018-06-25 23:06
Glad you were able to resolve. Please do get in touch with us if it happens again. We should be surfacing instructions to update the token (so that you don't have to reset again), if we are not there is some problem.

@mengyingdu maybe we should surface the option to `update token` to everyone, what do you think? It seems in some cases we can't correctly detect if the token needs to be updated.

**Comment by lgfogle** [comment] 2020-04-06 23:17
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!

**Closed by lgfogle** 2020-04-06 23:17 UTC
Labels: Feedback, feature-request
