### ISSUE TITLE
Facebook shop wont update after product price change -> Bulk Edit Doesn't Work

### ISSUE THREAD

**Issue by bagx3** [facebookincubator/facebook-for-woocommerce#44] opened 2017-09-20 12:22 UTC
my whole store is sync, i often perform a force sync weekly to ensure it is kept upto date, however im noticing the only products that update are the once done manually, 

for example. if i change my pricing via bulk editor for example or bulk plugin facebook doesnt update. 

facebook product:
https://www.facebook.com/commerce/products/1619615368072923/
website:
https://www.honeyz.com/mini-dresses/vip-adorable/?attribute_pa_clothing-size=uk-6&attribute_pa_colour=white

both prices are different, a force sync is not solving it either.

**Comment by dmitridr** [comment] 2017-09-21 19:51
I confirmed with a repro that bulk edit is not updating products, thanks for flagging! 

The way the plugin currently works is it hooks into the product update request from the products edit page. There aren't any hooks to the bulk edit because that must be going through a different pathway.

Force sync should solve the problem because it resyncs all the products, so that's weird. Seems there are two problems here. Will see if we can address the bulk edit first.

**Comment by bagx3** [comment] 2017-09-21 20:02
I noticed whilst writing the last message that an update was available for the plugin and the force sync does indeed work for me on the lastest version 

The previous version the force sync did not change the prices of the bulk edited items 

Thanks

**Comment by dmitridr** [comment] 2017-12-14 22:35
Happy to say that @mengyingdu committed [code to enable bulk edit compatibility](https://github.com/facebookincubator/facebook-for-woocommerce/commit/ae0ad3e7e326261b35c4d5832a42f023cb40f10c), coming soon in v1.7.4.

**Comment by mengyingdu** [comment] 2018-01-10 17:39
Hi @bagx3 ,

We enabled bulk edit in [v1.7.4](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.7.4) Can you try to upgrade?

I will close this issue for now. If you need more help, feel free to open another issue and we will be here help you troubleshooting.

Thanks.

**Closed by mengyingdu** 2018-01-10 17:39 UTC
Labels: bug
