### ISSUE TITLE
Facebook Shop shows discount price rather than full prices || Compatibility : WooCommerce Membership

### ISSUE THREAD

**Issue by VcDesigns** [facebookincubator/facebook-for-woocommerce#229] opened 2018-01-23 01:28 UTC
Hello,

I have been using the woocommerce facebook plugin now for a year and the latest update screwed up my facebook shop all together.  Before it was showing the regular full price for retail. and now it shows all discount prices from my primary website shop that is connected to my pro members area.  Before the latest update it didn't show the Discounted pro prices on facebook.     So i get complaints and constant people wanting to purchase the price that shows on facebook that isn't on my regular site for non members.  I don't see anything in the plugin integration when you click on settings section for facebook or even on products to select show regular price or retail price on facebook.  That option should be someplace if not this plugin sucks now.  I loved it before the latest update.  I'm losing money and business every day because this problem.  The woocommerce membership plugin is what i use for my pro members and that has never had an issue and shouldn't have any issue regarding this plugin.  The plugin should only be pulling in retail prices to facebook shop and it's not.   So what can fix this????

**Comment by sammul** [comment] 2018-01-23 02:01
This is a similar report as #191 
We will try to fix in the next versions.
If you really need to, you can try our older version to see if the problem can go away. Which version were you on previously? You can find the version in the releases section if it's after 1.4.2. But be aware that we have fixed a lot of other issues since then so it might not work perfectly.  
https://github.com/facebookincubator/facebook-for-woocommerce/releases?after=v1.6.3

Thanks

**Comment by VcDesigns** [comment] 2018-01-23 02:10
i've already tried 3 older versions and it doesn't work, it's set in stone that it shows  member price then shows crossed off retail price.     Example   $20.50 was $41.00    no matter what i do, on facebook it shows  that.  So now i have had to hide my shop on facebook.   I recommend someone in next version update to have an option that lets you pick retail price listed on facebook,     

one of the custom fields called  fb_product_discription   next to that it has this content  (Prices shown on Facebook are Pro Member prices for this product. Retail no member prices listed on website by clicking on share to proceed to primary shop.)    this doesn't even show up on facebook when looking at the descriptions of the facebook shop of the product.   so more than one problem.

The custom field boxes is where you should be able to pick what price should be shown where you can select Retail Price,  Sale Price or Discount Price   that would solve everything.

**Comment by sammul** [comment] 2018-01-24 01:09
@VcDesigns sorry to hear that. Would you mind trying the following if you want to use an older version?
- Reset using Reconfigure > Advanced Options > Delete All
- Install the Older Version
- Set up with the Older Version.

Without deleting everything, only installing an older version won't fix the problem. 

I have labelled this as a bug and we will try to fix in our next versions.

**Comment by VcDesigns** [comment] 2018-02-07 18:09
Hello,  I have downloaded, cleaned up, tried over 8 different older versions of the woocommerce facebook plugin and it doesn't do any good.   What i can tell is your code pulls in the lowest price that is listed within woocommerce itself.  It will not pull in retail only prices.  it pulls in private content prices for discounted members who are signed in versus what is showing on site to all non members who are regular guest visitors.   No matter what is done, your plugin only is great for pulling in products to be listed on your facebook shop after that is totally sucks so far.  Because a simple area of how to just tell your plugin to pull in Retail price column and that is it.   So how your plugin searches for lowest price and crosses off regular retail price when it's showing on the Facebook Shop side.    I also have a section of products that have hidden prices that don't show up at all when your a guest visitor it tells you to login and signup as member to see prices.   Unlike your plugin it pulls in the prices no matter what to show on Facebook.  So i have 100's of people a day right now totally confused many now upset because they want the prices that facebook is showing and when they click on it and it brings it to the primary website shop the prices are showing retail.   So right now i've lost business vs gained business because your so called plugin doesn't do what it says it suppose to do.   It be nice to see an actual working version that would just simply show RETAIL price field on Facebook.

**Comment by jieminz22** [comment] 2018-02-07 21:28
Hi @VcDesigns, 

We are really sorry for the issue. Currently our plugin is not compatible with membership plugin.  I'm marking this as a feature request to support compatibility with membership plugin. In general, if there is a compatibility issue, the workaround would be to disable the other plugin, set up with Facebook, then enable the plugin again.

**Comment by VcDesigns** [comment] 2018-02-09 14:31
That doesn't work enable the plugin first than the woocommerce membership plugin after that.  It doesn't matter, the facebook plugin automatically looks for prices not in the Retail main price list that is a problem in the facebook plugin.  If it was told to just show the primary full price then there be no problems.  I have also tried without the membership plugin and all my hidden prices on the website still show up on facebook because it still is looking for the lowest price hidden or not hidden.   This plugin of Facebook only works if you have a regular price and nothing else.

**Comment by dmitridr** [comment] 2018-02-13 19:08
As you say, our plugin pulls the regular price using standard WooCommerce product methods. 
You can see the method we use [here](https://github.com/facebookincubator/facebook-for-woocommerce/blob/master/includes/fbproduct.php#L89) which is `get_regular_price`. 

If for some reason, `get_regular_price` is not returning the correct price, then it must be the behavior of another plugin is overriding this or using a different area to store the price, the memberships plugin as you say is the likely culprit, we have never tested with this plugin. 

You can see in [this section](https://github.com/facebookincubator/facebook-for-woocommerce/blob/master/includes/fbproduct.php#L93) we have fixed a similar compatibility issue with the WooCommerce Bookings plugin, which also stored the price in a different place. 

It's possible we can do a similar fix here, however we're prioritizing the performance of product sync and critical bugs, for now. However, we'd love to see a fix for this... If you come up with a fix, or anyone reading this wants to send us a pull request with a fix, we'd be happy to review it.

**Comment by VcDesigns** [comment] 2018-02-13 19:11
no your plugin doesn't pull in the regular price it pulls in whatever the cheapest price is and lists it on facebook.  bookings isn't the same at all.

**Comment by dmitridr** [comment] 2018-02-13 19:13
Sounds like a problem with the sale price being imported incorrectly then?

**Comment by dmitridr** [comment] 2018-02-13 19:17
I have an idea for a workaround, try deleting these lines in `fbproduct.php` using the WP Plugin Editor `Plugins > Edit` 

https://github.com/facebookincubator/facebook-for-woocommerce/blob/v1.7.11/includes/fbproduct.php#L236-L257

Then do a `Force Resync`, and if that doesn't work, try a full reset of the plugin. 
This will essentially disable all sale prices for you until we can find a better fix.

**Comment by VcDesigns** [comment] 2018-02-13 19:21
no it isn't suppose to be showing any other prices on facebook, right now i hear is excuses vs results.  your facebook plugin only works with one price configuration, if you have a sale price or even prices hidden from view or disabled from view it still shows up on Facebook and also shows the lowest price, even if that price.  It doesn't pull in the Retail price, it pulls in sales prices or member prices that arn't even listed for public to be seen.     So so far this plugin sucks because it only works if you have no sale prices or member discount prices.   Because your plugin looks and takes the cheapest price for a product rather than pulling in just the full retail price from the retail column price.


Workarounds don't fix anything they create problems with something else.  This is a coding problem that is designed and created in the plugin itself, it isn't looking for retail, it is looking for cheapest price for product.  I disabled it and not using it, i have had to create a manual product store on my facebook page that shows product and price that is retail.  to many bugs in the woocommerce wordpress plugin.  It doesn't seem to ever been tested for these other issues dealing with sale prices or hidden or member prices only that are to be logged into site to see.  It pulls in everything public on facebook and uses cheapest price inside of woocommerce itself.

**Comment by dmitridr** [comment] 2018-02-13 19:53
That's not how the plugin works. The issue is with the other plugins you have installed that are conflicting with ours. Quite clearly, not everyone has this problem, as the plugin pulls the correct price using standard APIs provided by WooCommerce. So it is not a problem with our plugin itself, but a problem with your configuration.

We have gone out of our way to try and support your custom configuration, even providing you with a workaround, I'm afraid that's all we can do for you at this time, unless someone sends us a fix.

**Closed by dmitridr** 2018-02-13 19:53 UTC
Labels: compatibility, feature-request, help wanted, up-for-grabs
