### ISSUE TITLE
Error when Finishing Setup : The content you requested cannot be displayed at the moment. It may be temporarily unavailable

### ISSUE THREAD

**Issue by emyabdel** [facebookincubator/facebook-for-woocommerce#289] opened 2018-02-20 00:17 UTC
hi

I installed facebook-for-woocommerce pluging on wordpress, go to woocommerce settings / integration / get started
I followed all steps but when I click finish I get this message error:
The content you requested cannot be displayed at the moment. It may be temporarily unavailable, the link you clicked on may have expired or you may not have permission to view this page.

I tried with another browser but the same result. what can I do? thanks

**Comment by jjclinton** [comment] 2018-02-20 09:39
I had the exact same issue! Now I can't sync my catalogue with Facebook. So anoying. I hope a solution comes fast.

**Comment by emyabdel** [comment] 2018-02-20 11:14
I hope someone give us a solution

**Comment by FlairTrade** [comment] 2018-02-20 11:29
Same issue as #287

**Comment by emyabdel** [comment] 2018-02-20 14:42
and what's the solution?

**Comment by michaelbourne** [comment] 2018-02-21 18:22
This will happen if you have an ad blocker running now. I'm sure there are other causes, but that's one I noticed this week.

**Comment by mbohanon** [comment] 2018-02-21 19:52
Also doesn't work if you use incognito mode...so it has to be something else. Chrome did have a recent version update, perhaps this is causing sync issues?

**Comment by emyabdel** [comment] 2018-02-21 21:45
I tried with a new domaine and new facebook and it worked but with my domain and facebook account nop. I'm not using any ad blocker

**Comment by 8owan** [comment] 2018-02-26 10:12
the problem is in 2FA of facebook account

**Comment by FlairTrade** [comment] 2018-02-26 10:30
> the problem is in 2FA of facebook account

I'm not sure that's the case, I don't have it turned on and still have this issue.

**Comment by dmitridr** [comment] 2018-03-21 02:01
Hey all,

This can happen for a number of reasons. I think our error message needs improvement here. 
Here are a couple of known reasons:

- Unsupported Currency (e.g. Bitcoin)
- Page is blacklisted from shops.
- Your URL is blacklisted by Facebook.
- Your Hosting provider/domain is blacklisted by Facebook.
- Ad Blocker/Browser Extensions interfering with setup.
- Facebook infrastructure failure (One happened around 30 days ago)

In the last case, trying again a day later will help, with the others you may need to do some more work to get it working. If you post the url of your page here, we can potentially investigate why this is happening to you. Hope that helps.

**Comment by dmitridr** [comment] 2018-06-13 02:34
Judging by the fact that absolutely nobody commented here after a small period in February, I would venture to guess this was a very temporary issue, so I will close this out. If someone experiences this again, please file a new issue and reference this one.

**Closed by dmitridr** 2018-06-13 02:34 UTC
Labels: bug

**Comment by wahoojess** [comment] 2019-10-02 01:46
HAVING THIS ISSUES WITH MY CATALOG. UGH. 5th day trying to figure it out but I dont know what im doing. Fb shop wont show variants from wix shop with a pixel integration. I try to add variants and edit stock and I get these two messages in the process. see images

<img width="428" alt="Screen Shot 2019-10-01 at 9 34 54 PM" src="https://user-images.githubusercontent.com/55940156/66012343-c604b200-e494-11e9-9d13-49c5798ed7aa.png">
<img width="1292" alt="Screen Shot 2019-10-01 at 9 40 22 PM" src="https://user-images.githubusercontent.com/55940156/66012344-c604b200-e494-11e9-9e9e-cd1bd79d8230.png">
