### ISSUE TITLE
 Notice People cannot currently see this product because it is not marked as published for sale on Facebook.

### ISSUE THREAD

**Issue by sharon13m** [facebookincubator/facebook-for-woocommerce#300] opened 2018-02-25 08:35 UTC
Hi, I'm having an issue here with these products: https://www.facebook.com/commerce/products/1566919019986136/
https://www.facebook.com/commerce/products/1480200695352404/

My other products are working though.  Those two products use Variations.  Is there a relation to that, and it not working?  Any suggestions for how to fix?

Error I get is:  People cannot currently see this product because it is not marked as published for sale on Facebook.

**Comment by mengyingdu** [comment] 2018-03-06 01:13
Hi @sharon13m ,

Are you using some other pixel related plugins? I see 2 pixel id from you site. 

Thanks.

**Comment by dmitridr** [comment] 2018-03-20 23:28
@sharon13m The second product seems like it's working now. Any update here? If you found out what could potentially be the cause we're happy to hear it, it may help out some others with the same issue.

To give some more context. There's multiple reasons the product could be marked hidden:
(1) It's not in the default language and you have WPML, this is by design.
(2) It's marked as FB-Hidden in the product edit tool.
(3) It's trashed or in a non-published state.

Hope that helps.

**Comment by dmitridr** [comment] 2018-06-13 03:01
Closing this as it has been a while since there has been a reply, if the problem persists on v1.8.7 please open a new issue on us and reference this one.

**Closed by dmitridr** 2018-06-13 03:01 UTC
Labels: question
