### ISSUE TITLE
Pixel in Wizard vs Business Manager

### ISSUE THREAD

**Issue by igogarciamx** [facebookincubator/facebook-for-woocommerce#164] opened 2017-11-23 14:44 UTC
Hi! 
I can't find the pixel for my new ad account / page in the setup wizard. I installed the pixel with Woocommerce first and then download the plugin. The page appears in the first step then when I see pixels the pixel associated with that Page isn't there. I tried to select a random one and then go to the code and change it manually with no success. 
Why isn't the pixel for that specific page appearing?
Page: /Gstraps
Website: gstraps.com.mx (current pixel is a personal account pixel selected to continue the wizard flow)
Business ID: 448073188921219
I can provide additional information or pictures if needed.
Thanks

**Comment by mengyingdu** [comment] 2017-11-29 23:55
Hi,

Are you the only owner of your business? It's probably because the expected pixel doesn't belong to your ad account. 
Can you tell me more information or steps to repro your problem? 

Thanks.

**Comment by igogarciamx** [comment] 2017-12-01 03:44
Hi! Yes. I'm the only owner. I do own couple of Ad Accounts and Business Managers. Let me get a screencast and I'll send it tomorrow. Thanks for following up.

**Comment by dmitridr** [comment] 2017-12-04 20:42
I'm hoping the problem is resolved here?  There should be a place in the business manager interface to assign pixels to ad accounts, which should resolve your issue. The only reason a pixel won't appear (to my knowledge) is that it is not attached to any ad account.

**Comment by igogarciamx** [comment] 2017-12-04 23:01
I don't know what could be happening, really. I couldn't manually enter the Pixel in the WooCommerce integration. I had to override the pixel ID with "Pixelyoursite" plugin.  I have two business managers, four ad accounts and I only see three. Haven't had time to do the screen grab so I'll share some screens.

![screen shot 2017-12-04 at 4 59 10 pm](https://user-images.githubusercontent.com/33934420/33580967-b5351cea-d914-11e7-88e0-a9bc7828dd57.png)
![screen shot 2017-12-04 at 5 00 11 pm](https://user-images.githubusercontent.com/33934420/33580968-b55fe4ac-d914-11e7-97e8-14adb34a09f7.png)

**Comment by dmitridr** [comment] 2017-12-06 01:00
The selector shows all of your pixels `that are attached to ad accounts.` If the pixel you want to use is not attached or assigned to any ad account that you own, it will not be shown.

Could you try and follow the steps in this guide to assign the pixel in question to an ad account that you own? Starting from 'Share the facebook pixel' step.
https://www.jonloomer.com/2017/03/17/share-facebook-audience-pixel/

That may help. 
That said, I think pixel your site is only partially compatible with our plugin, because it does not afaik include catalog-related items in the pixel fire (product ids, etc).

**Comment by mengyingdu** [comment] 2017-12-07 19:09
Hi @igogarciamx ,
I checked your website, it seems a test site rather than a real business. Have you ever tried @dmitridr 's suggestion? 

Also, I checked your pixel and page, your pixel show it was created by FB employee. Have you ever work with other Facebook team to help you open your business? Or you are an employee but running personal business as part-time?

If it's the second case, I think this issue may be related to some private policy. 
Let me know if you need more help. 

Thanks.

**Comment by igogarciamx** [comment] 2017-12-07 21:34
Will follow @dmitridr suggestion :) 
And yes, @mengyingdu , I'm a Facebook employee trying to dogfood in a test site (that will become a real site)
I'll try out suggestions this weekend. Thank you both for your kind help.

**Comment by mengyingdu** [comment] 2017-12-13 00:26
Hi @igogarciamx ,

Any update? Did you fix your problem by @dmitridr 's suggestion?
Let me know if you need more help.

Thanks.

**Comment by igogarciamx** [comment] 2017-12-19 12:13
Hi! I decided to connect the whole ecommerce ecosystem with Shopify and they provided a specific OTB solution. Thanks for following up so closely.

**Comment by mengyingdu** [comment] 2017-12-19 17:04
Glad to hear your find the approach for your business. Let us know if you have further questions.

Thanks.

**Closed by mengyingdu** 2017-12-19 17:04 UTC
Labels: question
