### ISSUE TITLE
Facebook Pixel Purchase event not firing. Using 1.8.5 version

### ISSUE THREAD

**Issue by lpienia** [facebookincubator/facebook-for-woocommerce#427] opened 2018-04-23 15:55 UTC
Hi there, 

I'm using the version 1.8.5 and the Purchase event is not firing after a Purchase is done. 

My site is www.zeva.com.ar

Attached my buz account showing pixel activity

![fireshot capture 19 - pixel de facebook_ - https___business facebook com_events_manager_pixel_events](https://user-images.githubusercontent.com/7903381/39138090-88b53976-46f5-11e8-9b5b-2d36e9029c53.png)

What can I do?

Regards,

**Comment by dmitridr** [comment] 2018-04-23 19:42
Hello,

A couple of questions.
(1) Do you have the Google Enhanced E-Commerce plugin installed? This plugin breaks ours #319 #329 
(2) Can you use the Facebook Pixel Helper tool and go through your site to make a test purchase, then check the output of the tool? This tool is generally very accurate and should tell you if purchase is working or not.

**Comment by lpienia** [comment] 2018-04-23 20:54
First of all when I run the site after the Facebook Pixel Helper tool installed, it detects 2 pixels.

1) For Buz Account that run Ads
2) por AppID thar runs Facebook Login for example

Is that normal?

Besides that I'm using the plugin "Actionable Google Analytics" that includes  Google Enhanced E-Commerce.

I need to track both on Facebook and Google purchases. So what could I do until you have the plugin compatible with Google Enhanced?

Regards,

**Comment by dmitridr** [comment] 2018-04-23 21:38
It's not normal to have 2 pixels, but if you do have 2, make sure they are a different ID, otherwise everything will be double-counted on the FB side, and reporting will be inaccurate.

#319 or #329 has some users who have managed to get the compatibility working, I would look into those and see if a similar approach works for you.

Is the test purchase working for you using the helper tool? If not, if you can send us the source code of that page, particularly the area around the string `WooCommerce Facebook Integration Event Tracking`, that would help us debug your issue.

**Comment by lpienia** [comment] 2018-04-23 21:53
I disable for the first test the plugin that I mentioned before and the tool shows the PurchaseEvent.


Attached you will find the source code of the Thankyou page after the Purchase. 
[FacebookPurchaseEvent.txt](https://github.com/facebookincubator/facebook-for-woocommerce/files/1940137/FacebookPurchaseEvent.txt)

Cannot see the PurchaseEvent yet... Or other Events. Could you check the source attached?
I see something strange on the source. Is not the Facebook Login that insert the second pixel. Was the "Tracking Code Manager" plugin that inserts. It's supposed to not insert that pixel since was disabled. I just removed that tracking to be sure that is not inserted. 

Regards.

**Comment by lpienia** [comment] 2018-04-23 21:55
The problem is that I'm still not viewing the events on the Pixel Facebook Panel

**Comment by dmitridr** [comment] 2018-04-23 22:17
Thanks for sending over the source. Yeah I see a weird injection that is happening, seems like it's caused by another plugin, maybe the one you mentioned :

`
fbq('init', '389218744776317'); // Insert your pixel ID here.
fbq('track', 'Purchase', {
value: @@AMOUNT@@,
currency: 'ARS'
});
`
Later farther down in the code you see the correct purchase event being sent by our plugin, but this one is sent first (and is potentially causing the issue).
I would venture to guess that whichever plugin adds this code is causing this problem. So a couple of suggestions:

(1) When you are looking at the `Pixel Facebook Panel` on FB, I would double check that you are looking at the right Pixel. The events from the pixel 389218744776317 appear to be broken. I am not sure which plugin is installing these events but it's not ours. The pixel ID installed by our plugin is 256804364741762.
(2) Identify and remove the plugin that installed the second pixel, or if it was manually installed, manually remove it. Having 2 pixels generally will cause problems with reporting. It could be the pixels are interfering and preventing purchases from firing correctly. From your previous message, it seems you might have already done this.

**Comment by lpienia** [comment] 2018-04-24 11:59
I finished cleaned up the settings. And also enabled "Enhanced Ecommerce Google Analytics" plugin by tavtic. 

Attached you will find the source code of the purchase page. The Purchase event was tracked by the Pixel Tool and how the event it's supposed to captured by Pixel Debugger Analytics

I think now it's working and it's compatible with the plugin that I mentioned. 

Regards, 

![fireshot capture 20 - analisis - zeva cosmetic_ - https___www facebook com_analytics_256804364741762](https://user-images.githubusercontent.com/7903381/39185394-6c656964-479d-11e8-800a-539d16ac44f3.png)
[FinalizarCompraURL.txt](https://github.com/facebookincubator/facebook-for-woocommerce/files/1942602/FinalizarCompraURL.txt)

**Comment by dmitridr** [comment] 2018-06-13 22:59
Great, glad to hear you got this working! You may want to upgrade for a further compatibility fix to v1.8.7, which was released in early May, if you haven't already. There was a fix for pixel events in that version involving the enhanced ecommerce plugin which you mentioned.

**Closed by dmitridr** 2018-06-13 22:59 UTC
