### ISSUE TITLE
Shortcodes are not processed in product descriptions

### ISSUE THREAD

**Issue by popforce** [facebookincubator/facebook-for-woocommerce#169] opened 2017-11-27 21:38 UTC
Shortcodes in product descriptions do not get processed leaving the description with possible incomplete data in facebook, e.g. age verification, product details.

**Comment by jieminz22** [comment] 2017-11-27 21:55
Hi, 

Which version are you using? Also, could you please send us a product URL that has this issue? Thanks.

**Comment by popforce** [comment] 2017-11-27 22:05
Hi jieminz22,

I'm using 1.6.6

Facebook: https://www.facebook.com/commerce/products/1381414951981284/
Shop: https://www.lifetex.eu/p/teppiche/einzelstuecke/nepali-mit-seide-indien/

**Comment by jieminz22** [comment] 2017-11-28 00:20
Hi,

Can you give us a list of detailed steps so that we can try them on our test servers and reproduce your problem?

Thanks.

**Comment by mengyingdu** [comment] 2017-11-28 01:09
Hi,

If you could upload you product set-up, especially the field including your shortcode, it will help much.

Thanks.

**Comment by popforce** [comment] 2017-11-28 01:33
Hey,

I'm using a simple shortcode `[ltad dbs="desc"]` in the post_content of the product/post, which inserts some text based on the dbs string. It's working fine with my amazon plugin (wp lister pro).

Thanks you for your effort.

_**Note on another issue**: You really should include a (translateable) text-box which is appended or prepended to each product description so you can show tax, shipping time, privacy etc. In my perception it is at least risky to be used in some markets, e.g. Germany and France._

**Comment by jieminz22** [comment] 2017-11-29 00:37
Hi,

We weren't able to reproduce this on our test servers. Would you mind send us some screenshot/video to help us reproduce the problem? Thanks.

**Comment by mengyingdu** [comment] 2017-12-21 17:56
Hello,

We fix this in [commit](https://github.com/facebookincubator/facebook-for-woocommerce/commit/44d071341638e43b8ba806000cee85a3da379d9d) and it's included in [v1.7.3](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.7.3) now. Can you try to upgrade and check whether your issue still exist?

Thanks.

**Comment by dmitridr** [comment] 2018-01-12 00:42
Closing, because we fixed this in 1.7.3.

**Closed by dmitridr** 2018-01-12 00:42 UTC
Labels: bug
