### ISSUE TITLE
Plugin imports Hidden products to store

### ISSUE THREAD

**Issue by aand01** [facebookincubator/facebook-for-woocommerce#341] opened 2018-03-23 13:36 UTC
The plugin completely ignores the 'Catalog visibility' flag that can be set for each product, and indiscriminately imports products that are explicitly set as hidden. 

Please correct this as soon as possible, as these products are of course not to be publicly displayed in the Facebook store.

Thanks,
- Asbjoern

**Comment by sammul** [comment] 2018-03-23 16:20
Sounds similar to issue #228

**Comment by sammul** [comment] 2018-03-25 00:26
@aand01 We'd like to fix it asap, but the problem is we cannot reproduce the issue on our test website. If you can share login credential with us, it would help us to figure out what's wrong. If you feel comfortable, please send it to our address ads_extension_woocommerce@fb.com. Thank you very much.

**Comment by aand01** [comment] 2018-03-25 10:51
Thanks @sammul, but when I try that email address, I get the following automated reply:

'Thanks for your message. We're no longer responding to emails that are sent to this address' 

How do I proceed then?

**Comment by aand01** [comment] 2018-03-26 16:25
Hi @sammul , with that email address not working, any other sugestions on how I can get this resolved? Thanks

**Comment by mengyingdu** [comment] 2018-03-26 21:34
Hi @aand01 ,

I found the cause now and will fix it in the next release ASAP.

There's a temporary workaround: can you click on 'update' on the product you refer to ? It should set your product back to staging (invisible for visitor except  you)

Let me know if that works for you.

Thanks!

**Comment by mengyingdu** [comment] 2018-03-30 17:21
Hi @aand01 ,

This should be fixed in [v1.8.3](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.8.3) 
Can you try:
1. woocommerce settings->integration->facebook-for-woocommerce -> advance option->delete your setting
2. wordpress plugin tag -> deactivate and delete your current plugin
3. download from the hyper link,  upload, activate
4. go back to your facebook-for-woocommerce panel under integration tab
5. set up your settings and sync products

Thanks.

**Comment by aand01** [comment] 2018-04-04 11:53
I can happily report that hidden products no longer show up after following the steps above to upgrade to v1.8.3 - thanks!

**Comment by mengyingdu** [comment] 2018-04-04 17:01
Thanks for your confirm and feedback!

**Closed by mengyingdu** 2018-04-04 17:01 UTC
Labels: bug

**Comment by mengyingdu** [comment] 2018-04-26 21:27
Hi @aand01 ,

If they are not published means only you (page admin) can see them. You can test by asking a friend or your test account. If you need help for other problems, feel free to open a new one.

Thanks.

**Comment by carworldnow** [comment] 2018-08-27 11:50
hi i also have same issue, am using Version 1.9.5
 a few hidden products added to the store but not published.
website: https://carworldnow.com 
fb shop: https://www.facebook.com/pg/CarworldNow/shop/?ref=page_internal

and in FB there is no Product option under Sop not able to delete also!!!

**Comment by carworldnow** [comment] 2018-08-27 11:51
the product can be view by everyone
