### ISSUE TITLE
Took down my optimized VPS server

### ISSUE THREAD

**Issue by metuza** [facebookincubator/facebook-for-woocommerce#173] opened 2017-11-30 15:37 UTC
Hello..

I just updated to the latest version and at the same time i reset the catalog setting and did a new catalog creation and upload of my 800 products. During the upload of the products i got wp_remote_request_error and ajax calls was overloaded, and then i got many 100s requests from facebook IP's and it took down my site. This has never happend before, i have noticed a slower site but not like now.

Ajax cart/checkout stopped working.

Any idea?

Brgds
Rune

**Comment by sillyonthestreet** [comment] 2017-11-30 16:41
Somewhat related, the plugin takes down my optimized VPS too:
https://github.com/facebookincubator/facebook-for-woocommerce/issues/166

**Comment by alexanderdejong** [comment] 2017-11-30 17:28
Can confirm, sync causes the application to crash. 

`facebook-settings.js?ts=1512062574:57 POST https://website.com/wp/wp-admin/admin-ajax.php 504 ()
(anonymous)
send @ load-scripts.php:4
ajax @ load-scripts.php:4
n.(anonymous function) @ load-scripts.php:4
ajax @ facebook-settings.js?ts=1512062574:57
check_queues @ facebook-settings.js?ts=1512062574:456
(anonymous) @ facebook-settings.js?ts=1512062574:440
facebook-settings.js?ts=1512062574:57 XHR failed loading: POST "https://website.com/wp/wp-admin/admin-ajax.php".`

**Comment by dmitridr** [comment] 2017-11-30 19:18
Hello,

Thanks for reporting this. Can you all share any PHP stack traces within your error logs with us? It will help us identify and solve the problem.

wp_remote_request_error is likely coming from our auto-upgrade feature that was added. You can try disabling it by commenting out [these lines](https://github.com/facebookincubator/facebook-for-woocommerce/blob/1addf68f425fc40ace533553e8294f1d157ddef2/includes/fb-github-plugin-updater.php#L48-L52) using the wp plugin editor, to see if that fixes the problem.

**Comment by metuza** [comment] 2017-11-30 19:40
Well, i did not get any errors in my logs related to your plugin other than when i tested my checkout page for klarna gateway at the same time the product upload was in process - it was at that point i figured out that something was very wrong because none of the ajax calls was working and i found the below in my error-logs.

[30-Nov-2017 14:49:30 UTC] PHP Fatal error:  Uncaught Klarna_Checkout_ConnectionErrorException: wp_remote_request_error http_request_failed - cURL error 28: Operation timed out after 10001 milliseconds with 0 out of 0 bytes received, (url: ) in /home/www/arctic-fritid.no/wp-content/plugins/woocommerce-gateway-klarna/vendor/klarna/checkout/src/Klarna/Checkout/HTTP/WPTransport.php:110
Stack trace:
#0 /home/www/arctic-fritid.no/wp-content/plugins/woocommerce-gateway-klarna/vendor/klarna/checkout/src/Klarna/Checkout/BasicConnector.php(342): Klarna_Checkout_HTTP_WPTransport->send(Object(Klarna_Checkout_HTTP_Request))
#1 /home/www/arctic-fritid.no/wp-content/plugins/woocommerce-gateway-klarna/vendor/klarna/checkout/src/Klarna/Checkout/BasicConnector.php(119): Klarna_Checkout_BasicConnector->handle('GET', Object(Klarna_Checkout_Order), Array, Array)
#2 /home/www/arctic-fritid.no/wp-content/plugins/woocommerce-gateway-klarna/vendor/klarna/checkout/src/Klarna/Checkout/Order.php(106): Klarna_Checkout_BasicConnector->apply('GET', Object(Klarna_Checkout_Order), Arr in /home/www/arctic-fritid.no/wp-content/plugins/woocommerce-gateway-klarna/vendor/klarna/checkout/src/Klarna/Checkout/HTTP/WPTransport.php on line 110
[30-Nov-2017 14:50:04 UTC] PHP Notice:  Undefined variable: https://checkout.klarna.com/checkout/orders/5Z5ODPMDJ5J8H6XOJBMWM4VOI7N in /home/www/arctic-fritid.no/wp-content/plugins/woocommerce-gateway-klarna/vendor/klarna/checkout/src/Klarna/Checkout/HTTP/WPTransport.php on line 111
[30-Nov-2017 14:51:21 UTC] PHP Notice:  Undefined variable: https://checkout.klarna.com/checkout/orders/5ZLGUIYFMNTX5UO6LCX9QHMYYSN in /home/www/arctic-fritid.no/wp-content/plugins/woocommerce-gateway-klarna/vendor/klarna/checkout/src/Klarna/Checkout/HTTP/WPTransport.php on line 111
[30-Nov-2017 14:51:47 UTC] PHP Notice:  Undefined variable: https://checkout.klarna.com/checkout/orders/5ZNI5SVX5ODAOMVGREG303HC7FV in /home/www/arctic-fritid.no/wp-content/plugins/woocommerce-gateway-klarna/vendor/klarna/checkout/src/Klarna/Checkout/HTTP/WPTransport.php on line 111
[30-Nov-2017 14:56:55 UTC] PHP Notice:  Undefined variable: https://checkout.klarna.com/checkout/orders/5ZEPLPSB4L6NT63HDEXDW3BXQCD in /home/www/arctic-fritid.no/wp-content/plugins/woocommerce-gateway-klarna/vendor/klarna/checkout/src/Klarna/Checkout/HTTP/WPTransport.php on line 111
[30-Nov-2017 14:57:17 UTC] PHP Notice:  Undefined variable: https://checkout.klarna.com/checkout/orders/5Z2RO87K8DFAU6R19Y53ETL0NV1 in /home/www/arctic-fritid.no/wp-content/plugins/woocommerce-gateway-klarna/vendor/klarna/checkout/src/Klarna/Checkout/HTTP/WPTransport.php on line 111
[30-Nov-2017 14:57:17 UTC] PHP Fatal error:  Uncaught Klarna_Checkout_ConnectionErrorException: wp_remote_request_error http_request_failed - cURL error 28: Operation timed out after 10000 milliseconds with 0 bytes received, (url: ) in /home/www/arctic-fritid.no/wp-content/plugins/woocommerce-gateway-klarna/vendor/klarna/checkout/src/Klarna/Checkout/HTTP/WPTransport.php:110

**Comment by mengyingdu** [comment] 2017-11-30 19:51
Hi @metuza ,

Thanks for your information. Can you tell us your store url? or Facebook page?

From your log, there's nothing related to our plugin. I need more information to investigate your problem.

Thanks.

**Comment by mengyingdu** [comment] 2017-11-30 19:52
Hi @alexanderdejong ,

Did you also use woocommerce-gateway-klarna? Can you tell us your store url or Facebook Page?

Thanks.

**Comment by metuza** [comment] 2017-11-30 20:06
Well the problem was already there and site was on its way down during the catalog creation and product upload process, somehow it was like all ajax functionality dissapeared and site was very very slow - It was at that point i just checked my checkout page and the error was generated. If i have not visited the checkout page there has been no errors in my log.

Also after that the catalog was generated and all products was uploaded i did register hundreds or even thousands of hits from facebook hitting every one of the product pages over and over and it was then my site went down.

Anyway here is my FB site: https://www.facebook.com/ArcticFritid

Brgds
Rune

**Comment by mengyingdu** [comment] 2017-11-30 20:14
Thank @metuza , I'm looking into this issue now.

**Comment by mengyingdu** [comment] 2017-11-30 20:21
I checked your site, you're right that it's very slow now. Did  you try to comment out the lines mentioned by @dmitridr ? Does it help?

**Comment by mengyingdu** [comment] 2017-11-30 22:29
Hi @metuza, @alexanderdejong and @sillyonthestreet,

We just push [v1.7.1](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.7.1) to fix this issue. Can you upgrade and try to check whether it fix your issue?

Thanks.

**Comment by alexanderdejong** [comment] 2017-11-30 22:42
@mengyingdu the update didn't fix the problem during update. 

When I try to visit my shop I get the following error:

`Gateway Timeout
The gateway did not receive a timely response from the upstream server or application.`

Here is a snippet from my log: 

`[30-Nov-2017 22:38:00 UTC] Pushing post to queue: 1086
[30-Nov-2017 22:38:00 UTC] Pushing post to queue: 1070
[30-Nov-2017 22:38:00 UTC] Pushing post to queue: 1071
[30-Nov-2017 22:38:00 UTC] Pushing post to queue: 1072
[30-Nov-2017 22:38:00 UTC] Pushing post to queue: 1073
[30-Nov-2017 22:38:00 UTC] Pushing post to queue: 1074
[30-Nov-2017 22:38:00 UTC] Pushing post to queue: 1078
[30-Nov-2017 22:38:19 UTC] <b>Facebook for WooCommerce</b><br/>Unsupported post request. Object with ID '1614962571897272' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api
[30-Nov-2017 22:38:19 UTC] {"headers":{},"body":"{\"error\":{\"message\":\"Unsupported post request. Object with ID '1614962571897272' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https:\\\/\\\/developers.facebook.com\\\/docs\\\/graph-api\",\"type\":\"GraphMethodException\",\"code\":100,\"error_subcode\":33,\"fbtrace_id\":\"EqbtbyHM+A+\"}}","response":{"code":400,"message":"Bad Request"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
[30-Nov-2017 22:38:19 UTC] <b>Facebook for WooCommerce</b><br/>Unsupported post request. Object with ID '1443744665754197' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api
[30-Nov-2017 22:38:19 UTC] {"headers":{},"body":"{\"error\":{\"message\":\"Unsupported post request. Object with ID '1443744665754197' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https:\\\/\\\/developers.facebook.com\\\/docs\\\/graph-api\",\"type\":\"GraphMethodException\",\"code\":100,\"error_subcode\":33,\"fbtrace_id\":\"DOGcy\\\/TkXaD\"}}","response":{"code":400,"message":"Bad Request"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
[30-Nov-2017 22:38:22 UTC] <b>Facebook for WooCommerce</b><br/>Unsupported post request. Object with ID '1542632419155986' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api
[30-Nov-2017 22:38:22 UTC] {"headers":{},"body":"{\"error\":{\"message\":\"Unsupported post request. Object with ID '1542632419155986' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https:\\\/\\\/developers.facebook.com\\\/docs\\\/graph-api\",\"type\":\"GraphMethodException\",\"code\":100,\"error_subcode\":33,\"fbtrace_id\":\"FxHAtpkUTr8\"}}","response":{"code":400,"message":"Bad Request"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
[30-Nov-2017 22:38:40 UTC] {"headers":{},"body":"{\"success\":true}","response":{"code":200,"message":"OK"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
[30-Nov-2017 22:38:44 UTC] {"headers":{},"body":"{\"success\":true}","response":{"code":200,"message":"OK"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
[30-Nov-2017 22:38:48 UTC] {"headers":{},"body":"{\"success\":true}","response":{"code":200,"message":"OK"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
[30-Nov-2017 22:38:51 UTC] {"headers":{},"body":"{\"success\":true}","response":{"code":200,"message":"OK"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
[30-Nov-2017 22:38:54 UTC] {"headers":{},"body":"{\"success\":true}","response":{"code":200,"message":"OK"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
[30-Nov-2017 22:38:58 UTC] {"headers":{},"body":"{\"success\":true}","response":{"code":200,"message":"OK"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}`

**Comment by dmitridr** [comment] 2017-11-30 22:57
Hmm. Looks like this is a perf issue then, the site slows down so much during product sync that it appears to go down. Is that correct?

Is there an issue outside of product sync as well, or only during sync?

**Comment by dmitridr** [comment] 2017-11-30 23:13
We can't reproduce this issue on our test servers. Can you all try commenting out 

[these lines](https://github.com/facebookincubator/facebook-for-woocommerce/blob/master/facebook-commerce.php#L128-L147) by using the wp plugin editor (Plugins > Facebook For WooCommerce > Edit), and doing a force resync to see if that helps? This will remove the auto-updating functionality as well as a new info message, both of which are not necessary for the plugin to operate.

**Comment by alexanderdejong** [comment] 2017-11-30 23:31
I commented out the lines your referenced but alas this did not help. 

Just checked my log again and there are many "pushing post to queue" occurring at the same time:

```
[30-Nov-2017 23:25:16 UTC] Starting background sync to Facebook: 256 products...
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 2307
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 2309
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 2305
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 2302
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 2300
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 2297
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 2295
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 2292
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 2290
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 2288
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 2286
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 2285
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 2282
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 2281
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 2276
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 2272
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 2268
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 2264
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 2260
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 2256
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 2252
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 2247
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 2244
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 2242
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 2239
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 2236
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 2231
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 2188
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 2190
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 2180
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 2183
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 2186
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 2174
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 2177
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 2161
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 2164
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 2167
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 2169
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 2171
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 2143
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 2146
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 2149
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 2152
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 2156
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 2134
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 2136
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 2140
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 2131
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 2138
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 2129
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 2126
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 2028
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 2032
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 2035
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 2038
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 2016
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 2019
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 2022
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 2025
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 2001
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 2004
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 2007
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 2010
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 2013
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1992
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1995
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1998
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1986
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1989
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1971
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1974
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1977
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1980
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1983
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1956
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1959
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1962
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1965
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1968
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1950
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1953
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1944
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1947
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1926
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1929
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1932
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1935
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1939
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1942
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1905
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1909
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1912
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1916
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1919
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1923
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1898
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1884
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1891
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1864
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1872
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1878
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1850
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1858
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1823
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1833
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1842
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1808
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1815
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1792
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1799
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1716
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1720
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1723
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1711
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1714
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1671
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1673
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1675
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1696
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1699
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1702
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1705
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1708
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1655
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1661
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1666
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1645
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1650
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1640
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1630
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1635
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1620
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1625
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1605
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1610
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1615
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1595
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1600
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1580
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1585
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1590
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1574
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1576
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1578
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1567
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1569
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1548
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1553
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1560
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1526
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1528
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1530
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1532
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1534
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1536
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1538
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1543
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1513
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1522
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1524
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1508
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1510
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1493
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1500
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1504
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1469
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1482
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1489
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1473
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1478
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1458
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1464
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1445
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1451
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1362
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1363
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1364
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1365
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1366
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1367
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1439
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1360
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1361
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1351
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1355
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1356
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1357
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1358
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1359
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1343
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1347
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1334
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1326
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1318
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1309
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1314
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1295
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1299
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1304
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1291
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1292
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1277
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1284
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1266
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1274
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1251
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1255
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1258
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1247
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1240
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1243
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1232
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1236
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1221
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1222
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1223
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1226
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1229
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1212
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1216
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1217
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1203
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1204
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1208
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1199
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1191
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1195
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1181
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1186
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1171
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1176
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1161
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1166
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1155
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1143
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1149
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1131
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1137
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1121
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1125
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1113
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1117
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1101
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1105
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1109
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1090
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1094
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1098
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1082
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1086
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1070
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1071
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1072
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1073
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1074
[30-Nov-2017 23:25:16 UTC] Pushing post to queue: 1078
```

Maybe this shouldn't occur so quickly?

**Comment by tahoff** [comment] 2017-11-30 23:39
@alexanderdejong Did those messages print out much slower in previous versions?

**Comment by alexanderdejong** [comment] 2017-11-30 23:44
@tahoff I can't say...  as I just started using your plugin and troubleshooting yesterday. It hasn't worked optimally for me yet. I'll try a previous version tomorrow and see what happens.

**Comment by mengyingdu** [comment] 2017-12-01 01:47
Hi,

We send [v1.7.2](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.7.2) to fix this urgent issue. Can you try it?

Thanks.

**Comment by mengyingdu** [comment] 2017-12-01 19:39
Hi @metuza ,

I went to your website and it seems you haven't installed 1.7.2, can you upgrade? I think it should solve your site loading issue.

Thanks.

**Comment by metuza** [comment] 2017-12-01 21:01
Hi @mengyingdu 

Sorry for the delay, been busy with a conflict in my checkout page and i guess that is why you have found my site very slow - the cache has been disabled. It should now load in less than 1.6sec

Anyway, i have installed 1.7.2 and so far everything looks ok, but i have not done any test of the force product re-sync option as i will wait tils my customers goes to bed in case of same problems like with 1.7.0. :)

But i do not think i will see any issues during the re-sync as that always has been fast and ok. The problem has mostly been seen when i delete the catalog and totally reset/re-create catalog and upload new products. Then it has always slowing down my site a little and with 1.7.0 it totally chrashed site.

I'll check re-sync later this evening.

Brgds
Rune

**Comment by metuza** [comment] 2017-12-02 13:30
Ok, just did a force re-sync and everything went smooth and fast. Products and prices beeing updated, all ok.

Thanks

**Comment by mengyingdu** [comment] 2017-12-03 08:03
Thanks @metuza for your confirmation and update. I will close this issue for now, if the problem persists please create a new issue and reference this one.

**Closed by mengyingdu** 2017-12-03 08:03 UTC
Labels: Do this ASAP
