### ISSUE TITLE
Compatibility Issue : Google Enhanced E-Commerce. ViewContent firing error.

### ISSUE THREAD

**Issue by zzbeck** [facebookincubator/facebook-for-woocommerce#319] opened 2018-03-07 20:04 UTC
Hello!
I have noticed an issue, and I guess I am not the only one with this issue.

When I am logged in, all events seems to fire just fine, but as soon as I'm logged out, there is an issue with the "ViewContent". Take a look at the attached images.

Update: I noticed that the issue is happening when Google Enhanced E-commerce I active on the site.

<img width="354" alt="skaermbillede 2018-03-07 kl 21 02 58" src="https://user-images.githubusercontent.com/35366575/37115343-27d0ad08-224b-11e8-962d-6d4ee0d16b16.png">
<img width="343" alt="skaermbillede 2018-03-07 kl 21 03 05" src="https://user-images.githubusercontent.com/35366575/37115344-2815486e-224b-11e8-9ff1-4341a75b1b4e.png">

**Comment by zzbeck** [comment] 2018-03-08 10:17
When I disable enhanced e-commerce, there is no problem. The problem only seems to be happening with your plugin, I have tried PixelYouSite, that works with no trouble.

**Comment by jieminz22** [comment] 2018-03-08 18:10
Looks like our plugin is not compatible with Google Enhanced E-commerce. I'm marking this as a feature request to support compatibility with it. Currently you will have to disable enhanced e-commerce to make our plugin work. Sorry for the inconvenience.

**Comment by dmitridr** [comment] 2018-05-15 03:33
We fixed this compatibility in 1.8.7, it's available [here](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.8.7). Please open a new issue and reference this one if the problem occurs again.

Details : The issue was one of JS insertion into WooCommerce, both our plugin and Google do this insertion, however because of the way the insertion works our JS is inserted in between the Google tracking code, which appears to be the cause of the problem, we changed the insertion so that ours is inserted above the Google code, which should prevent interference.

**Closed by dmitridr** 2018-05-15 03:33 UTC
Labels: compatibility, feature-request, follow-up for next release
