### ISSUE TITLE
Very high CPU usage, very slow sync

### ISSUE THREAD

**Issue by thatlorenzo** [facebookincubator/facebook-for-woocommerce#363] opened 2018-03-30 17:28 UTC
Hi,

in my case the plugin is causing problems with the CPU usage. I have a GrowBig SiteGround hosting plan, so that sounded pretty strange. I have already contacted SiteGround, they say it's because of too many hits on adim-ajax.php.

This is a screenshot where you can see what happens when I deactivate the plugin, then activate it again.
![cpu_usage](https://user-images.githubusercontent.com/37937744/38146874-2e718ff8-3450-11e8-8c85-7267ba4027df.png)

plugin 1.8.2, Wordpress 4.9.4, Woocommerce 3.3.4, PHP 5.6.30
My FB page: http://facebook.com/lcsellaio
My WC shop: https://lcsellaio.it

They suggested to increase the Heartbeat interval (now it's 150, from the initial 15 seconds), optimize the db and schedule a cron job insted of the standard call for wp-cron. Unfortunately nothing changed: as you can see from the screenshot, after the suggested changes I restarted the plugin at 17:00 and CPU went again to roof... 

I have more or less 100 items in my shop, but many variations on each item. 
Synching is taking weeks. 

I started with 1.7.3 I think, then upgraded to 1.8.2, and re-configured the plugin like suggestes in other threads. Now If ask for a re-synch I receive a yellow warning telling I have to wait for the end of the current re-synch.

Thank you,

Lorenzo

**Comment by mengyingdu** [comment] 2018-04-02 17:36
Hi,

1. problem for re-sync
I found API error from your site because the associated catalog has been deleted (when you ask for a re-sync). I think there is sth wrong between your re-config and force re-sync. Also, we have more fixes for sync issues in [v1.8.3](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.8.3). Can you try to follow the re-config instruction and re-setup?

2. high CPU issue
Does it happen only during the short period after initial sync? Or all the times?
It's very difficult to figure out the cause since every server is different and we can't repo your issue on our dev.

Thanks.

**Comment by thatlorenzo** [comment] 2018-04-03 08:21
Hi,

1. I deleted the partial catalog upload because the sync process stopped after few days and I couldn't force it anymore (nothing happened when I pressed the button). I recently downloaded 1.8.3, deactivated and deleted 1.8.2 and installed and reconfigured the plugin. This is the CPU usage now:
![cpu_usage_1 8 3](https://user-images.githubusercontent.com/37937744/38237709-375766da-3728-11e8-801c-3ae3ec0114e1.png)

2. I can't answer precisely because I never been able to perform a complete upload of my catalog, so the plugin is always synching and the CPU usage is very high. When in the past days the sync process got stuck (before I deleted the catalog), my server CPU was back to normal.

Thank you.

**Comment by mengyingdu** [comment] 2018-05-25 16:03
Hi @thatlorenzo ,

There's the [commit](https://github.com/facebookincubator/facebook-for-woocommerce/commit/c7d75756fc7cf9853d1d245c9ce336a23c805d39) to improve the query loop in our plugin which will improve CPU quite a bit. If you are still interested in our plugin, can you reconfig and download, install the latest version?

Thanks.

**Comment by mengyingdu** [comment] 2018-06-17 18:57
This was fixed in [v1.9.0](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.9.0)

**Closed by mengyingdu** 2018-06-17 18:57 UTC
Labels: enhancement, follow-up for next release
