### ISSUE TITLE
Certain Products Not Showing Image

### ISSUE THREAD

**Issue by ThePrimroseMarket** [facebookincubator/facebook-for-woocommerce#489] opened 2018-05-17 17:47 UTC
I've deleted my store, reconfigured and deleted all settings. I just uploaded all of my products into my Facebook Shop and again the same 6 products will not show an image. The listing is there but with a blank picture. I'm losing my mind. I have no idea what else to do. I can resync all day and they still won't show. Please help.

My shop page: https://www.facebook.com/pg/ThePrimroseMarket/shop/?rt=29&ref=page_internal

**Comment by sammul** [comment] 2018-05-17 21:05
[Note : This is an Automated Message]

Hello,

Thanks for your interest in our plugin!
Due to a high volume of issues we may not be able to get to yours immediately.

If this is a feature request, or feedback, please reply with
`Feature Request` or `Feedback` and it will be categorized accordingly, and
we will read it and reply when we can.

If you are experiencing problems, read on.

First. Please check to see if your issue is not a duplicate of another one.
To search our issues, use the search feature at the top of the GitHub issues page.
We have nearly 500 existing and past issues, so it is fairly likely someone else has already reported your problem.
If you do find a relevant issue, please comment in that issue, and close this one.
It helps us prioritize issues to tackle by looking at the number of people with the same problem.

If your issue is unique, and you are sure, then read on.
We require the following information in order to help you:
- WooCommerce Version
- Wordpress Version
- Plugin Version. Please Note that we do not support outdated versions of the plugin.
- A Screenshot of where you see the problem. If it is on Facebook, a screenshot of Facebook,
if it is on WooCommerce, a screenshot of WooCommerce. If it is in multiple places, multiple screenshots.
- The URL of your website.
- The URL of your page.
- The URL(s) where you took your screenshot(s).
- (If applicable) Detailed steps you took in order to see the problem.

Please be advised, it may take us some time to get to your issue.
In the meantime, below are generic approaches you can take that may solve the issue :
- Upgrade to the latest version.
- Force Resync
- Reset the plugin using `Reconfigure > Advanced Options > Delete` and setup again.
- Try to deactivate other plugins which you think could be interfering and repeating the above.

When you have the above data for us, please include
`Debug Ready` in your reply. We will get to it and debug it as soon as we can.

Thanks for your patience,
Dev Team (@dmitridr, @mengyingdu, @sammul, @jieminz22)

**Comment by mengyingdu** [comment] 2018-06-28 15:42
Hi @ThePrimroseMarket ,

I have checked your fb shop: all products currently have images now.

Tips:
Once completing setup, you can see you products instantly. But the images will take couple of hours to populate due to cache and storage issues.

Thanks.

**Closed by mengyingdu** 2018-06-28 15:42 UTC
Labels: Automated : Need More Info
