### ISSUE TITLE
Differentiate title for variable products

### ISSUE THREAD

**Issue by lmartins** [facebookincubator/facebook-for-woocommerce#490] opened 2018-05-17 19:04 UTC
Hi,

I've been using this plugin to send data to a Facebook catalog where we use variable products. Is there any way we could have the product title being differentiated between the multiple variants of a single product?
Right now it shows the same title for all variants, which makes sense given that variants do not have a title, however it would be useful to have an easier way to differentiate the products while on the Facebook catalog.

Thanks!

**Comment by sammul** [comment] 2018-05-17 21:05
[Note : This is an Automated Message]

Hello,

Thanks for your interest in our plugin!
Due to a high volume of issues we may not be able to get to yours immediately.

If this is a feature request, or feedback, please reply with
`Feature Request` or `Feedback` and it will be categorized accordingly, and
we will read it and reply when we can.

If you are experiencing problems, read on.

First. Please check to see if your issue is not a duplicate of another one.
To search our issues, use the search feature at the top of the GitHub issues page.
We have nearly 500 existing and past issues, so it is fairly likely someone else has already reported your problem.
If you do find a relevant issue, please comment in that issue, and close this one.
It helps us prioritize issues to tackle by looking at the number of people with the same problem.

If your issue is unique, and you are sure, then read on.
We require the following information in order to help you:
- WooCommerce Version
- Wordpress Version
- Plugin Version. Please Note that we do not support outdated versions of the plugin.
- A Screenshot of where you see the problem. If it is on Facebook, a screenshot of Facebook,
if it is on WooCommerce, a screenshot of WooCommerce. If it is in multiple places, multiple screenshots.
- The URL of your website.
- The URL of your page.
- The URL(s) where you took your screenshot(s).
- (If applicable) Detailed steps you took in order to see the problem.

Please be advised, it may take us some time to get to your issue.
In the meantime, below are generic approaches you can take that may solve the issue :
- Upgrade to the latest version.
- Force Resync
- Reset the plugin using `Reconfigure > Advanced Options > Delete` and setup again.
- Try to deactivate other plugins which you think could be interfering and repeating the above.

When you have the above data for us, please include
`Debug Ready` in your reply. We will get to it and debug it as soon as we can.

Thanks for your patience,
Dev Team (@dmitridr, @mengyingdu, @sammul, @jieminz22)

**Comment by erdoslaszlo** [comment] 2018-05-22 12:33
Feedback

**Comment by dmitridr** [comment] 2018-06-11 21:37
Hello,

Thanks for the feedback!

There is a way to do this already, but it's not very easy, you'd have to do a code modification and use our filter to change the title of the variants as you see fit. 
#48 has an example of how this can be done for product images, adapting it to titles would be something like this : 

```
add_filter( 'facebook_for_woocommerce_integration_prepare_product', 'wc_fb_custom_title', 10, 2);
function wc_fb_custom_title($product, $id){
  $product['name'] = $product['name'].' Custom Title: '.$id;
  return $product;
}
```
Will append `Custom Title X` to every product title. With some further work you could only append this title if the product is a variant.

***

Regarding surfacing this in our UI as a feature of the plugin...
I'm not sure how we can ad this as a feature, because variations will appear in ads if you run ads, and the title of the product is prominent in the ad, so it would not make much sense to show 'Shirt - Variant 1' in the ad, as that would be a poor user experience. I imagine if we did this, many would complain saying that their ads are now performing worse because we added something strange to the end of the titles.

*** 

We will also give this feedback to the team that manages the `Catalog Manager` interface. Perhaps they can do something on that interface which will uniquely identify the products without changing the plugin. Thanks!

**Comment by lgfogle** [comment] 2020-04-06 23:16
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!

**Closed by lgfogle** 2020-04-06 23:16 UTC
Labels: Feedback, feature-request
