### ISSUE TITLE
Pixel Not Loading On Any Page

### ISSUE THREAD

**Issue by renesm34** [facebookincubator/facebook-for-woocommerce#307] opened 2018-03-03 15:17 UTC
Hi good day, I'm trying to add my FB pixel to my woocommerce store, I folllowed every step of the plugin to link my fb account and my online store, but once it's done and i check the pixel status, it seems that the pixel can be found but it is not being loaded so no info is sent back to facebook.

my site: https://dogemaster.com

"PageView
ERRORS
The Facebook pixel code on this page didn't load, so no information was sent to Facebook."

Is there something i might be doing wrong or missing?

Thanks beforehand :)

**Comment by mengyingdu** [comment] 2018-03-05 18:12
Hi @renesm34 ,

This is what i see on your site:
![screen shot 2018-03-05 at 10 11 08 am](https://user-images.githubusercontent.com/24535640/36991769-9acf2f90-205d-11e8-93da-971a43b30b81.png)

Where did you see the errors? A screen shot will help more.

Thanks.

**Comment by dmitridr** [comment] 2018-03-15 20:13
Hey @renesm34 

I checked your site with the pixel helper, everything looks fine! (Nice site by the way!)
I think you may see errors with the pixel if you have uBlock or very aggressive versions of adblock enabled.

I'm closing this issue but if that's not the cause please let us know by filing a new issue!

**Closed by dmitridr** 2018-03-15 20:13 UTC
Labels: question
