### ISSUE TITLE
Edit Product Page is in a constant state of loading after I click Update

### ISSUE THREAD

**Issue by mouseacookie** [facebookincubator/facebook-for-woocommerce#453] opened 2018-05-02 17:15 UTC
I've deactivated all other plugins and reactivated one by one. Once I hit Update, the page just stays loading. Not sure where to go from here. I'm using 1.8.5 as 1.8.6 caused other errors.

**Comment by mouseacookie** [comment] 2018-05-02 17:34
symptoms of your problem -- constant state of reload after Update
screen shot if possible
your Facebook page url http://facebook.com/25vintageplace
your website url http://25vintageplace.com
current version of 
Facebook-for-WooCommerce, 1.8.5
WooCommerce, 3.3.5
Wordpress, 4.9.5
PHP 7.1

**Comment by dmitridr** [comment] 2018-05-07 21:48
Hi, I checked your site. Seems like your products uploaded, are you still having the issue?
If you still do have the problem, I suggest updating to 1.8.7 and doing a full reset of the plugin. 

If you've used plugin versions 1.7.x and below, there could be potential issues like the one you described after upgrading to 1.8.x. This is because we significantly changed the way product upload works.

Let me know if the problem isn't fixed by the above and we can continue to try and resolve it.

**Comment by dmitridr** [comment] 2018-06-13 22:21
I'm closing this out because there hasn't been a reply, if you still have this problem, encourage you to open a new issue and reference this one!

**Closed by dmitridr** 2018-06-13 22:21 UTC
Labels: question
