### ISSUE TITLE
The Elegant You

### ISSUE THREAD

**Issue by innapk6** [facebookincubator/facebook-for-woocommerce#1660] opened 2020-10-27 21:44 UTC
New plugin "Facebook for WooCommerce" gives an error after upgrade
![Screenshot 2020-10-27 17 34 38](https://user-images.githubusercontent.com/50779912/97365439-0f802600-187c-11eb-9768-0f268f73ad69.png)

**Comment by simonporter007** [comment] 2020-10-28 17:08
Duplicate of #1652

**Closed by simonporter007** 2020-10-28 17:08 UTC
Labels: duplicate
