### ISSUE TITLE
Products Won't Sync : Bulk Edit Interfering?

### ISSUE THREAD

**Issue by kristiyan22** [facebookincubator/facebook-for-woocommerce#527] opened 2018-06-04 18:53 UTC
Hello, 
I have issues with the plugin. Today I accidentally deleted all my settings and now I can't sync again my products. I have a lot (around 1700 products, 60 000+ variations) before it worked well, but now it doesn't. I tried deleting the plugin and reinstalling, force product resync, deleting the settings and again and again, even deleted my pixel from the website and add it again, still didn't work. When I go in the integration of Woocommerce  I have buttons "Force products resync" , "Re-configure Facebook Settings" and also after this "Status: Products are synced to Facebook." and "Progress: 1000 items remaining." but it's not making any progress.
My facebook page is https://www.facebook.com/bgpano/ 
and my pixel ID is 171548127 :)
Please help me resolve this issue!
Best Regards,
Kristiyan

**Comment by dmitridr** [comment] 2018-06-05 00:37
[Note : This is an Automated Message]

Hello,

Thanks for your interest in our plugin!
Due to a high volume of issues we may not be able to get to yours immediately.

If this is a feature request, or feedback, please reply with
`Feature Request` or `Feedback` and it will be categorized accordingly, and
we will read it and reply when we can.

If you are experiencing problems, read on.

First. Please check to see if your issue is not a duplicate of another one.
To search our issues, use the search feature at the top of the GitHub issues page.
We have nearly 500 existing and past issues, so it is fairly likely someone else has already reported your problem.
If you do find a relevant issue, please comment in that issue, and close this one.
It helps us prioritize issues to tackle by looking at the number of people with the same problem.

If your issue is unique, and you are sure, then read on.
We require the following information in order to help you:
- WooCommerce Version
- Wordpress Version
- Plugin Version. Please Note that we do not support outdated versions of the plugin.
- A Screenshot of where you see the problem. If it is on Facebook, a screenshot of Facebook,
if it is on WooCommerce, a screenshot of WooCommerce. If it is in multiple places, multiple screenshots.
- The URL of your website.
- The URL of your page.
- The URL(s) where you took your screenshot(s).
- (If applicable) Detailed steps you took in order to see the problem.

Please be advised, it may take us some time to get to your issue.
In the meantime, below are generic approaches you can take that may solve the issue :
- Upgrade to the latest version.
- Force Resync
- Reset the plugin using `Reconfigure > Advanced Options > Delete` and setup again.
- Try to deactivate other plugins which you think could be interfering and repeating the above.

When you have the above data for us, please include
`Debug Ready` in your reply. We will get to it and debug it as soon as we can.

Thanks for your patience,
Dev Team (@mengyingdu, @sammul, @jieminz22, @dmitridr)

**Comment by kristiyan22** [comment] 2018-06-05 10:07
Hello,
Everything is up to date : plugin version 1.8.7. , woocommerce version 3.2.1. , wordpress version 4.9.6
When I start the setup I complete it and everything looks fine:
![1](https://user-images.githubusercontent.com/39924237/40969501-b9577a48-68c0-11e8-8a3e-bcc012152862.PNG)
But then this happens...
![2](https://user-images.githubusercontent.com/39924237/40969553-dcee44a0-68c0-11e8-9cc9-80efe119b99a.PNG)
Sometimes it says that Its processing 1000 items, but the number is not moving and they are not uploading to my facebook catalog 
![3](https://user-images.githubusercontent.com/39924237/40969621-0e3e8204-68c1-11e8-9c7f-c1353aab764a.PNG)
I tried to delete settings, delete the plugin and install it again, delete my adblock, detele the pixel code from my website, stopped all my ongoing facebook ad campaigns and I dont know what else I can do.
Facebook page: https://www.facebook.com/bgpano/
web url: http://pano.bg/
Pixel ID: 166739863926710

**Comment by kristiyan22** [comment] 2018-06-06 07:36
Hello,
Are you looking into this problem? I'm stuck from 2 days on "Progress: 1000 items remaining" and nothing changes. I tried again to delete the plugin, install again, old version, new version, old version of woocommerce, the newest version of woocommerce, delete the settings Reconfigure > Advanced Options > Delete a couple of times etc etc. Can you please take a look into this problem :) 
Thank you in advance.

**Comment by hamutalwz** [comment] 2018-06-11 07:49
I'm having the same problem. The plugin stopped syncing with Facebook and keep saying "Something wrong when uploading, please try again" and I keep trying again and again like you did.
I have an open ticket from May 1st and the last response I got was a month ago!

**Comment by kristiyan22** [comment] 2018-06-11 08:13
Hello,
I'm sorry to hear you have the same problem. I found that bulk edit via
plugin is making the facebook for woocommerce not working. I stopped bulk
editing with the plugin, but still not fixed. You have to start your plugin
and "sync" your products, even thought they are not gonna sync
automatically like before, you can go and update every single product.
After you click update, they will appear in your catalog and shop :)

Hope I helped,
Greetings

2018-06-11 10:49 GMT+03:00 Hamutal <notifications@github.com>:

**Comment by hamutalwz** [comment] 2018-06-11 08:33
Hi Kristiyan,
Thanks for trying to help. Unfortunately, even when updating a single product the sync does not work.
I get an error message saying: "Facebook extension error: Facebook for WooCommerce
Unsupported post request. Object with ID '962090333962545' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api"

**Comment by kristiyan22** [comment] 2018-06-11 08:47
I get that message too, but they sync in the catalog :)

2018-06-11 11:33 GMT+03:00 Hamutal <notifications@github.com>:

**Comment by hamutalwz** [comment] 2018-06-11 09:16
In my case they don't. The Facebook catalog remains empty.

**Comment by dmitridr** [comment] 2018-06-26 00:07
Hi,

Apologies in the delay in getting back to you. Your issue wasn't flagged for manual review by our automated system since `Debug Ready` was not included in the reply. 

Looks like you have figured out a workaround, I'm glad to hear that at least. But I'm interested in what the problem with bulk editing is making the plugin not work. Could you explain a bit further how you found out that the bulk editing is interfering?

**Comment by lgfogle** [comment] 2020-04-06 23:17
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!

**Closed by lgfogle** 2020-04-06 23:17 UTC
Labels: Automated : Multiple Reports, bug, workaround
