### ISSUE TITLE
Facebook for WooCommerce - Access Token keeps expiring 

### ISSUE THREAD

**Issue by Hashtag1975** [facebookincubator/facebook-for-woocommerce#962] opened 2019-04-20 14:56 UTC
Hi,

I have installed the Facebook for WooCommerce plugin however, it is not working as expected.

I have just 103 products that need to be synced with Facebook and Instagram but I can't get this to work.  I am therefore unable to display my products and take advantage of all that Instagram shopping has to offer.

Steps taken to install the Facebook for WooCommerce plugin as follows:

1. Navigate to https://hashtagdeals.co.uk/wp-admin/plugins.php and locate the plugin.

2. Click on the settings link and navigate to the Facebook for WooCommerce Business Settings PopUp box.  

3. Work my way through the setup procedure (Facebook Page, Facebook Pixel, Your Products, and Ad Setup). Some of the information seems to populate automatically as I am logged into my Facebook account on another browser tab.  The 103 products are also displayed in the background of the Your Products page.  

I return to the plugin on the WooCommerce page here https://hashtagdeals.co.uk/wp-admin/admin.php?page=wc-settings&tab=integration&section=facebookcommerce# and I am shown a message that reads as follows:

Your API key is no longer valid. Please click "Settings > Advanced Options > Update Token". 

I goto settings as instructed and see the following message:

Your access token, which is used to keep your products synced with Facebook, needs to be updated.  

I then press the update token button and am then show the following message:

Your access token has been updated

I return to the Plugin at https://hashtagdeals.co.uk/wp-admin/admin.php?page=wc-settings&tab=integration&section=facebookcommerce# and am shown a message that says as follows:

Your API key has been updated.
Please refresh the page.

I do as instructed and refresh the page.  I am then shown the following message:

Your API key is no longer valid. Please click "Settings > Advanced Options > Update Token". 

I then enter a loop of repeating the above steps until I have no hair left !!!

I have been advised by the WooCommerce support team that you require the following:

Facebook Page: https://www.facebook.com/hashtagoffers/
Wordpress version: 5.1.1
PHP Version: 7.2.17
WooCommerce Version: 3.6.1
Facebook for WooCommerce Version: 1.9.10
Product count: 103
Product type: Trainers / Sneaker (nothing too complicated)
There are no duplicate SKU's in my system.

**A list of other plugins as follows:**

Akismet Anti-Spam Version: 4.1.1 (NOT ACTIVATED)

Contact Form 7 Version: 5.1.1 

Datafeedr API Version: 1.0.98 

Datafeedr Comparison Sets Version: 0.9.26

Datafeedr Product Sets Version: 1.2.34

Datafeedr WooCommerce Importer Version: 1.2.35

Facebook for WooCommerce Version 1.9.10

GDPR Cookie Consent Version: 1.7.6

Hello Dolly Version 1.7.1 (NOT ACTIVATED)

Jetpack by Wordpress.com Version 7.2.1

Limit Login Attempts Reloaded Version: 2.7.4

Woo Title Limit Version: 1.4.4

WooCommerce Version: 3.6.1

WooCommerce Menu Cart Version: 2.7.4

WooCommerce Services Version: 1.19.0

WooCommerce Square Version: 1.0.37

WooCommerce Stripe Gateway Version: 4.1.16 

WP Super Cache Version: 1.6.4

Yoast SEO Version: 11.0

Please advise further.

Regards

Chris

**Comment by CKGrafico** [comment] 2019-04-20 19:19
+1

**Comment by lolfert** [comment] 2019-04-20 19:55
Same issue here, it's driving me insane.

**Comment by Loretta11** [comment] 2019-04-20 23:00
me too.  I'm going crazy with this plugin.  I dont want my client to swap to shopify to take advantage of this shopping feature on instagram.  This is error message I get on two seperate integrations.  One with a small catalogue and one with a large. Your API key is no longer valid. Please click "Settings > Advanced Options > Update Token".

**Comment by Adam-Y5WF** [comment] 2019-04-21 09:14
I am having exactly the same issue. Grateful for any suggestions or support.

**Comment by Loretta11** [comment] 2019-04-21 09:38
how do we get help with this.  It would be good to be able to link a woocommerce shop catalogue but it just doesn't seem to want to

**Comment by jameskim0903** [comment] 2019-04-22 18:09
## Automated Support Message

Hello,

Thanks for your interest in our plugin! Our developer team tries to provide personal support on GitHub whenever possible.

If you have a feature request or feedback for the developers, reply with `Feature Request` or `Feedback`.
If you are a developer or have a question for the developers related to code, reply with `Developer Question`.
If you are running ads with us, reply with `Advertiser`.

If you have encountered a bug or a problem with the plugin, keep reading for information that can help you resolve the issue yourself or provide us details we need to help you.

## Search Existing Issues

First, please [search our issues](https://github.com/facebookincubator/facebook-for-woocommerce/issues?q=) to see if your problem has been reported before.
There may already be a workaround or a solution to your problem. You can use the [search bar](https://github.com/facebookincubator/facebook-for-woocommerce/issues?q=) near the top of our issues page. Be sure to search both _open_ and _closed_ issues.
If you do find a similar issue, leave a comment on that issue instead of creating a new one. Your comment helps us prioritize which existing issues are important and urgent.

## Common Resolution Methods

If you are experiencing a problem or bug and have not found any similar issue, please try the following:

* Upgrade to the latest version of the plugin
* Try to `Resync` products using the button on the plugin config page
* Reset the plugin by selecting `Manage Settings > Advanced Options > Delete` from the configuration page of the plugin and setting up again
* Try deactivating other plugins that you think may be interfering, then reset and set up again

## Necessary Information

If the above steps did not help, please provide the following information in your next comment in order for us to debug your problem:

* WooCommerce version
* WordPress version
* Plugin version (please note: we only support up-to-date versions of the plugin)
* A screenshot of where you see the problem (for example: if it is on Facebook, provide a screenshot of Facebook, if it is on WooCommerce, provide a screenshot of WooCommerce. You can provide multiple screenshots if the problem relates to different screens.)
* The URL of your website
* The URL of your Facebook Page
* The URL(s) of where you took your screenshot(s)
* If applicable, detailed steps you took in order to see the problem

Please include `Debug Ready` in your reply so our automated system can note your issue for manual review. Please be aware that due to a high volume of issues, we may not be able to respond immediately.

## Response Time

We prioritize issues with the tags `Advertiser` or `Multiple Reports`.
For issues that have the tags `Debug Ready`, `Feature Request` or `Developer Question`, we aim to respond within 30 days.

If you have not responded to our automated message with one of the above phrases, such as `Debug Ready`, we may close your issue after 30 days. If a `Feature Request` is inactive (without new requests, messages or pull requests) for 6 months, we may close it.

Please note that we are not always able to provide support for issues related to interaction from other plugins with this plugin or related to the Facebook advertising interface. To get support related to Facebook ads, try visiting the [Facebook Ads Help Center](https://www.facebook.com/business/help).

For more information on our response times, visit [Facebook Support on GitHub](https://github.com/facebookincubator/facebook-for-woocommerce/wiki/Facebook-Support-on-GitHub).

Thank you,
The Facebook Dev Team

**Comment by Hashtag1975** [comment] 2019-04-22 19:01
Multiple Reports

Debug Ready

Hi,

I have installed the Facebook for WooCommerce plugin however, it is not working as expected.

I have just 103 products that need to be synced with Facebook and Instagram but I can't get this to work. I am therefore unable to display my products and take advantage of all that Instagram shopping has to offer.

Steps taken to install the Facebook for WooCommerce plugin as follows:

Navigate to https://hashtagdeals.co.uk/wp-admin/plugins.php and locate the plugin.

Click on the settings link and navigate to the Facebook for WooCommerce Business Settings PopUp box.

Work my way through the setup procedure (Facebook Page, Facebook Pixel, Your Products, and Ad Setup). Some of the information seems to populate automatically as I am logged into my Facebook account on another browser tab. The 103 products are also displayed in the background of the Your Products page.

I return to the plugin on the WooCommerce page here https://hashtagdeals.co.uk/wp-admin/admin.php?page=wc-settings&tab=integration&section=facebookcommerce# and I am shown a message that reads as follows:

Your API key is no longer valid. Please click "Settings > Advanced Options > Update Token".

I goto settings as instructed and see the following message:

Your access token, which is used to keep your products synced with Facebook, needs to be updated.

I then press the update token button and am then show the following message:

Your access token has been updated

I return to the Plugin at https://hashtagdeals.co.uk/wp-admin/admin.php?page=wc-settings&tab=integration&section=facebookcommerce# and am shown a message that says as follows:

Your API key has been updated.
Please refresh the page.

I do as instructed and refresh the page. I am then shown the following message:

Your API key is no longer valid. Please click "Settings > Advanced Options > Update Token".

I then enter a loop of repeating the above steps until I have no hair left !!!

I have been advised by the WooCommerce support team that you require the following:

Facebook Page: https://www.facebook.com/hashtagoffers/
Wordpress version: 5.1.1
PHP Version: 7.2.17
WooCommerce Version: 3.6.1
Facebook for WooCommerce Version: 1.9.10
Product count: 103
Product type: Trainers / Sneaker (nothing too complicated)
There are no duplicate SKU's in my system.

A list of other plugins as follows:

Akismet Anti-Spam Version: 4.1.1 (NOT ACTIVATED)

Contact Form 7 Version: 5.1.1

Datafeedr API Version: 1.0.98

Datafeedr Comparison Sets Version: 0.9.26

Datafeedr Product Sets Version: 1.2.34

Datafeedr WooCommerce Importer Version: 1.2.35

Facebook for WooCommerce Version 1.9.10

GDPR Cookie Consent Version: 1.7.6

Hello Dolly Version 1.7.1 (NOT ACTIVATED)

Jetpack by Wordpress.com Version 7.2.1

Limit Login Attempts Reloaded Version: 2.7.4

Woo Title Limit Version: 1.4.4

WooCommerce Version: 3.6.1

WooCommerce Menu Cart Version: 2.7.4

WooCommerce Services Version: 1.19.0

WooCommerce Square Version: 1.0.37

WooCommerce Stripe Gateway Version: 4.1.16

WP Super Cache Version: 1.6.4

Yoast SEO Version: 11.0

Please advise further.

Regards

Chris

**Comment by Hashtag1975** [comment] 2019-04-23 08:20
Hi Guys,

I reached out to WooCommerce regarding this issue and this is what they have said:

Hey Chris!

We do not have access to be able to troubleshoot the issue, however, I have sent up a flare with the partnerships team asking if there's anyone we can contact to get more eyes on it from Facebook.

Have a good one!
Jesse - WooCommerce Support

**Comment by marito158** [comment] 2019-04-24 13:26
Same issue

**Comment by kayladavidson** [comment] 2019-04-24 15:36
This is a repeated issue, nobody is answering the questions.... I cannot get my store to go live with products, though the pixel is tracking activity. I've been trying for 6 days now.

https://business.facebook.com/MCBDshopusa
Wordpress 5.1.1
Woocommerce 3.6.1
15 Products
Simple physical products
No duplicate skus
No custom plugins to my knowledge

**Comment by Hashtag1975** [comment] 2019-04-24 16:11
So many people experiencing the same issue and zero support from Facebook at this time.

**Comment by kayladavidson** [comment] 2019-04-24 16:14
> So many people experiencing the same issue and zero support from Facebook at this time.

I opened a facebook support ticket here, I think if we dump hell on them maybe they will do something:

https://www.facebook.com/business/help/?mail_sent

**Comment by Hashtag1975** [comment] 2019-04-24 16:16
The WooCommerce developers seem to have a way of speaking to the Facebook development team so it might be worth dropping them an email at this address help@automattic.com

Good luck !!

Chris

**Comment by kayladavidson** [comment] 2019-04-24 16:28
> The WooCommerce developers seem to have a way of speaking to the Facebook development team so it might be worth dropping them an email at this address [help@automattic.com](mailto:help@automattic.com)
> 
> Good luck !!
> 
> Chris

I contacted WooCOmmerce first and they told me to contact fb here or on fb support. FYI

**Comment by Hashtag1975** [comment] 2019-04-24 19:26
Hey all,

I just received this update from WooCommerce.

AJ (Automattic)
Apr 24, 18:14 UTC

Hi there Chris,

Our contact at Facebook told us yesterday that they were aware of this issue for other platforms, but did not know that it also was affecting WooCommerce. They told us that the development team at Facebook have started working on a fix last week.

I have reached out to our Partnerships team to let them know that this is still an ongoing issue with more users impacted.

Best,

AJ
Happiness Engineer @WooCommerce.com

**Comment by gregamer** [comment] 2019-04-25 07:03
Same issue here! Must say I'm very disappointed with FB to leave such issues in ignorance for so long. Though FB will be more self-initiative since they're making money out of it!
I hope it's fixed soon. In the meanwhile I just might look for another plugin.

**Comment by arzu-poolie** [comment] 2019-04-25 07:47
Hi everyone, I have the same issue - already tried some of the tricks online but nothing works for me. Is there going to be an update of the plugin? Did someone announce a date where the new update is going to be released? This bug concerns a lot of users as I've seen in many github threads. 

Does anybody have a solution yet or even a workaround until the issue is being fixed by FB?

**Comment by kayladavidson** [comment] 2019-04-25 11:47
Hi Everybody!

Good news - I received a reply from FB after submitting a support request yesterday (withing 2 hours of my request I'M IMPRESSED). They requested a screencast replicating the repeating access token expiry, which I sent to them just now. 

You can contact them here: https://www.facebook.com/business/help/?mail_sent

More to come as I hear back from them. :)

**Comment by Hashtag1975** [comment] 2019-04-25 11:52
Nice one Kayla and thanks for the update.

Have a great day !

Chris

**Comment by gregamer** [comment] 2019-04-25 12:41
That's really good news for all of us! Thanks!

V V čet., 25. apr. 2019 ob 13:53 je oseba Hashtag1975 <
notifications@github.com> napisala:

**Comment by terrorfall** [comment] 2019-04-25 21:16
Same issue here

**Comment by yinghec** [comment] 2019-04-26 00:29
Hey Folks, this is a known issue to Facebook, and our team is working to fix this. 

Thanks

**Comment by Hashtag1975** [comment] 2019-04-26 00:56
Hey Yinghec,

Are you part of the Facebook team ?  If so, can you confirm when we can expect a fix for this ?  

Regards

Chris

**Comment by kayladavidson** [comment] 2019-04-26 12:38
I received a confirmation via email that they are reviewing my screencast recording...

**Comment by Hashtag1975** [comment] 2019-04-26 12:50
Thank you for the update Kayla.

Regards

Chris

**Comment by Hashtag1975** [comment] 2019-04-26 12:56
Hey guys,

Following the update from KaylaDavidson above, I thought I would attempt the token renew process again and to my absolute amazement, IT WORKS !!!

I'd be interested to know if it works for anybody else.  I didn't have to update the plugin or anything which suggests the issue must have been with Facebook as opposed to the actual plugin.

Regards

Chris

**Comment by Aprilhead** [comment] 2019-04-26 13:01
API error dissapeared for me too. Dont know how the product syncing will go though.

**Comment by kayladavidson** [comment] 2019-04-26 13:04
> Hey guys,
> 
> Following the update from KaylaDavidson above, I thought I would attempt the token renew process again and to my absolute amazement, IT WORKS !!!
> 
> I'd be interested to know if it works for anybody else. I didn't have to update the plugin or anything which suggests the issue must have been with Facebook as opposed to the actual plugin.
> 
> Regards
> 
> Chris

I just tested it and it worked for me as well!

**Comment by Hashtag1975** [comment] 2019-04-26 13:09
Products started to show up in Facebook almost as soon as I updated the token.  I didn't have to do anything else.  

Kayla - I think it was your email to Facebook that did the trick so thank you !!

**Comment by gregamer** [comment] 2019-04-26 13:09
Me too! I've been expecting this problem for sooo long, but it works now!
No more manual work here :)

V V pet., 26. apr. 2019 ob 15:04 je oseba kayladavidson <
notifications@github.com> napisala:

**Comment by kayladavidson** [comment] 2019-04-26 13:10
WOOTWOOT Now let's make some money!!!! 

> Products started to show up in Facebook almost as soon as I updated the token. I didn't have to do anything else.
> 
> Kayla - I think it was your email to Facebook that did the trick so thank you !!

**Comment by Adam-Y5WF** [comment] 2019-04-26 13:16
Yes, working for me too now! Yeay! Thank you everyone, great to finally have this resolved. 
    	
    	

    	
    
  




On Fri, Apr 26, 2019 at 4:10 PM +0300, "kayladavidson" <notifications@github.com> wrote:












WOOTWOOT Now let's make some money!!!!



Products started to show up in Facebook almost as soon as I updated the token. I didn't have to do anything else.


Kayla - I think it was your email to Facebook that did the trick so thank you !!

**Comment by jameskim0903** [comment] 2019-04-26 19:57
Merging with #944

**Closed by jameskim0903** 2019-04-26 19:57 UTC
Labels: Automated : Debug Ready, Automated : Multiple Reports

**Comment by ViolentCrumble** [comment] 2019-04-26 21:51
woot thanks guys! seems to be syncing.. syncing does seem to be taking ages though and i only have 11 products.. all the images showed up on facebook right away but not all the colours and sizes.. so far its been syncing for around 15mins... unsure if i need to keep this window open..

either way this is progress so thanks heaps!

**Comment by CKGrafico** [comment] 2019-04-27 19:07
working 🔥

**Comment by arzu-poolie** [comment] 2019-04-29 13:41
It works for me too, but I've noticed that the FB Shop now displays products which were created as drafts. This isn't the way it should be. For example I'm having 127 products online in the shop, FB shows 152 products (published and draft ones) in the FB shop tab. Is there anything I can do about this so it only shows the products which were published?

Thanks in advance!

**Comment by gregamer** [comment] 2019-04-29 14:07
For me it seems to work in the wp but there are no products displayed on
the fb shop although wp plugin says sync successful. Anyome else
experiencing the same problem?

**Comment by Loretta11** [comment] 2019-05-03 07:58
I have managed to upload the catalogue from woocommerce website to facebook and my products are showing up in the facebook shop.  My problem now is I've connected my facebook business account to the instagram business account but nothing is showing in the business menu.  On another site I tried there was a products link in the menu with catalogues showing from which you select one, then it said it had to be approved.  but on this one the catalogue is showing in the facebook shop but nothing showing up on Instagram business menu.  I've searched high and low to troubleshoot this and tried everything but nothing is changing. Does anyone know what is happening here.

**Comment by volmerf** [comment] 2019-06-28 14:48
I still have this issue. Anyone else knows how to fix this?

**Comment by volmerf** [comment] 2019-06-28 14:56
Seems it has to do with a ad-blocker doh!

**Comment by danielcharrua** [comment] 2019-07-29 07:08
Issue is still happening, every time I sell a product, the message appears: Your API key is no longer valid. Please click Settings > Advanced Options > Update Token

**Comment by dcgraphics1** [comment] 2019-08-02 16:00
This is never going to be fixed or resolved? 

Constantly having to update the token when I update a product.
**Your API key is no longer valid. Please click "Settings > Advanced Options > Update Token".
Your Access Token Has Expired
Your access token, which is used to keep your products synced with Facebook, needs to be updated.**

**Comment by tnchuntic** [comment] 2019-08-06 02:21
This is still not fixed access token will still expire. Hope they change it to 

> This is never going to be fixed or resolved?
> 
> Constantly having to update the token when I update a product.
> **Your API key is no longer valid. Please click "Settings > Advanced Options > Update Token". Your Access Token Has Expired Your access token, which is used to keep your products synced with Facebook, needs to be updated.**

I agree with you regarding this issue, I am not sure why it was close in the first place. This issue are still existing... user/admin needs to update/reauthorise again the pixel because it expires.

**Comment by DJSavill** [comment] 2019-09-03 14:22
Is this fixed yet??!!

Someone on here said in April Facebook were looking into it. It's now September.

Whenever I try and connect Facebook WooCommerce plugin to my page, it keeps giving me "suspicious activity" and making me change my Facebook Password.

Now, finally, it looks to be connected, but I'm getting the same token issue as everyone else. IT says go to Settings -> Advanced Settings, but there isn't any Advanced Settings in there. IT's just trying to take me through the process of connecting my page again, which doesn't even show up in the drop down menu this time.

Uninstalling / reinstalling the plugin doesn't work.

**Comment by jeffceriello** [comment] 2019-09-13 09:38
> Is this fixed yet??!!
> 
> Someone on here said in April Facebook were looking into it. It's now September.
> 
> Whenever I try and connect Facebook WooCommerce plugin to my page, it keeps giving me "suspicious activity" and making me change my Facebook Password.
> 
> Now, finally, it looks to be connected, but I'm getting the same token issue as everyone else. IT says go to Settings -> Advanced Settings, but there isn't any Advanced Settings in there. IT's just trying to take me through the process of connecting my page again, which doesn't even show up in the drop down menu this time.
> 
> Uninstalling / reinstalling the plugin doesn't work.

I'm having the same issue. It keeps giving me "suspicious activity" and making me change my Facebook password every 2-3 days.

Very annoying!!

**Comment by DJSavill** [comment] 2019-09-15 21:45
I don't really understand how Facebook, who is relying on businesses doing business on their platform and buying Ads, has released such a glitchy plugin for one of the worlds most popular eCommerce plugins on one of the worlds most used CMS.

I also can't understand why the hell they're not throwing everything they have at it to make sure it's fixed quickly when something goes wrong.
