### ISSUE TITLE
Facebook shows the wrong featured picture

### ISSUE THREAD

**Issue by BBarbadoSS** [facebookincubator/facebook-for-woocommerce#8] opened 2017-08-03 07:12 UTC
WooCommerce:
http://imgur.com/t0vI8tq

Facebook:
http://imgur.com/4msoxoO

Even when I try to reset the metadata.

**Comment by silksow** [comment] 2017-08-05 05:59
Confirmed, plugin does not honor WC default image for variable products. 

Steps to reproduce: 

1. Create variable product
2. Select main image and additional catalog images for variations
3. Include variation images in list drop down menus
4. Complete FB description box 
5. Update product 
6. WC displays product info and variation images
7. FB displays product info, description, image of last variation in list

**Comment by BBarbadoSS** [comment] 2017-08-07 12:51
Still the wrong picture...

**Comment by dmitridr** [comment] 2017-09-06 00:41
@silksow thanks for the detailed repro steps.

We fixed this in [v1.5.0](https://github.com/facebookincubator/facebook-for-woocommerce/releases/download/v1.5.0/facebook-for-woocommerce-v1.5.0.zip), the default image for variants should now be the WC default image for the variable product. Let us know if you still have this issue.

**Comment by silksow** [comment] 2017-09-08 00:19
This appears to be a poorly patched cosmetic fix in 1.5.1, creating more issues than it resolved. 

Steps to reproduce:

1. Update variable product with at least 4 variants in WooCom.
1a. Experience sympathetic pain for shops with hundreds or thousands of products to update.
2. Facebook displays WooCom default variant thumbnail, primary image, and price. 
3. Facebook displays <1.5.1 incorrect variant thumbnail and preselected options. 
4. In dropdown menu, select a variant other than WooCom default or <1.5.1 incorrect default.
5. Facebook dynamically adds selected variant thumbnail. Default variant thumbnail and primary image remain unchanged. 
6. Select variant thumbnail.
7. Facebook properly displays primary image for variant. 
8. In dropdown menu, select a variant other than WooCom default or <1.5.1 incorrect default. 
9. Faceboook dynamically replaces thumbnails with WooCom default variant and selected variant with default variant thumbnail selected and default variant primary image displayed. 

![fb for woocom 151 default product](https://user-images.githubusercontent.com/30702576/30189855-6a70dc30-93eb-11e7-9d8b-9e22e1e2fc82.jpg)

**Comment by dmitridr** [comment] 2017-09-08 07:35
Thanks for the message and detailed steps.
I went through the steps but, I'm not clear on what the specific problem(s) are here, so I'd like to ask you for some clarification.

- When you say '<1.5.1 incorrect X' does that mean this issue is fixed in 1.5.1 or broken in only 1.5.1?
- When I go through the repro steps, the selected thumbnail on the left resets to the first one. Is this the problem you refer to in step 9? I think we can fix this in one of two ways (1) by making the variant image the primary (first) image and the 'featured' image the secondary image or (2) by not changing the index of the selected image when switching variants.
- Is there any other problem than the one you mention in step 9?

**Comment by silksow** [comment] 2017-09-08 08:33
This issue was opened because versions of the plugin less than, or previous to, 1.5.1 seemed to use the last variation in the list of variations of a WooCom variable product as the default variation in FB. This is incorrect, as WooCom allows for explicitly declaring a default variation - as does the FB API, which is apparently being hacked around. 

You may find the problems more apparent in the iPhone app:

1. View the same variable product.
2. Select a variation. 
3. FB adds the additional image, which must be swiped into view. 
4. Tap image. 
5. Default variation is displayed.

**Comment by dmitridr** [comment] 2017-09-08 20:02
The lack of a default variation seems like a separate issue, given that this original issue was about the wrong image being shown in from what I can tell is an ad (Primary Image vs Color Variant Image).

Could you create a separate issue for this if we are not using the default correctly? As far as I am aware we did not explicitly fix this in 1.5.1 to do anything with the 'default' variant. 

In 1.5.1 are using the image from the parent variable product. If a variant is missing a field, we default to the field used by the parent.

What you describe in the iPhone seems to be an iPhone app bug, since this behavior isn't present in the desktop version as far as I can tell. This does not seem to be a bug specific to our plugin either, but a general problem with the shops app. Feel free to file an issue for this as well, and we can forward it to the appropriate team.

**Closed by dmitridr** 2017-09-08 20:02 UTC

**Comment by silksow** [comment] 2017-09-08 20:13
To help clarify, here's how it seems to me variable products should operate: 

1. The WooCom default variation should be displayed as the FB default selected menu item(s), thumbnail, and primary image (and enlarged image on tap in mobile), and all other unique thumbnails should be included rather than dynamically added when selecting from the menu. 
2. Selecting a thumbnail or swiping in mobile should change the menu selection and vice versa (selecting a variation from the menu should highlight the corresponding thumbnail or, in mobile, scroll to the corresponding image).
