### ISSUE TITLE
Visual Composer Shortcode in product description

### ISSUE THREAD

**Issue by pixolab** [facebookincubator/facebook-for-woocommerce#493] opened 2018-05-19 08:35 UTC
Hi, is there a solution to remove/strip the Visual Composer shortcodes from the product descriptions in order to have clear descriptions?

Exemple of shortcodes to strip: [vc_row][vc_column width="5/6"][vc_column_text] 

Thanks!

Plugin: 1.8.7
WC: 3.3.5
WP: 4.9.6
PHP: 7.0.0

![2018-05-20_09-13-28](https://user-images.githubusercontent.com/14137754/40276585-395e1e5a-5c0e-11e8-8b7a-99762874c414.png)

**Comment by joe6ar** [comment] 2018-05-20 23:13
Same problem, needs fixing, seems impossible to edit the description in facebook

**Comment by mengyingdu** [comment] 2018-05-21 00:03
[Note : This is an Automated Message]

Hello,

Thanks for your interest in our plugin!
Due to a high volume of issues we may not be able to get to yours immediately.

If this is a feature request, or feedback, please reply with
`Feature Request` or `Feedback` and it will be categorized accordingly, and
we will read it and reply when we can.

If you are experiencing problems, read on.

First. Please check to see if your issue is not a duplicate of another one.
To search our issues, use the search feature at the top of the GitHub issues page.
We have nearly 500 existing and past issues, so it is fairly likely someone else has already reported your problem.
If you do find a relevant issue, please comment in that issue, and close this one.
It helps us prioritize issues to tackle by looking at the number of people with the same problem.

If your issue is unique, and you are sure, then read on.
We require the following information in order to help you:
- WooCommerce Version
- Wordpress Version
- Plugin Version. Please Note that we do not support outdated versions of the plugin.
- A Screenshot of where you see the problem. If it is on Facebook, a screenshot of Facebook,
if it is on WooCommerce, a screenshot of WooCommerce. If it is in multiple places, multiple screenshots.
- The URL of your website.
- The URL of your page.
- The URL(s) where you took your screenshot(s).
- (If applicable) Detailed steps you took in order to see the problem.

Please be advised, it may take us some time to get to your issue.
In the meantime, below are generic approaches you can take that may solve the issue :
- Upgrade to the latest version.
- Force Resync
- Reset the plugin using `Reconfigure > Advanced Options > Delete` and setup again.
- Try to deactivate other plugins which you think could be interfering and repeating the above.

When you have the above data for us, please include
`Debug Ready` in your reply. We will get to it and debug it as soon as we can.

Thanks for your patience,
Dev Team (@dmitridr, @mengyingdu, @sammul, @jieminz22)

**Comment by pixolab** [comment] 2018-05-21 09:06
Plugin: 1.8.7
WC: 3.3.5
WP: 4.9.6
PHP: 7.0.0
Website: https://www.themessage.it/
FB page: https://www.facebook.com/themessageit/?ref=bookmarks
Screenshot URL: https://www.facebook.com/commerce/products/1549279941849838/

**Comment by jcastro91** [comment] 2018-05-23 23:13
Hello,

I noticed that on fbutils.php line 92 is this function:

 public static function clean_string($string) {
      $string = str_replace(array('&amp%3B', '&amp;'), '&', $string);
      $string = str_replace(array("\r", "\n", "&nbsp;", "\t"), ' ', $string);
      // Strip shortcodes via regex but keep inner content
      $string = preg_replace("~(?:\[/?)[^/\]]+/?\]~s", '', $string);
      $string = wp_strip_all_tags($string, true); // true == remove line breaks
      return trim($string);
    }
But FB shop is still rendering the shortcodes: http://prntscr.com/jlruaj

Best, Jorge

**Comment by pixolab** [comment] 2018-05-24 12:48
Hi, in the function fbutils.php **before** `return trim($string);` line, i added the following code to solve problem:

`$shotcodes_tags = array( 'vc_row', 'vc_column', 'vc_column', 'vc_column_text', 'vc_message' );
	$string = preg_replace( '/\[(\/?(' . implode( '|', $shotcodes_tags ) . ').*?(?=\]))\]/', '', $string );`

Best, Gaspare!

**Comment by mengyingdu** [comment] 2018-06-28 21:07
Hi @pixolab ,

This is great! Would you like send us a pull request? It will help others in the community with this problem, and we will support and review your pull request!

The Engineering Team.

**Comment by mengyingdu** [comment] 2018-08-17 22:04
## Automated Support Message - Issue Closed

Hello,

Because it has been 30 days since this issue was updated and you have not included `Debug Ready` in your reply, our automated system will now close your issue.
If you are still having this problem, please open a new issue and reference this one.

For more information on our response times and support policy, visit [Facebook Support on GitHub](https://github.com/facebookincubator/facebook-for-woocommerce/wiki/Facebook-Support-on-GitHub).

Thank you,
The Facebook Dev Team

**Closed by mengyingdu** 2018-08-17 22:04 UTC
Labels: Automated : Multiple Reports, Automated : Need More Info

**Comment by mohamdio** [comment] 2019-01-05 09:16
For this exact problem, I developed this free plugin named ( Shortcode Cleaner Lite ). 
https://wordpress.org/plugins/shortcode-cleaner-lite/

It will Clean your WordPress content from any unused broken shortcodes, which it clean up unused, broken shortcodes from WordPress content automatically, so you can switch between themes and plugins without worrying and keep your content cleanly and fresh all the time, it is dealing with any theme (Divi, Avada..etc) shortcodes that are left when changing themes or plugins or page builders (Visual Composer, Divi…etc).

I hope it will be useful.

**Comment by robwent** [comment] 2019-08-06 10:44
Couldn't this be done with the WordPress function strip_shortcodes()?

https://codex.wordpress.org/Function_Reference/strip_shortcodes

I think that's what's used to generate excerpts.
