### ISSUE TITLE
Get Started Button Opens www.facebook.com : Conflict with 'Remove HTTP' extension.

### ISSUE THREAD

**Issue by ShopVeraVeraCollection** [facebookincubator/facebook-for-woocommerce#74] opened 2017-10-10 09:47 UTC
Hi!
I have a problem with the Facebook for WooCommerce instalation. When I click get started, my facebook page opens...but there is no GET SET UP ADVERTS ON FACEBOOK...there is no option WELCOME/FACEBOOK PAGE/FACEBOOK PIXEL/YOUR PRODUCTS...just my facebook page...how can I fix that? what could be the problem?﻿

However, there is reminder on my dashboard...Facebook for WooCommerce is almost ready. To complete your configuration, complete the setup steps...and every time I click on COMPLETE THE SET UP STEPS...just my page opens and there is no set up to complete...please help me﻿!!!

https://www.facebook.com/ShopVeraVeraCollection/
WooCommerce version number Version 3.1.2 
WordPress version number latest version
I'm going to upload 167 variable products and more later.

Warmest Regards,

**Comment by dmitridr** [comment] 2017-10-10 23:50
Hello,

We had a similar problem in older versions. Could you confirm you are using version 1.6.x or above?
We also had a user reporting a similar issue when trying to set up on Mobile, could you confirm you are using desktop for the setup process?

**Comment by dmitridr** [comment] 2017-10-10 23:50
Also, a screenshot of what you are seeing after hitting the setup button would be helpful!

**Comment by ShopVeraVeraCollection** [comment] 2017-10-11 00:28
Hi!
WordPress version number 4.8.2
Set up on desk top

**Comment by dmitridr** [comment] 2017-10-11 00:29
Sorry, I mean the plugin version.

**Comment by ShopVeraVeraCollection** [comment] 2017-10-11 00:31
![20171011_110640](https://user-images.githubusercontent.com/32669764/31416805-4e999c08-ae77-11e7-8222-3b1c3b104a18.jpg)

**Comment by ShopVeraVeraCollection** [comment] 2017-10-11 00:32
![20171011_111904](https://user-images.githubusercontent.com/32669764/31416867-c1cc3898-ae77-11e7-8e04-007ecde595b6.jpg)

**Comment by ShopVeraVeraCollection** [comment] 2017-10-11 00:33
![20171011_111919](https://user-images.githubusercontent.com/32669764/31416893-e0aec0dc-ae77-11e7-893f-b7f690dc5747.jpg)

**Comment by ShopVeraVeraCollection** [comment] 2017-10-11 00:34
2nd picture - I press get started
3rd picture - what's what appears when I click get started

**Comment by ShopVeraVeraCollection** [comment] 2017-10-11 00:34
oops let me have a look

**Comment by ShopVeraVeraCollection** [comment] 2017-10-11 00:36
Facebook for WooCommerce - Version 1.6.1

**Comment by dmitridr** [comment] 2017-10-11 20:35
Hello,

This is very puzzling, but I have some things you can try.

- Can you try using a different browser? (I see you are using Chrome, so Firefox?)
- I see you are logged in as a page in FB, can you log in as a user then try it?
- Can you disable any adblockers you may have and try again? In particular disabling the adblocker on the url `www.facebook.com`.

I have some more ideas, but for now could you try those? If none of those help we'll have to try more advanced stuff.

**Comment by ShopVeraVeraCollection** [comment] 2017-10-13 08:27
Hi!
I tried Internet explorer and when I click get started nothing opens at all in this case.
I logged in as a user
What do you mean adblockers? I had W3 total cache and WP fastest cache plugins...but deactivated them for now.
I also had a problem with SSL...because 1st I didn't include it...added it a bit latter...could it be the reason for fb for woocommerce installation now?

Kind regards,

**Comment by ShopVeraVeraCollection** [comment] 2017-10-13 08:36
One more thing! I'm using Divi builder. There shouldn't be any conflict right?

**Comment by dmitridr** [comment] 2017-10-13 21:22
Hi,

By adblockers I mean any extensions you may have in the browser (Chrome) that could be blocking ads.
Those wordpress extensions you mentioned sound like they are not the cause, but you can try to test that ... one quick way to do that is to deactivate *all* extensions (except ours and WooCommerce), temporarily, then try the setup, if it still doesn't work, they are probably not the cause.

If that still does not work, I have some more suggestions, and if these do not work then we may have to ask for access to your site in order to debug.

Here's what you can try:
- Can you open the javascript console before clicking 'Get Started'? (Ctrl + Shift + J in Chrome) Then click Get Started and tell us if there is some error.
- Can you check the PHP logs for your webserver during the time that you hit 'Get Started' to see if there is some error related to the extension? If there is (it should mention `facebook`) can you paste it here?

**Comment by ShopVeraVeraCollection** [comment] 2017-10-15 04:20
Hi!
Checked in extensions on google chrome...don't have any ad blockers.

**Comment by ShopVeraVeraCollection** [comment] 2017-10-15 04:29
What do you mean BEFORE CLICKING GET STARTED in javascript console? confused where get started to click?

**Comment by ShopVeraVeraCollection** [comment] 2017-10-15 04:32
![20171015_152734 1](https://user-images.githubusercontent.com/32669764/31581744-dbaed4f2-b1bd-11e7-96a9-21480670dbba.jpg)

**Comment by ShopVeraVeraCollection** [comment] 2017-10-16 01:22
![20171016_121236 1](https://user-images.githubusercontent.com/32669764/31591560-8910ecbc-b26c-11e7-9152-3b2ae58db571.jpg)

**Comment by ShopVeraVeraCollection** [comment] 2017-10-16 01:23
Pic above, when I open  javascript console

**Comment by ShopVeraVeraCollection** [comment] 2017-10-16 01:24
![20171016_121442 1](https://user-images.githubusercontent.com/32669764/31591589-d30416f0-b26c-11e7-8004-5bfe06182ba2.jpg)

**Comment by ShopVeraVeraCollection** [comment] 2017-10-16 01:25
then I go to get started...nothing changes...again my facebook opens...then I opened javascript console again...pic above

**Comment by ShopVeraVeraCollection** [comment] 2017-10-17 00:00
waiting for your answer!

**Comment by dmitridr** [comment] 2017-10-17 00:43
Hi again, 

Yeah this is very strange, Unfortunately I have no idea what could be causing this without more detailed info. Would you be comfortable emailing us credentials to log in to your site and to try it out ourselves?

We can be reached at ads_extension_woocommerce@fb.com.

If you are not comfortable with this, could you email us the result of right clicking and hitting 'view source' on the main page? That may provide some insight to us as well, but it's a long shot.

**Comment by ShopVeraVeraCollection** [comment] 2017-10-17 05:54
Hi!
It's ok...Just sent it to you .
Please check your email: FACEBOOK FOR WOOCOMMERCE_VeraVera Collection.

Warmest Regards,

**Comment by dmitridr** [comment] 2017-10-17 21:21
Hi!

Great! Thank you, I got your email and was able to identify the issue.
The problem is that 'http' and 'https' is removed from the popup URL, which results in the popup opening to facebook.com instead. This is (likely) caused by your "Remove HTTP" extension.

Here's my suggested solution:
- Deactivate "Remove HTTP". Click Get Started. Finish Setup. Reactivate "Remove HTTP".
- When on the page with the `Get Started` button. Append the following string to the URL : `&url=https%3Ahttps%3A%2F%2Fwww.facebook.com` and hit enter. Then hit `Get Started`, I tested this and setup will work.

I recommend the first way, but either should work!

**Comment by ShopVeraVeraCollection** [comment] 2017-10-18 03:56
Hi!
Let me check it please.
I will come back to you.
Thank you.

Warmest Regards,

**Comment by ShopVeraVeraCollection** [comment] 2017-10-18 12:32
Hi! 
Thank you for your support!
I finished the set up as you said...get started opens now...but just 50 products uploaded, there should be 167 in total.
And when I was finishing the set up...it was said that all 167 products will be uploaded.

Also, I faced another issue, seems like after this, before, it was working well. When I'm trying to make an ad campaign or boost a post for example...it's just loading but nothing happens. I close the page, open again and it offers me to finish my promotion but nothing happens again. I cleared cache in my browser. Tried to do it from different browsers...everything is the same. I also tried to report a problem but SEND REPORT button doesn't work...oh my god!!! How can I contact them? 

That was my letter to them: URGENT PLEASE!!! I'm trying to create a campaign from adverts manager. However, when I click confirm button nothing happens...I close the page, open again and it offers me to finish my promotion but nothing happens again. 
The same happens when I'm trying to boost my posts...when I click boost...it's just submitting forever(can be an hour and I just close the page) and never submitted. What does it mean? I can't promote any product now. ads section doesn't work. How to fix that?
However, I get messages telling me do you want to promote your post? other posts?, etc.
I cleared cache in my browser. Tried to do it from different browsers...everything is the same.
was I blocked? However, don't see any notice about that! and I always get messages to finish my promotions and adverts.

What can you recommend?

**Comment by ShopVeraVeraCollection** [comment] 2017-10-18 12:33
![20171018_225730 1](https://user-images.githubusercontent.com/32669764/31718742-b50773d0-b45c-11e7-86ce-4c6989fa43ee.jpg)

**Comment by ShopVeraVeraCollection** [comment] 2017-10-18 12:34
![20171018_232605 1](https://user-images.githubusercontent.com/32669764/31718782-d2674bc6-b45c-11e7-8278-c1f784858270.jpg)

**Comment by ShopVeraVeraCollection** [comment] 2017-10-18 12:36
Don't have any idea what to do:(

**Comment by ShopVeraVeraCollection** [comment] 2017-10-19 02:45
Hi! 
I checked once again. Just 50 products uploaded, instead of 167.
What can you recommend?
Is there any limit on the quantity of products, while uploading?

**Comment by dmitridr** [comment] 2017-10-20 00:43
Hello,

Glad you got it working! There's no limit, but you do have to keep the settings window open during the upload and it may take some time to upload 167 products. I'd recommend going to the settings window and trying the 'Force Resync' button, then keeping the page open for some time (for 167 maybe 1 hour?) until the upload finishes.

**Comment by ShopVeraVeraCollection** [comment] 2017-10-21 07:14
Hi! 
But I Did that 3 days ago. Just 50 items uploaded.
What's the best way to upload all my items?
Should I deactivate plugin? then activate it again and try to upload all items again from the very beginning?
Also, if uploaded my item through facebook for woocommerce, can I delete for example an item there and add another? I mean can I make adjustments?

**Comment by ShopVeraVeraCollection** [comment] 2017-10-23 03:15
Please tell me how I can upload all my products from the very beginning...because just 50 uploaded

**Comment by dmitridr** [comment] 2017-10-31 21:38
Hi Again,

You can mark products as not visible on Facebook using the WooCommerce interface for editing products (the option should be available on the individual product edit page and on the all products page).

I'm not sure why only 50 products sync for you. I checked our backend logs for your store, and there's no completion event for the sync, so it seems the sync was not allowed to finish or there was some problem during the sync. 

Could you try the following:
1. Click 'Force Resync' and click OK.
2. Stay on the page and wait until the plugin settings page says the products are done syncing. (~1 hr?)
3. Check the shop, if there are still only 50 products, check your server PHP logs (as you did before) and look for 'facebook', if there are any exceptions or lines related to 'facebook' please send us those, or paste them here.

Also, make sure the HTTP plugin is disabled during sync, that could be interfering with the upload as well (by changing the urls).

**Comment by dmitridr** [comment] 2017-12-04 22:43
Closing this since the original problem was solved. Feel free to file another issue if the problem with the partial uploads is persisting!

**Closed by dmitridr** 2017-12-04 22:43 UTC
Labels: bug

**Comment by ShopVeraVeraCollection** [comment] 2018-02-21 02:52
Hi!


I'm coming back with my issue. Just 50 items out of 167 has been aploaded.

You said:

 Click 'Force Resync' and click OK


How I can do that?

Should I deactivate plugin and then activate it again?


Thank you


________________________________

VeraVera Collection
Title
Company

________________________________
