### ISSUE TITLE
My products not updating in facebook eshop

### ISSUE THREAD

**Issue by xbass540** [facebookincubator/facebook-for-woocommerce#216] opened 2018-01-15 10:41 UTC
hi,
i am using the plugin successfully until now and it shows all my products to Facebook eshop.
After creating new products, those are not updated in Facebook feed.
I clicked force resync button but no success.
thanks!

**Comment by tahoff** [comment] 2018-01-16 17:18
Thanks for reporting this issue. Can you provide some more information, specifically:
- Are you using the latest version of Facebook for WooCommerce, if not, can you upgrade?
- Do the products you've recently added have anything special about them (ex: were they created using another plugin)?
- Can you send the link to your website?
- Can you send a screenshot of a WooCommerce product on your shop that hasn't uploaded to Facebook?

**Comment by xbass540** [comment] 2018-01-17 11:02
- yes it is the latest version
- no they were normally created with woocommerce
- i cant share this info. Can i send you a pm?

**Comment by tahoff** [comment] 2018-01-17 15:10
@xbass540, you can email me at ads_extension_woocommerce@fb.com. In the email can you provide your website url, and any additional information about the products that aren't syncing successfully.

**Comment by xbass540** [comment] 2018-01-17 18:04
Hi,
The url is
De-sunglasses.com 

Our new woocommerce products are not reflecting to our Facebook eshop.
 
There is no pixel installed on the site , I don’t know if this is relevant.

I hope you get the email.

Kostas Mavrokefalos
Solomondesigns.co.uk
+44-(0)-7871274602
+31-(0)-686192466

**Comment by xbass540** [comment] 2018-01-17 23:32
hi,

this product should be in the facebook shop but is not there .

it is called texas red

![texas](https://user-images.githubusercontent.com/6285342/35072968-1a98f7ec-fbe7-11e7-8665-dd7496203f5a.png)

**Comment by xbass540** [comment] 2018-01-17 23:33
the email you sent me gives me mail delivery error so i have to answer here. 
Thanks anyway!

**Comment by tahoff** [comment] 2018-01-18 00:02
This was resolved by deleting the existing settings and re-completing the setup flow. The cause was old product data that was still associated with the products.

**Closed by tahoff** 2018-01-18 00:02 UTC
Labels: question

**Comment by DehautDesign** [comment] 2019-02-19 19:04
Hi, I have the same problem, My products were created inside the woocommerce platform. I did the sync, but nothing happened. Wich ''SETTINGS'' are you talking about here? Facebook or Woocommerce?
