### ISSUE TITLE
Conflict with A2 Optimized Plugin

### ISSUE THREAD

**Issue by digirev** [facebookincubator/facebook-for-woocommerce#57] opened 2017-09-27 01:13 UTC
Hi, after I install the plugin, I can see duplicated event in Pixel Helper. 1 of them shows me an error.

I tried with the plugin by PixelYourSite, it works well. Seems like there's something wrong with the plugin.

How can I fix or troubleshoot this further? Definitely not the cache since I cleared it already.

Thanks.

**Comment by dmitridr** [comment] 2017-09-28 01:00
Hello.

We don't seem to be able to reproduce this on our end.

- Could you tell us which version of the plugin you have?
- Could you share a screenshot or link to a site with the problem?

**Comment by digirev** [comment] 2017-09-28 01:41
It's version 1.6.1.
You can check it here: https://gizmosified.com/
It's still in a development phase. I turn it on for you to take a look for that Facebook Pixel Plugin issue. Please let me know if you have taken a look. I need to change it back to maintenance mode again.
Thanks.

**Comment by dmitridr** [comment] 2017-09-28 01:56
I took a look. Seems like a bug with the helper tool because the pixel fires once, correctly, the other duplicate fire is some kind of mis-parsing of your source by the pixel helper tool, interesting that PixelYourSite doesn't have this problem though.

If you [email us](ads_extension_woocommerce@fb.com) the source of your main page with PixelYourSite installed, perhaps we can figure out and fix the bug by looking at the difference. But I would not worry too much in the meantime, since this appears to be a problem with the pixel helper tool in some cases, and not the pixel itself.

**Comment by digirev** [comment] 2017-09-28 02:30
Hi, is this the best email ads_extension_woocommerce@fb.com ? I think couple days ago I sent an email there, but there's an automated email that I need to check to Facebook resource page which is not telling anything. I can send you the page source if you want so that you can apply the fix. Yeah that PixelYourSite plugin, instead of creating 2 Page Views, it creates 2 different event: PageView & (something else that I forgot).

Anyway, if you're 100% sure that it's only the bug in Pixel Helper, then I am going to use the plugin. Thanks.

**Comment by digirev** [comment] 2017-09-28 03:36
The 2 events that was created by PixelYourSite plugin is PageView & GeneralEvent, while your plugin created 2 PageView events (that's what it's shown on Pixel Helper).

I sent you the email as requested. Please check. Thanks.

**Comment by dmitridr** [comment] 2017-10-13 23:12
Hello,

We had to prioritize other issues above this one, but I finally had some time to take a look. Thank you for sending us your source, but unfortunately it seems that pixel your site uses a completely different approach that we won't be able to emulate.

On the other hand, I took a look at your site again, and it seems everything is fine according to the helper tool. Did you find a workaround? I'd be interested to hear what it was.

**Comment by digirev** [comment] 2017-10-14 01:53
Hi Dimitri,

 

Thanks for getting back to me.

 

It’s most likely a conflict with A2 Optimised Plugin. That plugin has several features. Please see this:  <https://wordpress.org/plugins/a2-optimized-wp/> https://wordpress.org/plugins/a2-optimized-wp/

 

I am not sure which feature that cause the issue. I think when I disable it, it’s working fine afterwards. I am now only using W3 Total Cache.

 

Best regards,

 





Ruben Noichi


e:

 <mailto:ruben@digitalrevival.com.au> ruben@digitalrevival.com.au


p:

 <tel:0426447070> 0426 44 7070


w:

 <http://www.digitalrevival.com.au> www.digitalrevival.com.au


 <https://www.google.com/partners/?authuser=1&hl=en-US#a_profile;idtf=1977788120;> 

  _____  

This email and any attachments may contain privileged or confidential information or both. You should not read, copy, use or disclose them without authorisation. If you are not an intended recipient, please contact me at once by return email and then delete both messages.  I do not accept liability in connection with computer virus, delay, interruption, unauthorised access or unauthorised amendment. It is your responsibility to check any attachments for viruses and defects before opening them or sending them on. This notice should not be removed.

  _____

**Comment by dmitridr** [comment] 2017-11-08 18:38
Hey Again,

Just a heads up : You may want to try v1.6.6. @citymont added a fix which could have solved the conflict with the A2 optimized plugin.

**Comment by dmitridr** [comment] 2018-01-09 00:56
Closing this as this was fixed by a pull request, please open a new issue and reference this one if the problem persists.

**Closed by dmitridr** 2018-01-09 00:56 UTC
Labels: feature-request, help wanted
