### ISSUE TITLE
Crop/resize product image size on facebook shop

### ISSUE THREAD

**Issue by sean3650** [facebookincubator/facebook-for-woocommerce#140] opened 2017-11-04 02:27 UTC
hi  
is there a fix to resizing the product image?
https://www.facebook.com/lensgogo/
this is my facebook page, if you go to shop the image is  not shown the right way

**Comment by tahoff** [comment] 2017-11-06 22:43
It looks like this issue has been encountered with the Shopify integration as well. At the moment, there isn't a way to change the cropping in the Facebook shop, although you can change the way the images appear in ads if you go to https://www.facebook.com/products/catalogs/ and go to the settings tab of your catalog.

**Comment by whatevs-already** [comment] 2017-11-06 23:37
The link you shared is broken or has been removed: https://www.facebook.com/products/catalogs/

I'm also having an issue with product image sizes, slightly different. The product images on an iPad are absolutely huge. They are resized on desktop, huge on iPad, and the shop won't even load on iPhone 7. It's an older iPad on iOS 10.3.3 but successfully running the latest version of Facebook app. Screenshot: https://snag.gy/0hFndM.jpg -- that's actually a square image of a pillow, but this is what it shows in the shop, for every pillow... about 1/4 of it.

**Comment by tahoff** [comment] 2017-11-07 23:31
The link must have changed, it's now: https://www.facebook.com/products/.

**Comment by dmitridr** [comment] 2018-03-21 00:01
I'm following up on older issues. This appears mostly to be a duplicate of #48 which covers the cropping of non-square images. Please open a new issue on us if there's a specific problem that's separate from the cropping!

**Closed by dmitridr** 2018-03-21 00:01 UTC
Labels: shops-feature
