### ISSUE TITLE
2Factor Authentication Business Setting Causes Absolute Failure in Plugin

### ISSUE THREAD

**Issue by hamutalwz** [facebookincubator/facebook-for-woocommerce#449] opened 2018-04-30 22:07 UTC
One of my products is not being synced properly.
It was fine before I tried to update the product in Wordpress while using version 1.8.6 of the Facebook for Woocommerce plugin that is broken.
Every time I tried to post the update I got an error even though the changes were actually saved.
Since then, the ITEM GROUP ID field of this product, in Facebook catalog, is not populated anymore with the post_id and the product is marked as Not Synced in Wordpress and is not shown in my Facebook page shop.
I tried to force Sync. The product information is synced yet the ITEM GROUP ID field is still not populated and the product is still marked as not synced.
How can I correct this?
Thank you.

**Comment by sammul** [comment] 2018-05-01 19:02
v1.8.6 is a known broken version. Please try out 1.8.5 https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.8.5 and let us know if it works

**Comment by hamutalwz** [comment] 2018-05-01 19:13
I did roll back to version 1.8.5 but it did not solve the sync problem, only the save problem.

**Comment by hamutalwz** [comment] 2018-05-03 09:27
While using v1.8.5 I updated another product and it synced the data changes I have made but again, lost the ITEM GROUP ID field of this product in the Facebook catalog and now this product also is not showing in my Facebook shop.
**This is a major issue! I keep loosing products in my Facebook shop due to this error.**
Please assist.
Thank you.

**Comment by dmitridr** [comment] 2018-05-07 21:41
Hello, 

could you please upgrade to 1.8.7? do you still have this issue after doing a `Force Resync` with the new version? Right around the time you last posted we had a major shop issue which affected lots of shops (not just WooCommerce).

**Comment by hamutalwz** [comment] 2018-05-07 22:26
I'm sorry but it is very frustrating to receive a response after 5 days asking me to do something I already wrote I did: "v.1.8.7 did not solve this problem" (see above).

**Comment by dmitridr** [comment] 2018-05-08 23:26
I missed that. Thanks for confirming it though.

- Could you send us the url of your shop? 
- If the shop upload is working for you. Could you send us a link to the product (in your original post) which has the problem?

**Comment by hamutalwz** [comment] 2018-05-09 04:26
I wish  could but I don't have a shop anymore. As I've written before: "I tried to delete the settings and re-configure the plugin but now it's not working at all. I keep getting the infamous error message: "Something wrong when uploading, please try again.". I keep trying over and over again but it's always the same. Now I have an empty catalog since the sync is not working, and I don't have a shop in Facebook."

**Comment by mengyingdu** [comment] 2018-05-10 20:17
Hi @hamutalwz ,

1. Can you send us your facebook page? I want to take a look in our logging to see what weird things happen on your site.
2. Your site url (www.your_actual_website.com) 

Thanks.

**Comment by hamutalwz** [comment] 2018-05-10 20:27
sure. here it is:
https://www.beingaprojectmanager.com/
and this is my Facebook page:
https://www.facebook.com/beingaprojectmanager/

**Comment by dmitridr** [comment] 2018-06-13 22:07
Hi,

Thanks for your patience, we are dealing with many issues right now.
I took a look in our logs, the situation is quite bizarre, let me list my observations:

- When you tried on v1.8.7 it seems as you say nothing worked at all we have no logs from you about your product upload, it is likely we introduced a bug in v1.8.7 that prevents you from using it.
- When you tried on v1.8.5 the upload seems to have worked at least once.

So there are two problems here:
(1) We introduced a bug in 1.8.7 that prevents you from uploading completely.
(2) The Group ID is erased after you upload.

I have some resolution suggestions and some additional info that would help us:
- Have you tried v1.7.11? This is the last stable version using the old method to sync products, it will be slow but it may work for you. If you have not yet tried it, I recommend downgrading while we try and fix the problem.
- For the Item Group ID, do you mean on Facebook or on WooCommerce? If I understand you correctly, you mean on WooCommerce. We have a mechanism to fetch the Item Group ID from Facebook which should happen if you load the `all products` page, but it seems that is not working for you. cc @mengyingdu.

**Comment by hamutalwz** [comment] 2018-06-14 07:55
It not working.
I've downgraded to v1.7.11 but the sync does not work.
I have deleted the settings and re-configured a few times, it seems to be syncing for just a quick second and then it says that the products are synced but when I go to the products page, their status is 'Not Synced' and there's an error message at the top of the page saying:
"We've detected that your Facebook Product Catalog is no longer valid. This may happen if it was deleted, or this may be a transient error. If this error persists please delete your settings via "Re-configure Facebook Settings > Advanced Settings > Delete Settings" and try setup again"

So I keep remaining in this endless loop.

As for the Group ID, I mean on Facebook. When you look at the products that are synced (if they are synced), there's a 'Group ID' fields which seems to be populated with the post ID from Wordpress, however, this field is suddenly erased and then the sync - if it worked before, does not work any more.

The problem I'm having now is that products are not synced at all.

**Comment by dmitridr** [comment] 2018-06-14 22:06
Thanks for trying that. Judging by our logs, it seems you have had at least one success with v1.8.5, so I would stick to that version.

Something is blocking your webserver from contacting Facebook via API calls. The last successful API call from your server into FB was back in April. Since then I have seen absolutely nothing in our logs.

This indicates to me that it could be a problem with the API call from your server.
The fact that you see the catalog error message also indicates to me that it's a problem with that.

(1) Do you have any method by which you can debug outbound calls on your server? 
If you don't could you install this plugin, https://wordpress.org/plugins/query-monitor/ then try a full reset and monitor the outbound queries immediately after clicking `Finish`? Specifically could you look for calls in the query monitor going to `facebook.com`?

Then there are two possibilities
[A] You don't see any calls to `facebook.com` at all. If you're sure the monitor is set up correctly, this means there's some kind of bug in our plugin (but it worked before...?), or your server is preventing the outbound request.
[B] You see calls to `facebook.com` but they are failing or they are being blocked or they are returning a negative result or some kind of error. Any error information you can give us would be helpful here. Screenshots would work.

Thanks for your patience as we try to get to the bottom of this.

**Comment by hamutalwz** [comment] 2018-06-15 11:40
Hi,
I tried re-configuring the plugin using v1.8.5 and it still did not work.
I have installed the debug plugin you suggested and here are some screenshots.
![1](https://user-images.githubusercontent.com/4686912/41466212-f497fe84-70a9-11e8-974e-4667c3197d39.png)
![2](https://user-images.githubusercontent.com/4686912/41466218-fbb09ce4-70a9-11e8-979a-e45c2b05220b.png)
![3](https://user-images.githubusercontent.com/4686912/41466223-fe422fea-70a9-11e8-9e30-243f01cfc8f2.png)
![4](https://user-images.githubusercontent.com/4686912/41466224-00ef1f50-70aa-11e8-8dca-6e8c4d60356f.png)

**Comment by dmitridr** [comment] 2018-06-19 00:58
Hey again,

Thanks for helping us debug this and sending over the screenshots!
It looks like from your first screenshot, *some* API calls to FB are actually working. But most of them are not there, this means that likely there is a conditional bug in the code somewhere, with your help we can hopefully determine where it is and fix it... unfortunately we cannot reproduce this bug ourselves (on our own sites) so we're completely relying on you for more information.

Could you check the Javascript browser console in the window where you took the first screenshot (Ctrl + Shift + J opens it) right before and during the process of hitting 'Finish' while product sync should be starting? 

(1) If it has an error that happens after clicking `Finish` that's probably the cause. Please screenshot it with the expanded information (as much info as possible).
(2) If it says `Syncing all Products!` and there is no error, this is very strange, we will build a special debug-version of the plugin for you to try, which will hopefully be able to pinpoint the cause of the error. 
(3) If it does not say `Syncing all Products!` and there is no error, then the cause is probably [these lines](https://github.com/facebookincubator/facebook-for-woocommerce/blob/master/assets/js/facebook-settings.js#L131-L136) which you can try removing in the WordPress plugin editor (make sure to clear browser cache afterward). We can issue a fix for this, if that's the cause.

Thanks for working with us on this! 
(also v1.9.0 [is out](https://github.com/facebookincubator/facebook-for-magento/releases), there's a small chance it will help so feel free to try it)

**Comment by hamutalwz** [comment] 2018-06-19 11:47
Hi,
Here are the screenshots. I'm not sure how much information there is.
![1](https://user-images.githubusercontent.com/4686912/41595496-a8f29c36-73cf-11e8-8e02-dd678cbde524.png)
![2](https://user-images.githubusercontent.com/4686912/41595498-ab762392-73cf-11e8-877e-1d333069c247.png)
I will try the latest version too.

**Comment by dmitridr** [comment] 2018-06-19 23:48
Thanks for trying that and sending more screenshots. Looks like it says `Syncing Products!` but there is no error. 

This is definitely the hardest case for us to figure out, my guess is there is an exception somewhere on your server. If you have access to the error logs from your server, I would encourage you to check them around the time when you click finish. If there is an entry relating to Facebook around this time, it could indicate the problem to us as well, please post it here if there is.

Here is a debug version of the plugin we've built to try and debug this, 
[facebook-for-woocommerce-v1.9.0-DEBUG.zip](https://github.com/facebookincubator/facebook-for-woocommerce/files/2117224/facebook-for-woocommerce-v1.9.0-DEBUG.zip)
could you please uninstall your current version, install this one, and run through the same process above? It will try to send debug information to FB at every step of the product sync, so we should be able to understand where the failure occurred. If it fails to send information to FB, it should create a notification in your admin panel that should be visible if you refresh the page.

If nothing happens with this debug version, chances are there is some issue with your server and AJAX requests. The most puzzling thing about this is, it was working for you back in April, and then the same exact version did not work for you now, so I suspect it's a bug relating to some specific configuration of your server... if you can think of anything that has changed regarding your server since that time, that may also be helpful.

Thanks for your patience as we work through this problem.

**Comment by hamutalwz** [comment] 2018-06-20 16:25
Hi,
Not sure what supposed to happen with this version. Here's the screenshot of the Javascript browser console:
![1](https://user-images.githubusercontent.com/4686912/41671379-9ae928f8-74bf-11e8-9ea5-1a35c8523bf9.png)

**Comment by dmitridr** [comment] 2018-06-20 18:32
Thanks for trying that, this is turning out to be a pretty baffling issue. 
 
Couple of questions:
(1) If you refresh the page do you see a notification from the extension?
(2) Do you see any error in your server logs? At this point your error logs may be our only hope.
(3) Does the query monitor I mentioned earlier show any new requests to Facebook?

Unfortunately, we still have no logging from you from the debug version... which means either the AJAX request is failing silently or the logging itself is broken, so our only hope to discover the problem is the php logs on your server itself. If you don't have server logs enabled, those can usually be enabled by setting WP_DEBUG_LOG and WP_DEBUG to `true` in `wp-config.php`. 
Here's a guide : https://codex.wordpress.org/Debugging_in_WordPress

Could you ensure logging is enabled, go through the flow once more, then send the resulting server log (or relevant snippet) to us, either by posting here or emailing us at ads_extension_woocommerce@fb.com ?

**Comment by hamutalwz** [comment] 2018-06-24 16:45
Hi,
It is not possible to use the plugin in debug mode. Once I change the settings in the wp-config.php file, I get an error message in the WordPress admin panel saying: "To use Facebook for WooCommerce, please disable WP_DEBUG_DISPLAY in your wp-config.php file. Contact your server administrator for more assistance."

**Comment by dmitridr** [comment] 2018-06-25 20:38
Hi,

The error message usually indicates there is some problem with the API call. If we get your log we can determine the cause of the problem. I will investigate if there is any log for this specific error you saw that we can look from our side.

To get your logging set up please try disabling `WP_DEBUG_DISPLAY` but enabling `WP_DEBUG` and `WP_DEBUG_LOG`. The extension should work in this case. Thanks for your persistence!

**Comment by dmitridr** [comment] 2018-06-25 21:33
One other thing to try : please try setting up with a new (non-business owned) page, instead of your existing one. There's a possibility this is related to the fact that your current page is business owned, and due to the permissions assigned by the business to who can manage your page, the extension is not able to access it to upload products and etc.

**Comment by hamutalwz** [comment] 2018-07-12 08:10
Hi,
I have contacted my hosting managers and they performed all the tests possible on the server side and they could not find anything wrong.
1. They have temporarily disabled the server's firewall;
2. They have temporarily disabled the MODSECURITY system.

I have enabled the debug mode and ran the process again and it fails and this is what I got:
[12-Jul-2018 07:58:19 UTC] Settings saved!
[12-Jul-2018 07:58:20 UTC] Got pixel-only settings, doing nothing
[12-Jul-2018 07:58:21 UTC] PHP Notice:  Undefined property: WC_Facebookcommerce_Integration::$test_mode in /home/fshcoil/sites/beingaprojectmanager.com/wp-content/plugins/facebook-for-woocommerce/facebook-commerce.php on line 1655
[12-Jul-2018 07:58:23 UTC] Not syncing, invalid product catalog!
[12-Jul-2018 07:58:23 UTC] PHP Notice:  Undefined property: WC_Facebookcommerce_Integration::$test_mode in /home/fshcoil/sites/beingaprojectmanager.com/wp-content/plugins/facebook-for-woocommerce/facebook-commerce.php on line 2254

Please help!
Thank you.

**Comment by dmitridr** [comment] 2018-07-12 21:09
Hi. 

Thanks for doing that, the logs are extremely helpful. The key line is this:
`[12-Jul-2018 07:58:23 UTC] Not syncing, invalid product catalog!`

The problem appears to be with business permissions on your page, which are causing business permission issues on your catalog. I agree there appears to be nothing wrong with your server.

There's three things to try:
(1) Please try disassociating the page from your business when completing setup. This should hopefully fix the problem. Afterwards, you can connect your page to your business again.
(2) After completing setup, you can view your catalog at `www.facebook.com/products`. When doing this, go to `Settings` and attach your catalog to your business. Then in your business make sure you have the highest possible permissions on this catalog. After doing so, try to reload the settings page of the plugin and doing a `Force Resync`
(3) Ensure that whichever FB user completed the Setup is an Admin of the page **and** has the admin role on the page assigned via the business. Due to the complexity of Business Manager, this may not be enough, and you may need to do (2) as well.

Hope that helps. We will fix the `PHP Notice` that appears in your logs though I don't think it's causing the problem.

**Comment by hamutalwz** [comment] 2018-07-12 21:20
Hi,
I don't know how disassociate the page from my business I can only seem to remove it however, I have a lot of assets related to this page, as well as ads.
I am the Admin and Owner of this page and I always was. Remember that the sync once worked so I don't feel confident to use this solution.

**Comment by hamutalwz** [comment] 2018-07-12 21:34
Every time I delete the plugin's settings the catalog is deleted too.
Every time I run the plugin's settings, a new catalog is created but the products are not synced to it.
I have tried to associate the empty catalog to my business but am unable to. When I try to assign the catalog as an asset the list is empty and there's a message: "No assets matched your search. Please try again".
The catalog simply does not show on the list.

**Comment by dmitridr** [comment] 2018-07-13 21:30
Hi,

I confirmed what you said, it seems your business is configured in such a way that you do not have permission to edit/modify your page via API. I'm not sure how this is possible, but we're looking into what we can do to solve this. This permission extends to your catalog as well, and also explains why we don't see any logs from you... 

The best way to solve this is to disconnect the page from the business (I doubt ads will be affected), but at this point I ask that you not do this and not reset the plugin, since both our team and the catalog team are debugging your current catalog. 

Will update when we have something, hope we can fix this for you.

**Comment by dmitridr** [comment] 2018-07-14 00:57
We pinpointed the problem. The problem is due to 2fac authentication enabled on your business account, if you disable this, it should address the problem, if not we should have a fix out by early next week.

**Comment by dmitridr** [comment] 2018-07-16 19:53
Glad we finally got this working for you! Our fix is live now so you should be able to enable 2Factor authentication tomorrow and the plugin should still work. 

Regarding your questions:
(1) Some products will be rejected depending on our policies. It looks like your products have a lot of text in the image, we used to have a rule/policy that would prohibit such products. There is also an appeals process you can use with the shops team (if it's not broken for you #318 is related). You're right in that we can't help you much with this.
(2) Give it a few days (up to a week) for events to show up. That interface is very slow to update. We have many complaints if you [search our open and closed issues](https://github.com/facebookincubator/facebook-for-woocommerce/issues?utf8=%E2%9C%93&q=is%3Aissue) using the search bar at the top about exactly the same problem, it eventually resolves itself in almost all cases.

**Comment by dmitridr** [comment] 2018-07-20 21:35
I'm closing this out since the core issue has been solved. Thanks for working with us on this! It's largely thanks to your help in debugging we fixed this critical failure for everyone who had 2Fac enabled in their business.

Feel free to open a new issue on us if you encounter other problems or have feedback or feature requests for us. Thanks again!

**Closed by dmitridr** 2018-07-20 21:35 UTC
Labels: bug
