### ISSUE TITLE
Facebook store images not showing

### ISSUE THREAD

**Issue by Blipsinspace** [facebookincubator/facebook-for-woocommerce#504] opened 2018-05-24 08:52 UTC
Hi,

Please I need some assistance. I have uploaded products using the woocommerce facebook plugin. Products were all uploaded successfully. It took a while to upload them to store though - I have up to 5k products. However, a couple of days after upload, several products were missing images. Please can you help with this issue. I am not a developer and not familiar with codes.

Thanks,

**Comment by mengyingdu** [comment] 2018-05-24 15:28
[Note : This is an Automated Message]

Hello,

Thanks for your interest in our plugin!
Due to a high volume of issues we may not be able to get to yours immediately.

If this is a feature request, or feedback, please reply with
`Feature Request` or `Feedback` and it will be categorized accordingly, and
we will read it and reply when we can.

If you are experiencing problems, read on.

First. Please check to see if your issue is not a duplicate of another one.
To search our issues, use the search feature at the top of the GitHub issues page.
We have nearly 500 existing and past issues, so it is fairly likely someone else has already reported your problem.
If you do find a relevant issue, please comment in that issue, and close this one.
It helps us prioritize issues to tackle by looking at the number of people with the same problem.

If your issue is unique, and you are sure, then read on.
We require the following information in order to help you:
- WooCommerce Version
- Wordpress Version
- Plugin Version. Please Note that we do not support outdated versions of the plugin.
- A Screenshot of where you see the problem. If it is on Facebook, a screenshot of Facebook,
if it is on WooCommerce, a screenshot of WooCommerce. If it is in multiple places, multiple screenshots.
- The URL of your website.
- The URL of your page.
- The URL(s) where you took your screenshot(s).
- (If applicable) Detailed steps you took in order to see the problem.

Please be advised, it may take us some time to get to your issue.
In the meantime, below are generic approaches you can take that may solve the issue :
- Upgrade to the latest version.
- Force Resync
- Reset the plugin using `Reconfigure > Advanced Options > Delete` and setup again.
- Try to deactivate other plugins which you think could be interfering and repeating the above.

When you have the above data for us, please include
`Debug Ready` in your reply. We will get to it and debug it as soon as we can.

Thanks for your patience,
Dev Team (@mengyingdu, @sammul, @jieminz22, @dmitridr)

**Comment by mengyingdu** [comment] 2018-05-25 16:00
similar to #463 
Can you check your image size?

**Comment by mengyingdu** [comment] 2018-06-28 21:15
Images' issue should be fixed in as #463, and there's no update for 1 month. Close it for now. 
If you still have this problem, feel free to open a new issue! @Blipsinspace

**Closed by mengyingdu** 2018-06-28 21:15 UTC
Labels: Automated : Need More Info

**Comment by angelo-msg** [comment] 2018-09-01 16:13
@mengyingdu I have kind of the same problem. I've synced my products (took a while to realize products with no price won't sync, you should really add this to the documentation), anyway, just 37 products. They all synced correctly but when I accessed the shop page on facebook no images were diplayed. Then I realised that, if I open the product link and then refresh the shop page the image for that product will display correctly. It seems that the same happens to visitors (tried accessing the page in incognito without logging in).

**Comment by devi2998** [comment] 2019-07-19 10:27
I have the same problem
Product images could not be shown in the facebook shop page

**Comment by youreperfect** [comment] 2019-07-30 16:50
We use the Facebook Shop manually (manually entering products directly) and have tons of issues with images not showing. Sometimes they will show up if you click on the product listing like 20 times. Sometimes they never show up and we have to edit the product and reupload the images and wait for approval again - sometimes that doesn't work and it takes 2 or 3 tries. 

So this isn't just a woocommerce issue, but a general FB shop issue and I have no idea who to contact about it. Any suggestions? (if it helps our shop is here: https://www.facebook.com/youreperfectstudio )
