### ISSUE TITLE
Missing conten type + problem with ViewCategory + no event InitiateCheckout

### ISSUE THREAD

**Issue by bossyaka** [facebookincubator/facebook-for-woocommerce#444] opened 2018-04-28 16:12 UTC
Hello!

1. When I open product page event ViewConten have content type: product_group. When I open category page event ViewCategory have content type: product. It should be vice versa?

2. When I visit some of my category pages I have no view event ViewCategory.

For example: https://beauty-shop.top/kokosovye-masla-i-jojoba-oil/ - no event
https://beauty-shop.top/naturalnoe-mylo/ - event present

3. When I open my checkout page I have no event InitiateCheckout.

Could help me?

Sorry for my English :-)

![2018-04-28_18-55-09](https://user-images.githubusercontent.com/38466109/39398451-e2dc7bc4-4b16-11e8-82ed-e4932bf6f71b.png)
![2018-04-28_19-03-39](https://user-images.githubusercontent.com/38466109/39398452-e2fe7b3e-4b16-11e8-9f52-3f5022e21f0d.png)

**Comment by sammul** [comment] 2018-04-30 17:25
@bossyaka Do you have google enhanced ecomm plug-in? Can you disable that and try to see if pixel can be correctly fired? We had known incompatibility issues with their plug-in.

**Comment by bossyaka** [comment] 2018-05-02 14:59
Yes. I use this plugin. I disable it. Now all of my pages (category or product) has only PageView event. I enable enhanced eccom plugin, but now only PageView events.

**Comment by bossyaka** [comment] 2018-05-02 15:07
I roll back to 1.8.5 version, but get the same result - Now all of my pages (category or product) has only PageView event. I enable enhanced eccom plugin, but now only PageView events.

**Comment by mengyingdu** [comment] 2018-05-04 18:56
Hi @bossyaka ,

We suspect the issue is because our `ViewContent` and similar events get injected in the middle of the Google Analytics events, which causes some interference. We have fixed it in [v1.8.7](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.8.7).  Sorry we can't repo this issue since the config of different server could be different. Can you try upgrading to the latest version and see whether it fix your pixel fire issues?

Thanks.

**Comment by mengyingdu** [comment] 2018-05-15 15:42
Hi @bossyaka ,

Any update on this?

**Comment by mengyingdu** [comment] 2018-06-17 18:29
Close this issue now since we haven't got update for a long while. It should be fixed in 1.8.7.

**Closed by mengyingdu** 2018-06-17 18:29 UTC
Labels: bug, compatibility, duplicate
