### ISSUE TITLE
Add to Cart pixel not firing When in the Cart

### ISSUE THREAD

**Issue by belladonnaboutique** [facebookincubator/facebook-for-woocommerce#302] opened 2018-02-26 15:23 UTC
Hi there,

I have noticed on my store that the Add to Cart pixel is only fired when a user clicks "Add to Cart" and an upsell pop-up appears that keeps them on that same page.

If an upsell pop up does NOT appear, and the user is re-directed to the actual Cart, the Add to Cart pixel is NOT fired.

Please see the attached screen shots.

It is odd because, the Add to Cart pixel should fire when the user is actually inside the shopping cart.

How can I resolve this? This affects my FB ads and I cannot run Add to Cart conversions or optimize conversion based campaigns properly if the Add to Cart pixel is not firing properly. 
![screen shot 2018-02-19 at 12 31 44 pm](https://user-images.githubusercontent.com/35646111/36678445-c430f460-1ade-11e8-9ae3-6a2a97f66ccf.png)
![screen shot 2018-02-26 at 10 14 40 am](https://user-images.githubusercontent.com/35646111/36678542-0e6fcaba-1adf-11e8-814b-b182e85247f5.png)

**Comment by belladonnaboutique** [comment] 2018-02-26 15:24
sorry the first screen shot was the wrong one. This is the correct one that shows the Add to Cart pixel firing only when the upsell pop up is triggered
![screen shot 2018-02-19 at 12 32 37 pm](https://user-images.githubusercontent.com/35646111/36678607-354f239c-1adf-11e8-9ac5-1fc5f3671c68.png)

**Comment by mengyingdu** [comment] 2018-03-06 01:04
Hi @belladonnaboutique ,

Sorry for the delayed response.
If you use redirect to cart directly setting in woocommerce, the pixel won't fire at 'add to cart' and this is not a bug. 

The reason of this scenario is 'add to cart' is hooked on the ajax with click action. if you enable direct redirect, it won't reach the hook we added. We decide this backend decision to avoid double fire problem in the shopping cart, eg refresh page.(The initial design and we received tons of request about this)

Thanks for your understanding.

**Comment by belladonnaboutique** [comment] 2018-03-06 01:22
The pixel is not firing when someone is IN the cart,
belladonnaboutique.co/cart/


What do I need to do to make sure the pixel fires when someone is in the
cart?

**Comment by belladonnaboutique** [comment] 2018-03-06 01:27
I do not even know where to find these settings. I am using the FB for Woo
plugin so where would I even find the redirect to cart setting? I have this
setting only in my Beeketing app for the upsell pop-up. I can either
redirect them to the cart or to check out. But this is for the Beeketing
app - not WooCommerce itself.

So when someone is in the Beeketing Pop up upsell, Add to Cart fires.

When someone is just in the cart itself,
Pixel doesn’t fire. How do I fix?

**Comment by mengyingdu** [comment] 2018-03-06 17:28
Hi @belladonnaboutique ,

Can you check the setting in this page?
![screen shot 2018-03-06 at 9 27 54 am](https://user-images.githubusercontent.com/24535640/37047732-b6da8806-2120-11e8-86ac-31fd10ac79b4.png)

**Comment by belladonnaboutique** [comment] 2018-03-06 19:45
Hi I have the first option enabled - redirect to cart page after successful
addition.

I do NOT have the second option ticked like in your screen shot.

Which should it be?

**Comment by belladonnaboutique** [comment] 2018-03-06 20:01
I enabled just the AJAX option, and tried adding to cart again.

I tried with a different product that didn't have an up-sell pop up.

It redirected to the cart, and did not show the Add to Cart pixel, it shows
Subscribed Button Clicked with Add to Cart underneath.

See attached screen shot.

That is not correct ...it should show Add to Cart pixel.

The subscribed button clicked doesnt show for products with the up-sell pop
up though.

**Comment by mengyingdu** [comment] 2018-03-08 22:03
Hi @belladonnaboutique ,

You don't need to care about the  'subscribed button clicked'. It's not your pixel event. It's to send your pixel fired event (the add to cart here) back to pixel if a 'click button' action happened. 
If the 'add to cart' shows up, it is correct.


Thanks.

**Comment by dmitridr** [comment] 2018-03-14 01:13
There's more context on this issue in #219. The issue is, briefly, that the add to cart pixel used to fire inside the cart itself, but we changed that behavior based on user demand. #219 describes a method to change it back to the old behavior. 

Though I think we can come up with an approach that covers both cases @mengyingdu. Marking this as a duplicate bug.

**Comment by belladonnaboutique** [comment] 2018-03-15 14:54
I dont know what is going on with this stupid plugin. I finally got the Add
to Cart pixel to fire last week inside the cart, and now it is gone again!
I am beyond frustrated with this plugin working then not working then
working then not working.

**Comment by dmitridr** [comment] 2018-03-15 20:17
Sorry to hear that. We're definitely trying to get the plugin to be really stable and easy to use, but there are problems like that which means it's not there yet. We'll prioritize the add-to-cart fix after we fix the existing product sync performance issues many people are are having.

**Comment by mengyingdu** [comment] 2018-04-05 06:43
Hi @belladonnaboutique ,

Good news! We fixed this and will ship it in the next release!

Thanks for you feedback!

**Comment by dmitridr** [comment] 2018-04-07 00:04
Yep it's fixed. Here's what we did:

- If your store setting is redirect to cart, we fire the event on the Cart being viewed.
- If your store setting is not redirect to cart, we fire the event via AJAX when the button is clicked.

The fix is in v1.8.4 and later versions available [here](https://github.com/facebookincubator/facebook-for-woocommerce/releases/latest). Thanks for your patience!

**Closed by dmitridr** 2018-04-07 00:04 UTC
Labels: bug, duplicate

**Comment by PoeNedge** [comment] 2019-02-13 22:17
Add to cart event is not working for me either, can you look into this?

**Comment by Waleedov** [comment] 2021-06-27 20:23
Mee too
