### ISSUE TITLE
Plugin Not Syncing Catalog Products Correctly : Displaying Pending and Draft Products

### ISSUE THREAD

**Issue by belladonnaboutique** [facebookincubator/facebook-for-woocommerce#380] opened 2018-04-06 14:31 UTC
Hi there,

I have tried Force ReSync several times, as when I went to check on my Shop section of Facebook, products that were in my Drafts and/or Pending were showing up in my Shop.

Products that had also been deleted permanently from my site were also showing up!

I manually went through all the Draft and Pending products in my Dashboard that were being displayed in my shop, and I manually selected Delete Product Data from Facebook.

This removed all those items from my Shop, however several items that had already been previously permanently deleted from my store were still showing up in my Shop.

After I manually deleted the product data, I then Force Resynced the product data from the plugin settings because I wanted to see if that would then delete the trashed products from my shop.

It did not! In fact, it simply restored my Draft Items and Pending items again!

I ended up Hiding my Shop because I do not have the time to go through the process of manually deleting those items again right now, and there doesnt seem to be a way of deleting the product data from the other items that had already been permanently deleted from my site.

**Comment by dmitridr** [comment] 2018-04-06 20:59
Hello,

This was a problem with older versions, seems odd that it is appearing again. 
Could you please try a full reset, using `Reconfigure > advanced options > delete` then complete setup again on our latest version? Does the problem still occur?

**Comment by MelD78** [comment] 2018-04-06 23:14
I'm having the same issues. 

I'm going in circles, just deleted the plugin and installed the latest version. 
Some products are showing twice (once with correct price, duplication with incorrect price).
I compared all the set up options for each product and nothing jumps out that could cause this issue. 
I've had a developer look at this and he can't work it out. 

This seems to be also causing issues when I'm trying to create "product sets". I tried to create a product set that includes all "Body Care" products with the category body care but it's only pulling up 3 products, whereas it should be 5.

Are you able to assist?

**Comment by belladonnaboutique** [comment] 2018-04-07 17:11
I deleted the plugin and then installed it again and set it up again. The
shop is still propogating but I previewed it and it is still "processing"
products that are saved as drafts, pending reviews, and even products that
had been deleted.

**Comment by MelD78** [comment] 2018-04-09 00:58
@dmitridr Are you guys looking into this issue? Could you please advise on an ETA for resolving this?
Thank you!

**Comment by dmitridr** [comment] 2018-04-09 19:33
@MelD78 could you create a separate issue? The duplication sounds like a different problem from the one described in this issue. Please also double check that you are using the latest version v1.8.4 and if you are not, try upgrading and doing a full reset.

@belladonnaboutique this is by design, we are mirroring the state of the product on Woo on FB: The products that are in the processing state are hidden from normal users on FB who see your shop. If you unhide them on Woo, they will be unhidden on FB. The same for drafts. Products that are trashed will also have the same behavior. Products that are permanently deleted from the trash should disappear from FB forever, however, if they are still showing up in the latest version there could be a problem.

If there are products in the above states that are NOT processing and showing up as visible, please let us know, that would be a bug on our side.

**Comment by belladonnaboutique** [comment] 2018-04-09 20:08
Yes they are showing as visible when they are NOT processing. It was only
initially processing during the set up. But even after the set up is
complete, drafts, pending products, and deleted/permanently deleted
products are still showing up in the shop.

**Comment by dmitridr** [comment] 2018-04-09 21:12
Thanks for confirming that. Could you verify you have v1.8.4 installed? I can't reproduce this problem on our own test servers with the latest version.

**Comment by MelD78** [comment] 2018-04-09 22:04
@dmitridr Will start a separate thread but just to let you know, when I'm logging into my Woocommerce account, there is only version 1.8.3 available as the latest version.

**Comment by belladonnaboutique** [comment] 2018-04-10 19:01
Yes I do have version 1.8.4  - and currently my Shop is displaying 3
permanently deleted products, as well as the Pending and Draft items from
my dashboard.

**Comment by dmitridr** [comment] 2018-04-13 01:13
Really weird, I can't reproduce it on my test server. A couple of questions to try to nail down the cause:

- Do you have any plugins that could be enhancing the standard woo visibility settings?
- Could you elaborate on the `Pending` products, is that functionality added by a plugin?
- For the `Draft` and `Pending` products, if you go to their edit screen, what is the status of their Facebook sync (on the right column), is there an ID there, or does it say `This product is not yet synced to Facebook.`?

Thanks.

**Comment by belladonnaboutique** [comment] 2018-04-13 13:41
I do not believe I have any plugins that could be "enhancing the standard
woo visibility settings," because 1) not sure I know what that means lol,
and 2) I literally have not changed anything in my dashboard. I wasn't
having these issues before, and all I did was Force Resync, then delete the
plugin and upload it again. I am assuming this issue has been occurring
since I first uploaded the newest version of the plugin, I just did not
catch it until recently.

Pending Products means that I have created a product but it has not been
published Live to the site yet; Draft products are pretty much the same
thing. It is not added or operated by a plugin - it is standard with
WooCommerce, you can save a product as a Draft, as Pending, or Publish it
live immediately.

Previously, I did not have any issues with FB for Woo publishing any Draft
or Pending products - it only published my Live products in my shop.

In the draft and pending products, it Does show the Facebook data on them.

I had to go and manually delete the Draft and Pending products' Facebook
Data. However, the products that had already been permanently deleted are
still showing up in my Shop.

I have attached a screen shot. The grayed out boxes are the permanently
deleted products that still show up in the FB Shop.

Also, there are some issues with the pixel duplicating the Subscribed
Button Click pixel. I will open a separate issue for that.

**Comment by belladonnaboutique** [comment] 2018-04-13 13:42
![screen shot 2018-04-13 at 9 33 36 am](https://user-images.githubusercontent.com/35646111/38737990-f5989da2-3efe-11e8-9adb-b7f715c1b9cc.png)

**Comment by mengyingdu** [comment] 2018-04-17 19:09
Hi @belladonnaboutique ,

I'm sorry to hear the problems in your shop and want to follow up with more details.

You have tried to delete then re-sync. Do you mean ONLY delete the plugin or your settings (re-config your settings -->  advance options -> delete settings) ?

You can check the changelog in [1.8.2](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.8.2), we begin to use the same feed id for re-sync. Which means the following situation will have problems:

1. You set up successfully.
2. You draft some products or change the status as invisible.
3. You forced-resync.

Then you force resync based on the original data which is why your manual change is gone. 
WORKAROUND:
1. Make your products as your preferred status (publish or whatever) 
2. delete your settings
3. set up from scratch

We will re-think the design about force-resync and hopefully fix it in the version.

Can you try my suggestions? Let me know if you need more help.

Thanks!

**Comment by belladonnaboutique** [comment] 2018-04-18 02:16
Yes I’m still using.

My site is belladonnboutique.co

And Facebook.com/shopbelladonnaboutique/

I hid my FB shop because it was still showing permanently deleted products
and drafts.

**Comment by milosmili** [comment] 2018-04-26 16:11
is this a bug in 1.8.5 ?

Using Chrome and while logged into my FB profile / page plenty of my products have since 5 days ago the following alert: "Your product is being processed. This usually takes a few minutes. We'll notify you when processing is complete and your product is visible.". Therefore cannot proceed to checkout on my Web site

However on the same PC using Firefox, and NOT being  logged in to FB, the same products do not carry the above message, CHECKOUT button is enabled.

Can someone advise if I can ignore the above message ? How do we kknow sync is 100% done ? I want to make sure all products with all their variations are 100% synced, so that I can disable plugin who's taking lots of resources (cca. 1MB in scripts and server charge)

Pls advise.

Thx.

**Comment by mengyingdu** [comment] 2018-04-26 17:03
Hi @milosmili ,

It seems different from this issue. Can you open another issue to discuss this problem? That will help much for us to categorize and manage priorities.

Thanks.

**Comment by mengyingdu** [comment] 2018-04-26 17:06
Hi @belladonnaboutique,

we had a quality room first half of this week and just released [v1.8.6](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.8.6) We have 10 fixes plus 1 content enhancement. We have a fix for the draft and deleted products if you check the commit history. Can you try to upgrade and force-resync? 
Let me know if you need more help!

Thanks.

**Comment by milosmili** [comment] 2018-04-26 23:04
I have no intention to force re-sync...already got my Web server down, 
corrput my MySQL dband made a mess on my site. Luckily I had a full 
backup s oI restored all.

Please delete ver .1.8.6 and revert back to 1.8.5 or people will be 
really pissed.

Thx.

**Comment by milosmili** [comment] 2018-04-26 23:09
I'd open a new discussion if I knew what I should discuss.

The problem is that I, and many others, don't know what's going on and 
why the plugin is causing so many problems, don't know where to begin.

I am not programmer so I really cannot discuss any tech issues.

For what I can tell is that plugin does not transfer correctly: many 
variations and variations images are not transferred, plugin puts lots 
of load on Web servers.

FB is not willing to help, so I have to find another solution

**Comment by belladonnaboutique** [comment] 2018-04-27 00:07
I haven’t uploaded the new version yet and now I’m wondering if I shouldn’t
🤷‍♀️

**Comment by dmitridr** [comment] 2018-05-09 00:16
@belladonnaboutique thanks for all your feedback in this thread. We were able to nail down and fix the issue with draft products and deleted products. This fix will likely fix pending products as well.

As @mengyingdu said the fix is live in 1.8.7. It's stable and has been out for over a week with no reported issues.

@milosmili regarding your earlier question, (1) if you see the products processing in one browser but not the other, chances are it's a caching issue. If you clear the browser's cache it could fix the problem. (2) After doing a sync (force resync or otherwise) you can monitor the status in greater detail at `www.facebook.com/products` on the `Data Feed` tab. This interface shows a full status of the upload and lets you see what exactly was uploaded.

Regarding 1.8.6, that was not a stable version, we released it in error. Apologies for that. We're building tests so that it never happens again.

Hope that helps bring clarity here. I am closing this issue since we have fixed the problem in the original post (draft/pending) . If this is in error, please let me know and I'll re-open and we can continue investigation.

**Closed by dmitridr** 2018-05-09 00:16 UTC
Labels: bug, follow-up for next release

**Comment by wapiadahy** [comment] 2018-08-09 14:29
Hi, found this looking for same issue but I installed just yesterday so its up to date.
Still facebook imported all my DRAFT products to the catalog
Strange that this conversation was from months ago. Im using Versión 1.9.2

**Comment by vucumbra** [comment] 2018-12-03 12:56
the new version plugin not have fixed nothing

Try remove re-syncro
remove re-syncron
but problem still remaning

Draf products are showing in Facebook Page!

**Comment by vucumbra** [comment] 2018-12-03 13:02
Maybe understand why
this happend when the proucts are imported via csv

I have update all my product in draft via woocommerce (every 100)  and now it seems to work

**Comment by vucumbra** [comment] 2018-12-03 13:14
no I can confirm this plugin not working
some products have hide
some still remains
are all confudes becouse you never understand witch products are published
