### ISSUE TITLE
fbproductfeed.php errors in lines 177, 188

### ISSUE THREAD

**Issue by aand01** [facebookincubator/facebook-for-woocommerce#464] opened 2018-05-04 08:55 UTC
Hi, just installed 1.8.7, and my error log is showing PHP errors along the lines of these:

PHP Warning: Invalid argument supplied for foreach() in path/fbproductfeed.php on line 177 - and the same error is also shown for line 188. The store on FB is now empty, and the plugin says: "Status: Products are synced to Facebook."

Hope this helps pinpoint the issue.

**Comment by mengyingdu** [comment] 2018-05-04 15:44
Hi @aand01 ,

Can you follow the instruction of the support section of the repository main page? We do need more information in order to help you investigate the issue.

Thanks.

**Comment by aand01** [comment] 2018-05-04 15:50
Thanks @mengyingdu, is there a way to submit the details such as FB page & website without having them public here?

**Comment by mengyingdu** [comment] 2018-05-04 16:32
Hi @aand01 ,

If you set up a Facebook shop, I assume you want it public to Facebook users. Only with fb page and website, it won't release any of your credential.

**Comment by aand01** [comment] 2018-05-04 16:34
Sure, what I meant was that I didn't want it public here on github

**Comment by aand01** [comment] 2018-05-04 17:08
Hi @mengyingdu, I just emailed you a private reply - did you receive it?

**Comment by mengyingdu** [comment] 2018-05-06 18:44
Hi @aand01 ,

We received it. Sorry for the delayed replies since our engineer team are limited by these weeks. I will follow up and update you later.

Thanks.

**Comment by mengyingdu** [comment] 2018-05-06 23:33
potential related to  #463

**Comment by mengyingdu** [comment] 2018-05-06 23:38
Hi @aand01,

As for your problem that your shop is empty, there is a bug caused by another team. And it has fixed now. Can you follow my instruction on issue #463? There has been one reporter confirmed that they show up now after follow my instructions. 

Thanks.

**Comment by mengyingdu** [comment] 2018-05-15 15:56
This has been fixed.

**Closed by mengyingdu** 2018-05-15 15:56 UTC
Labels: Bug-not-from-plugin
