### ISSUE TITLE
Products are in the catalogue but not showing in the shop

### ISSUE THREAD

**Issue by centrespot** [facebookincubator/facebook-for-woocommerce#1202] opened 2020-02-05 16:22 UTC
Hi
This issue has probably happened many times in the past but I can't find a solution in the archives.
I have gone through the steps of adding a Facebook shop and linking my wordpress/woocommerce site to the shop without any errors but (every time) it shows that the products have synced but unfortunately they are not showing on the facebook shop page.

**Comment by centrespot** [comment] 2020-02-05 16:39
https://www.facebook.com/bbcmicro/

**Comment by wvega** [comment] 2020-02-05 16:52
Hi @centrespot, unfortunately you right, this issue has occurred several times in the past. I'm sorry you are experiencing it as well.

We are still working on preventing this problem from the plugin and finding clear steps to fix it when it occurs. While we have reports about the problem, is not easy to reproduce it, which makes it harder to understand why is happening or how to fix it.

Would you be able to check https://business.facebook.com/products/ and let me know how many product catalogs you see on that table?

You should see a table like the one below, with information for one or more product catalogs.

<img width="1415" alt="Screen Shot 2020-02-05 at 11 48 56 AM" src="https://user-images.githubusercontent.com/45068/73863179-ae0bb900-480d-11ea-96f0-22c78ef29217.png">


I'm trying to confirm a theory: this problem occurs because two catalogs got created (this is done automatically), the plugin is syncing the products to one and the page is connected to the other.

**Comment by centrespot** [comment] 2020-02-05 16:55
I think your theory could be right, originally when I tried to sort the problem there were two catalogs, I thought the same and deleted the one that didn't have any products in, that didn't sort it though.

**Comment by centrespot** [comment] 2020-02-05 16:58
![facebook](https://user-images.githubusercontent.com/60705492/73863874-a6add500-4838-11ea-890e-0b1971ce18b0.jpg)

**Comment by centrespot** [comment] 2020-02-05 17:09
Just checking whether I have the correct plugin, it downloads as facebook-for-woocommerce.zip and after loading successfully it then upgrades to version 1.9.15. 
Is that correct ?

**Comment by centrespot** [comment] 2020-02-05 17:14
![facebook](https://user-images.githubusercontent.com/60705492/73865228-d9f16380-483a-11ea-84ea-2ceef0a27db0.jpg)

**Comment by wvega** [comment] 2020-02-10 18:07
@centrespot thank you for sharing those details about your setup. I'll try to move forward with the theory that two catalogs are created and see if we can detect and fix that problem from the plugin.

>Just checking whether I have the correct plugin, it downloads as facebook-for-woocommerce.zip and after loading successfully it then upgrades to version 1.9.15. Is that correct ?

That's correct, version 1.9.15 is the latest version available right now.

It appears the releases section on this repository is a bit out of date. I believe that's why you had to upgrade after downloading that zip file. 

The latest version is also available from https://woocommerce.com/products/facebook/ or will show up as an update on your site when a new version is released.

**Comment by dhruvtandel** [comment] 2020-02-12 07:34
I am facing same problem. By default 2 Catalog is being created and not able to sync with facebook page. Is there any solution to fix it ?
Thnx.

**Comment by gguerrab** [comment] 2020-02-12 13:26
Hi there. Same issue. I initially downloaded the plugin from Facebook, but then realized it was outdated, I wasn't able to update. So, I deleted it and dowloaded from WooCommerce (Version: 1.9.15). 
About the two catalogs, I'm not sure now. but maybe the same happened to me.
This Wordpress [support page](https://wordpress.org/support/topic/facebook-for-woocommerce-syncs-but-items-show-not-published-or-rejected/page/3/) from WooCommerce talks about issues with virtual products with variables (which is my case), they suggest to add a few lines to the code but I realized the new version has that exact same code already there.
Would love to find a solution. Let me know if you need any info to help fixing it.

**Comment by Rakesh-Chauhan** [comment] 2020-02-18 03:05
Yes I am also having the same problem. There was already a default catalogue available I think when I created Facebook page with shop tab. And when we try to integrate setting on below screenshot is read only. So it uploads all products on new catalogue which is never shown on facebook page.
![image](https://user-images.githubusercontent.com/37824182/74700405-42433a80-5268-11ea-8e47-46a10a157f17.png)

On the same page chrome console throws below error. Not sure if this is impacting this issue or not but should be fixed i think.
![image](https://user-images.githubusercontent.com/37824182/74700478-88989980-5268-11ea-9fef-c2be13c0a985.png)

**Comment by KojiiH** [comment] 2020-02-18 21:58
I have this same problem with the Plugin. Has anyone found a way to fix this issue yet? I'm getting so frustrated with this. Facebook keeps reverting back to an empty catalogue it creates and the woocommerce catalogue is only available for instagram shopping. It seems I have to manually enter all of my products if there's no way to fix it.

**Comment by filipchrapek** [comment] 2020-02-19 17:53
Same here. Any progress on this?

**Comment by rickdroio** [comment] 2020-02-21 13:50
same issue here

**Comment by souzajr** [comment] 2020-02-22 05:27
Same here.

**Comment by Rakesh-Chauhan** [comment] 2020-02-25 04:09
@wvega Is there any progress on this ? When can we expect resolution ? Or if there is any workaround for the time being.

**Comment by elliotchav** [comment] 2020-03-13 17:07
same issue, it's frustrating :/

**Comment by wvega** [comment] 2020-03-16 17:32
@elliotchav, @Rakesh-Chauhan, @souzajr, @rickdroio, @KojiiH, @gguerrab, @dhruvtandel I'm sorry this problem is still occurring for all of you. I'm currently testing a possible workaround and would like to know whether the steps here work on your Facebook pages.

First, when you go to the Shop section in your Facebook page, do you see a **Delete shop** option like the one below?

<img width="846" alt="Screen Shot 2020-03-16 at 12 11 47 PM" src="https://user-images.githubusercontent.com/45068/76783591-27d58180-6780-11ea-8c3e-d569aba94007.png">

If that's the case, could you try the following steps and let me know if they allow products to show up in the Shop page?

1. Use the **Delete shop** option to remove the Shop section from your Facebook page
1. Don't try to add or access the Shop section in your Facebook page again, let the plugin configure it
1. If necessary, remove the connection between the Facebook for WooCommerce plugin and your Facebook page:
    1. Go to the plugin settings on your WooCommerce store
    1. Click the Manage Connection button
    1. Click Advanced Options on the pop-up window
    1. Click the Remove button to disconnect your WooCommerce store from Facebook
1. Configure Facebook for WooCommerce to connect your store with Facebook

If this works, at this point the Product Catalog used by Facebook for WooCommerce should be the one that is linked with your Facebook page and the products should start showing up in the Shop section.

Would it be possible to give these steps a try and let me know in the comments whether they work for you?

---

This workaround is taken from this comment: https://github.com/facebookincubator/facebook-for-woocommerce/issues/463#issuecomment-564365299

**Comment by centrespot** [comment] 2020-03-17 08:32
It has worked for me.

**Comment by Rakesh-Chauhan** [comment] 2020-03-17 21:49
@wvega Yeah this worked for me too. Thanks a lot. Cheers.

**Comment by filipchrapek** [comment] 2020-03-20 10:27
@wvega All good, appreciate it!

**Comment by lgfogle** [comment] 2020-04-07 00:23
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!

**Closed by lgfogle** 2020-04-07 00:23 UTC
