### ISSUE TITLE
Fb extension error

### ISSUE THREAD

**Issue by SonataAmanes** [facebookincubator/facebook-for-woocommerce#475] opened 2018-05-09 10:04 UTC
Hello,
I am getting the following error:
_Facebook extension error: Facebook for WooCommerce The user must be an administrator, editor, or moderator of the page in order to impersonate it. If the page business requires Two Factor Authentication, the user also needs to enable Two Factor Authentication._
No changes have been made to admins.
Any thoughts on what may cause this?
Thanks

**Comment by sammul** [comment] 2018-05-14 16:16
What's your page name, business id and the name of the person try to setup/config?

**Comment by sammul** [comment] 2018-05-17 21:48
[Note : This is an Automated Message]

Hello,

Thanks for your interest in our plugin!
Due to a high volume of issues we may not be able to get to yours immediately.

If this is a feature request, or feedback, please reply with
Feature Request or Feedback and it will be categorized accordingly, and
we will read it and reply when we can.

If you are experiencing problems, read on.

First. Please check to see if your issue is not a duplicate of another one.
To search our issues, use the search feature at the top of the GitHub issues page.
We have nearly 500 existing and past issues, so it is fairly likely someone else has already reported your problem.
If you do find a relevant issue, please comment in that issue, and close this one.
It helps us prioritize issues to tackle by looking at the number of people with the same problem.

If your issue is unique, and you are sure, then read on.
We require the following information in order to help you:

WooCommerce Version
Wordpress Version
Plugin Version. Please Note that we do not support outdated versions of the plugin.
A Screenshot of where you see the problem. If it is on Facebook, a screenshot of Facebook,
if it is on WooCommerce, a screenshot of WooCommerce. If it is in multiple places, multiple screenshots.
The URL of your website.
The URL of your page.
The URL(s) where you took your screenshot(s).
(If applicable) Detailed steps you took in order to see the problem.
Please be advised, it may take us some time to get to your issue.
In the meantime, below are generic approaches you can take that may solve the issue :

Upgrade to the latest version.
Force Resync
Reset the plugin using Reconfigure > Advanced Options > Delete and setup again.
Try to deactivate other plugins which you think could be interfering and repeating the above.
When you have the above data for us, please include
Debug Ready in your reply. We will get to it and debug it as soon as we can.

Thanks for your patience,
Dev Team (@dmitridr, @mengyingdu, @sammul, @jieminz22)

**Comment by bogdandin** [comment] 2018-05-30 21:17
_Facebook extension error: Facebook for WooCommerce
The user must be an administrator, editor, or moderator of the page in order to impersonate it. If the page business requires Two Factor Authentication, the user also needs to enable Two Factor Authentication._

Same Issue
When i try to edit product and i have 2 plugins active, woo and this one.

WooCommerce Version - last
Wordpress Version - last
Plugin version : Version 1.3.3
rest of the things, i not want to be here...

**Comment by SonataAmanes** [comment] 2018-05-30 21:44
Hi Din,

Is your page, pixel and products showing normally at Reconfigure?
Also, are your products showing correctly at your fb page shop and at the product catalogue?

Regarding the error, there was an error at Reconfigure > Advanced Options, mentioning something about an expired token. Also, this was an easy fix, just pressed a button there. I don't remember details on that, but if this is your case then you will recognize it when you see it.

I am not sure what the source of the problem is, but I had many issues these with this plugin. I think that it is very poorly maintained and practically no support from facebook.

However, if you use woocommerce, it really pays off if you spend the time to make it work. Other plugins (today I tried pixel caffeine) don't offer such seamless cooperation with woocommerce and fb store.

I am not a developer, but please let me know if you feel I can assist any further!

I wish you luck!

**Comment by dmitridr** [comment] 2018-06-11 21:14
Hi, @bogdandin  Please upgrade to 1.8.7, version 1.3.3 is close to a year old now. The number of bugs in the older versions that we have fixed is likely several hundred, it is likely the problem will be fixed from just that (and a reset). 

@SonataAmanes 
We do what we can with little time to support. Thank you for the feedback.
It seems from your comment that you have solved the original problem? If so, I'm glad.
This message you received sounds like it is because the page is owned by a business, or recent changes were made to the business roles on that page. But we would need more details (the details requested in the automated message) in order to help if you are still having the issue.

**Comment by SonataAmanes** [comment] 2018-06-11 21:43
Hi @dmitridr ,

Thank you very much for your reply. I have managed to solve all my issues with the plugin.

As I stated in my previous post, Facebook for Woocommerce has many advantages, compared to other similar plugins and it saves a lot of time and effort when it works with no issues.

However, I feel that the support is below par. Bearing in mind that this is an official facebook plugin and we pay a lot of money to advertise on facebook based on this plugin, I was really surprised by the lack of support. 

Please don't misunderstand me, I am not saying that "I pay and I demand support". My surprise is based on the fact that facebook actually loses money because of the poor support.

**Comment by dmitridr** [comment] 2018-06-11 22:35
Great. Happy to hear that! I will close this out then.

Thanks for jumping in earlier in the thread to help someone with the same issue, we are definitely relying heavily on community support at the moment, as you rightly pointed out our own support is somewhat lacking.

I'll convey your feedback to the rest of our team. We'll see what we can do to improve the support process. Thanks again!

**Closed by dmitridr** 2018-06-11 22:35 UTC
Labels: Automated : Multiple Reports, Automated : Need More Info
