### ISSUE TITLE
Compatibility : WP All Import. Woocommerce Products Not Synced

### ISSUE THREAD

**Issue by CS10-85** [facebookincubator/facebook-for-woocommerce#312] opened 2018-03-06 13:54 UTC
Hi there.
I have an issue on my store where the products don't seem to sync automatically with my Facebook Pixel.

I import products using WP All Imports. As it stands at the minute, there are 32000 products on the store.

Forcing the resync is taking a long time (kind of expected).

Is there anything special I need to do in the WP All Import process itself? I am thinking that maybe the products are being created this way and then its missing out the step that tells it that it needs to sync to facebook.

Only when I go in and edit a product and save does it then sync. Obviously I can't do this for all the products I have!

I am using the latest version of the plugin - Updated it today.

Many thanks  in advance,
Craig

**Comment by jieminz22** [comment] 2018-03-06 20:12
Hi,

WP All Imports is a different plugin from this Facebook for Woocommerce plugin. Sorry we can't help you on that.

**Comment by jieminz22** [comment] 2018-03-06 20:13
You are welcome to try this Facebook for Woocommerce plugin, which will create you a Facebook shop.

**Comment by CS10-85** [comment] 2018-03-06 20:14
Hi,
I'm aware its a different plug in.
WP All Import is importing products into my Woocommerce store from an excel file.

I thought Facebook for Woocommerce would then sync these new products, but it isn't doing.....

**Comment by jieminz22** [comment] 2018-03-06 22:57
Sorry I misunderstood your problem.
Looks like our plugin is not compatible with WP All Imports. I'm marking this as a feature request to support compatibility with WP All Imports.

**Comment by CS10-85** [comment] 2018-03-07 06:54
That's ok.
Is there anything I can do (ie run some SQL in the database) which will make your plug-in think they need syncing?

**Comment by dmitridr** [comment] 2018-03-14 01:28
Looks like it's a duplicate of #32. If force resync is not an option, you can do a bulk edit of the newly imported products, it should be picked up and synced. Unfortunately there isn't any SQL flag or anything that controls the sync of a product to FB right now.

**Comment by CS10-85** [comment] 2018-03-14 07:24
The only reason force resync isn't an option is because of the time taken to sync 50000 products. Am I right in thinking that the browser has to remain open all of the time whilst syncing?

Or can I close the browser and it will carry on in the background?
Its literally going to take days, maybe weeks to fully sync.

The last import I did imported 8000 products, so selecting all of these and bulk editing is probably not feasible either.

**Comment by dmitridr** [comment] 2018-03-20 00:16
@CS10-85 yeah it will take a long time for that many, and yes you need to keep it open. `Force Resync` uses an older method of resyncing, uploading the products one by one. 

As of 1.8.0, We have a newer method for the initial product sync which is extremely fast and uses a product feed, even 50,000 products should only take a few minutes. However it's only for the first sync, so if you want to sync that way you will have to reset the plugin, which means the shop will have to go through review again, and any ads you're running with existing products would have to be stopped.

I think we could potentially change `Force Resync` to use the much faster method, which would help your case, it seems. @mengyingdu do you think it's feasible or is it too complex to do that?

**Comment by CS10-85** [comment] 2018-03-20 07:28
@dmitridr if that could be done it would help my case no end! It really would.

I've been looking for other plugins to use instead, but I'll hang fire in the hope this can be done on force resync as well.

I look forward to @mengyingdu response.

Thanks
Craig

**Comment by dmitridr** [comment] 2018-04-24 00:25
Small update here:

- Version 1.8.3 adds a much faster `Force Resync` via feed. In order to use this new method you'll need to update to one of the latest versions and you will need to reset your installation completely if you've used the previous (slow) method of uploading.
- We're working on compatibility with WP All Import for the next version, it's likely this will be very basic compatibility in the form of a message asking you to `Force Resync` when lots of products have been added, or possibly an automatic Force Resync, if that proves feasible.

**Comment by mengyingdu** [comment] 2018-04-26 20:45
Hi @CS10-85,

We added preliminary compatibility support for WP All Import in [v1.8.6](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.8.6).

Thanks.

**Comment by mengyingdu** [comment] 2018-04-26 20:46
If you like **Facebook-for-WooCommerce**  please leave us a [*****](https://woocommerce.com/products/facebook/) rating. A huge thanks in advance!

**Closed by mengyingdu** 2018-04-26 20:45 UTC
Labels: compatibility, duplicate, feature-request

**Comment by gaitagarcia** [comment] 2022-01-18 14:16
> Hola. Tengo un problema en mi tienda en el que los productos no parecen sincronizarse automáticamente con mi píxel de Facebook.
> 
> Importo productos usando WP All Imports. Tal como está en el momento, hay 32000 productos en la tienda.
> 
> Forzar la resincronización está llevando mucho tiempo (algo esperado).
> 
> ¿Hay algo especial que deba hacer en el proceso wp all import? Estoy pensando que tal vez los productos se están creando de esta manera y luego se está perdiendo el paso que le dice que necesita sincronizarse con Facebook.
> 
> Solo cuando entro y edito un producto y lo guardo, se sincroniza. ¡Obviamente no puedo hacer esto para todos los productos que tengo!
> 
> Estoy usando la última versión del plugin - Actualizado hoy.
> 
> Muchas gracias de antemano, Craig



> Hi there. I have an issue on my store where the products don't seem to sync automatically with my Facebook Pixel.
> 
> I import products using WP All Imports. As it stands at the minute, there are 32000 products on the store.
> 
> Forcing the resync is taking a long time (kind of expected).
> 
> Is there anything special I need to do in the WP All Import process itself? I am thinking that maybe the products are being created this way and then its missing out the step that tells it that it needs to sync to facebook.
> 
> Only when I go in and edit a product and save does it then sync. Obviously I can't do this for all the products I have!
> 
> I am using the latest version of the plugin - Updated it today.
> 
> Many thanks in advance, Craig

Hi Friend, how you solved this? i have the same error.
