### ISSUE TITLE
No add products to a facebook shop button

### ISSUE THREAD

**Issue by WOBusiness** [facebookincubator/facebook-for-woocommerce#486] opened 2018-05-16 23:19 UTC
Hi
I have installed the plugin and synced the products but there is no "Add Products to a facebook shop" slider button. As a result all my products are visible within the facebook merchant centre but not on my facebook page as a shop. 

I have deleted and reinstalled looking for this button... PLEASE HELP. 
Thankyou.

**Comment by sammul** [comment] 2018-05-17 21:05
[Note : This is an Automated Message]

Hello,

Thanks for your interest in our plugin!
Due to a high volume of issues we may not be able to get to yours immediately.

If this is a feature request, or feedback, please reply with
`Feature Request` or `Feedback` and it will be categorized accordingly, and
we will read it and reply when we can.

If you are experiencing problems, read on.

First. Please check to see if your issue is not a duplicate of another one.
To search our issues, use the search feature at the top of the GitHub issues page.
We have nearly 500 existing and past issues, so it is fairly likely someone else has already reported your problem.
If you do find a relevant issue, please comment in that issue, and close this one.
It helps us prioritize issues to tackle by looking at the number of people with the same problem.

If your issue is unique, and you are sure, then read on.
We require the following information in order to help you:
- WooCommerce Version
- Wordpress Version
- Plugin Version. Please Note that we do not support outdated versions of the plugin.
- A Screenshot of where you see the problem. If it is on Facebook, a screenshot of Facebook,
if it is on WooCommerce, a screenshot of WooCommerce. If it is in multiple places, multiple screenshots.
- The URL of your website.
- The URL of your page.
- The URL(s) where you took your screenshot(s).
- (If applicable) Detailed steps you took in order to see the problem.

Please be advised, it may take us some time to get to your issue.
In the meantime, below are generic approaches you can take that may solve the issue :
- Upgrade to the latest version.
- Force Resync
- Reset the plugin using `Reconfigure > Advanced Options > Delete` and setup again.
- Try to deactivate other plugins which you think could be interfering and repeating the above.

When you have the above data for us, please include
`Debug Ready` in your reply. We will get to it and debug it as soon as we can.

Thanks for your patience,
Dev Team (@dmitridr, @mengyingdu, @sammul, @jieminz22)

**Comment by WOBusiness** [comment] 2018-06-11 05:43
WooCommerce Version: 3.3.5
Wordpress Version: 4.9.6–en_AU
Plugin Version:  1.8.7
The URL of your website: https://glitterhaven.com.au
The URL of your page: https://www.facebook.com/pg/glitterhaven/shop/

There is no Add to Facebook button - even when I delete and reupload the plugin. 

![facebook shop toggle](https://user-images.githubusercontent.com/38719858/41214288-de21bbd2-6d8d-11e8-8d22-0be81d0143fc.PNG)

**Comment by WOBusiness** [comment] 2018-06-11 06:04
Looking through other threads, is it possible that my shop has been blacklisted? If so why??


From the comment in #134 , looks like this was resolved.If the slider doesn't show, it's usually because of the blacklist. If the slider does show, but the products do not appear for a while, it's due to review.
--

Can my shop be whitelisted please. 
Thankyou

**Comment by mengyingdu** [comment] 2018-06-28 22:00
@dmitridr ,

I heard you have mentioned blacklist issue before but i don't know the full context. Any ideas?

**Comment by WOBusiness** [comment] 2018-07-11 01:44
![no toggle](https://user-images.githubusercontent.com/38719858/42546141-530a5822-84ff-11e8-9d35-fff4780a0831.PNG)
Hi
I have done as you requested, and reset the plugin using Settings > Reconfigure > Advanced Options > Delete, but as you can see the toggle is not visible. 

Facebook page ID is: 609521342494632
https://www.facebook.com/pg/glitterhaven/

Thankyou for your help.

**Comment by dmitridr** [comment] 2018-08-02 20:06
Hello, 

Do you still see this problem? We recently redesigned the page that you showed a screenshot of. It may be worth trying again. I checked your page, it does not appear to be blacklisted.

There is another possibility that you are accessing Facebook from one of the 5 restricted countries (Cuba, NK, Iran, Syria, Sudan). It seems unlikely since I assume from your shop that you are in Australia, but I would like to double check to make sure we can rule this out.

**Comment by mengyingdu** [comment] 2018-08-10 01:50
@WOBusiness Your shop has already set up.https://www.facebook.com/pg/glitterhaven/

**Closed by mengyingdu** 2018-08-10 01:50 UTC
Labels: Automated : Debug Ready
