### ISSUE TITLE
Your server is sending an invalid ip_address, user_agent 

### ISSUE THREAD

**Issue by sorucofernando** [facebookincubator/facebook-for-woocommerce#1681] opened 2020-11-05 15:47 UTC
Your server is sending an invalid ip_address, user_agent parameters value for your ViewCategory event. This may be because there was an error in the parameter value.

**Comment by tamarazuk** [comment] 2020-11-05 20:54
This is a duplicate of #1682

**Closed** 2020-11-05 20:58 UTC
Labels: duplicate
