### ISSUE TITLE
latest update 2.1.2. caused debug error with WordPress

### ISSUE THREAD

**Issue by Zanypig** [facebookincubator/facebook-for-woocommerce#1670] opened 2020-10-29 14:27 UTC
## 🔎 Isolate the bug

- [Y ] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [Y ]I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug

![IMG-20201029-WA0000](https://user-images.githubusercontent.com/73652831/97586847-a4a52b00-19f2-11eb-8c68-b01428eb1bf2.jpg)

##🚶‍♀️ Steps to reproduce

1. The first step
1. The next step…

**Comment by Zanypig** [comment] 2020-11-03 08:37
I have deactivated the plugin until I receive a reply.

**Comment by simonporter007** [comment] 2020-11-09 15:41
Duplicate of #1652

**Closed by simonporter007** 2020-11-09 15:41 UTC
