### ISSUE TITLE
No pictures after synchronization : 403 From FB Side when Fetching Images -> Hotlinking Disabled?

### ISSUE THREAD

**Issue by PolyMen** [facebookincubator/facebook-for-woocommerce#177] opened 2017-12-04 00:00 UTC
Hi, pals!

First of all - thanks for your work!
About problem. I can't find any information about some problems, but in my case - something wrong with product's pictures. After synchronization products created without pictures on Facebook side. Actually I can see pictures, but only on the Product Catalog page. On [my shop page](https://www.facebook.com/pg/topshopmir.ru/shop/) all products without pictures. And on place of product picture, if I look code of page - just 1x1 gif file.

![face1](https://user-images.githubusercontent.com/19803594/33531507-176f4bae-d89f-11e7-8019-d95a365ce1e9.JPG)
![face2](https://user-images.githubusercontent.com/19803594/33531521-3c7b864c-d89f-11e7-894b-718a1633d4d2.JPG)

WordPress - 4.9.1
Woocommerce - 3.2.5
Facebook for Woocommerce - 1.6.6 #134

**Comment by PolyMen** [comment] 2017-12-04 10:28
In appendix...

If in the item card, click the button "More fields" - in the string with image_url, I see the[ following image link](https://external.xx.fbcdn.net/safe_image.php?d=AQB6N3F9oPwTu68F&url=https%3A%2F%2Ftopshopmir.ru%2Fwp-content%2Fuploads%2F2016%2F11%2Fshop_property_file_1344_2491.jpg&cfs=1&_nc_hash=AQADLwB3LHpNkcaJ), for example. 
![face3](https://user-images.githubusercontent.com/19803594/33548000-d77a9a78-d8f6-11e7-9534-3323ed6b71bf.JPG)

**Comment by dmitridr** [comment] 2017-12-04 22:03
Hello,

Thanks for reporting this issue. It looks like any ads you may have (da_display_preview_url in your screenshot) will still load the image. But it's strange that the main image does not load in the shop or in the catalog manager page. 

I've double checked and it doesn't appear to be an issue with our plugin, so I've forwarded this to our product catalog team, we'll see if they can resolve it. I'll update if there's some progress.

**Comment by PolyMen** [comment] 2017-12-05 09:21
Good news...!

**Comment by PolyMen** [comment] 2017-12-06 01:13
Sod’s Law! My apologies, but Christmas sales just round the corner! We are waiting for...

**Comment by fagnersantos** [comment] 2017-12-07 19:05
Same here... I'm trying to use another tool while they fixed this. :-(

**Comment by dmitridr** [comment] 2017-12-07 21:09
I've asked the catalog team for updates about the fix, stay tuned. Thanks for your patience.

**Comment by PolyMen** [comment] 2017-12-08 10:58
@fagnersantos If you find good working plugin - note here! OK?

**Comment by PolyMen** [comment] 2017-12-08 10:59
@dmitridr Дмитрий, что-то Ваша команда не спешит что-то делать! 4 дня и ничего!

**Comment by fagnersantos** [comment] 2017-12-08 15:46
@PolyMen I'm trying Storeya. It has a limit of 20 products on the free version. I guess I'll use that until Facebook decides to fix this issue, if they will fix.

**Comment by PolyMen** [comment] 2017-12-08 16:42
@fagnersantos I think they will, but given that it's free - it will not quickly :-)

**Comment by dmitridr** [comment] 2017-12-08 19:34
Ok, the catalog team says the issue is we get a 403 when hitting your servers to try to fetch your product images. Can either of you confirm that you don't have any plugins or server settings to cause this to happen? Something like a plugin to prevent hotlinking enabled?

**Comment by dmitridr** [comment] 2017-12-08 19:50
If you do have such settings, could you disable them or whitelist requests by Facebook so that we can fetch your images? I believe the user agent has `facebook` in the string.

**Comment by PolyMen** [comment] 2017-12-15 13:29
Hi pals! Everything, what I can say, that use [Swift Perfomance](http://swift-performance.swteplugins.com/) for caching

**Comment by dmitridr** [comment] 2017-12-15 21:14
Can you try a full reset of the plugin (Reconfigure > Advanced Options > Delete), then deactivating Swift Performance, then setting up again and seeing if the images will load in the Shop and Catalog Manager?
Then if all is well, it should be okay to enable Swift Performance again.

**Comment by PolyMen** [comment] 2017-12-17 17:55
@dmitridr I will try today

**Comment by dmitridr** [comment] 2018-03-14 00:55
Hey again, I guess it didn't work since I still see your shop has blank images. Any idea why your server would return 403?

I tried accessing an example image directly, for example `https://topshopmir.ru/wp-content/uploads/2017/04/hot-power-belt-pink.jpeg` and got a certificate error for your site, perhaps that's the cause?

**Comment by dmitridr** [comment] 2018-03-23 00:31
Closing this as we believe it to be a certificate issue with your site which prevents FB from fetching your images, please open a new issue on us if there's still a problem on our side.

**Closed by dmitridr** 2018-03-23 00:31 UTC
Labels: bug, shops-feature
