### ISSUE TITLE
Categories Don't Sync + Sync Affects Draft/Pending Products

### ISSUE THREAD

**Issue by alexhwan** [facebookincubator/facebook-for-woocommerce#364] opened 2018-03-31 07:13 UTC
1. Categories don't sync anymore
2. Variations sync now as separate products
3. Sync affects all products from a shop, including drafts, pending, etc.

**Comment by jjbbrr** [comment] 2018-03-31 08:55
Just confirming points 1 & 2. Point 2 especially is a critical issue as it's making draft content live.

**Comment by alexhwan** [comment] 2018-03-31 09:49
Point 2 (variations) maybe was like it even before, don't really remember. 
But Point 1 and 3 are really critical.

**Comment by mengyingdu** [comment] 2018-04-23 17:00
seems related to #380

**Comment by dmitridr** [comment] 2018-04-23 22:29
Hi @alexhwan @jjbbrr just want to clarify the problem here.

(1) Categories should be inside `Product Type` if you need them for ads. Could you provide a link to a product which does not have categories properly synced?
(2) They were always separate products in the catalog, that's by design, they should still appear in the shop as the same product.
(3) We're looking into this in #380

**Comment by jjbbrr** [comment] 2018-04-24 08:06
Just had another look at this and I can't see the logic behind why some products are displaying and some aren't. It doesn't seem related to whether they are set to show/hide in the WP dash. I can't share mine sorry as I've now hidden the shop on the Facebook page since I can't control what displays there.

**Comment by mengyingdu** [comment] 2018-04-26 22:29
Hi @alexhwan,

We have a fix for draft product being synced in [v1.8.6](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.8.6). Also, we had a quality room first half of this week and have 10 fixes plus 1 content enhancement  in this new version.

Can you try to upgrade and then go through a full reset your settings and re-sync your products?
Instructions:
1. go to 'woocommerce' -> settings  -> integrations -> facebook-for-woocommerce
2. In the blue panel, click on 're-config'
3. In the popup window, 'advance option' -> delete your settings
4. back to the blue panel, click on 'get started' -> finish setup

Let me know if it works for you.

Thanks.

**Comment by mengyingdu** [comment] 2018-04-26 22:40
Hi @jjbbrr,

Sorry to hear you disable your shop, I'd like to explain more details. 
1. show/hide button in your woocommerce editor:
It controls whether a visitor (except you as page admin)
2. The display logic in your Facebook shop:
1) If you run dynamic ads, the upselled products will be sorted before others
2) In you All Products collection don't have complicated logic in terms of order. For a variable product, if you set a variation as default, it will be there as a representative of the variation group. For a simple product, it will just show up.

Thanks.

**Comment by alexhwan** [comment] 2018-04-28 03:55
Hi @mengyingdu ,

1. Now the sync process works only if I am not pushing the products to FB Shop. Categories don't sync at the same time.
![image](https://user-images.githubusercontent.com/37950576/39391751-a712337a-4ad2-11e8-9bb1-1a602ee1b4f6.png)


2. When the sync with the shop is enabled, all products are disappearing after the sync process is finished. And FB shows that products were uploaded in manual mode.

Sync with the FB shop doesn't work. 

Thanks.

Alex.

**Comment by mengyingdu** [comment] 2018-05-15 16:10
your facebook page?
Your site url? @alexhwan 

Generally, you may need to wait a couple of hours till products synced complete and showing up in your shop.

Thanks.

**Comment by dmitridr** [comment] 2018-06-22 21:10
Closing this, as there has not been a reply for >1month. 
We should have fixed this in [1.8.7](https://github.com/facebookincubator/facebook-for-woocommerce/releases) (out on May 2nd). 
If the issue is still occurring, please open a new issue and reference this one so we can continue discussion with full context.

**Closed by dmitridr** 2018-06-22 21:10 UTC
Labels: bug, follow-up for next release

**Comment by quique-iterando** [comment] 2019-04-04 19:25
I'm having the same issue with the categories not syncing and its grayed out in the filter menu. "Your current selection has not returned any options for this filter."
All the products have the product_type synced correctly.
![Screen Shot 2019-04-04 at 13 24 52](https://user-images.githubusercontent.com/40504400/55582575-1a44fa00-56dd-11e9-869d-be129d903234.png)

**Comment by SergiOca87** [comment] 2019-04-08 10:54
This is not fixed. It syncs everything, I have only 20 visible products and it syncs 300 drafts and every variation is a new product on Facebook...
