### ISSUE TITLE
Wrong product currency per language (Woocommerce WPML)

### ISSUE THREAD

**Issue by yurabogdanov** [facebookincubator/facebook-for-woocommerce#517] opened 2018-05-31 11:53 UTC
Hello,

We have a Woocommerce shop which runs on Woocommerce V 3.3.4, with products translated for two languages (EN / UA) with WPML (Woocommerce Multilingual V 4.2.9). For each language we've set custom prices (for example, the sweatshirt may cost EN — 90 € / UA — 1100 UAH).

After we've used Facebook for Woocommerce plugin (now V 1.8.7) the products were synced to our Facebook catalog and we've faced two issues (see the screenshot below): 

1) There are duplicates for each product (EN in blue / UA in red for 4 available sizes). Not sure if it's an actual problem, but I've found a workaround in WPML support: https://wpml.org/forums/topic/facebook-for-woocommerce-extension-products-displaying-twice/#post-1296482

2) Currencies have been set wrong (correct for EN in blue, set in € / incorrect for UA in red, must be UAH and different price)

Can you fix these issues so we can reupload the products correctly?
Thanks!

![image](https://user-images.githubusercontent.com/17838168/40780800-5b91d840-64e2-11e8-8312-d75bac32478a.png)

**Comment by RainingJing** [comment] 2018-05-31 17:27
[Note : This is an Automated Message]

Hello,

Thanks for your interest in our plugin!
Due to a high volume of issues we may not be able to get to yours immediately.

If this is a feature request, or feedback, please reply with
`Feature Request` or `Feedback` and it will be categorized accordingly, and
we will read it and reply when we can.

If you are experiencing problems, read on.

First. Please check to see if your issue is not a duplicate of another one.
To search our issues, use the search feature at the top of the GitHub issues page.
We have nearly 500 existing and past issues, so it is fairly likely someone else has already reported your problem.
If you do find a relevant issue, please comment in that issue, and close this one.
It helps us prioritize issues to tackle by looking at the number of people with the same problem.

If your issue is unique, and you are sure, then read on.
We require the following information in order to help you:
- WooCommerce Version
- Wordpress Version
- Plugin Version. Please Note that we do not support outdated versions of the plugin.
- A Screenshot of where you see the problem. If it is on Facebook, a screenshot of Facebook,
if it is on WooCommerce, a screenshot of WooCommerce. If it is in multiple places, multiple screenshots.
- The URL of your website.
- The URL of your page.
- The URL(s) where you took your screenshot(s).
- (If applicable) Detailed steps you took in order to see the problem.

Please be advised, it may take us some time to get to your issue.
In the meantime, below are generic approaches you can take that may solve the issue :
- Upgrade to the latest version.
- Force Resync
- Reset the plugin using `Reconfigure > Advanced Options > Delete` and setup again.
- Try to deactivate other plugins which you think could be interfering and repeating the above.

When you have the above data for us, please include
`Debug Ready` in your reply. We will get to it and debug it as soon as we can.

Thanks for your patience,
Dev Team (@mengyingdu, @sammul, @jieminz22, @dmitridr)

**Comment by dmitridr** [comment] 2018-06-11 20:38
Hello,

Thanks for the detailed info!
 
(1) If you are seeing this in catalog manager, it is not a bug. Each variation is treated as an individual product in Facebook, but displayed as one item in the shop. Some of our older issues cover this duplication and the reasoning behind it more extensively.
(2) Definitely seems like a bug. We will get to this when we can, in the meantime consider looking through some of our other WPML issues, they may have some suggestions on a workaround.

**Comment by mengyingdu** [comment] 2018-06-28 22:32
I think the currency sign issue is caused by this [line](https://github.com/facebookincubator/facebook-for-woocommerce/blob/master/includes/fbproduct.php#L460)
Basically, it gets woo default currency ,so WPML didn't override it. @dmitridr

**Comment by dmitridr** [comment] 2018-08-10 23:31
I agree it's probably that line, but I have no clue how to fix it. If any developer who has worked with WPML has an idea, would love to hear it. Tagged with help-wanted.

**Comment by mengyingdu** [comment] 2018-11-13 00:49
Hi @yurabogdanov 
I'm looking into this issue, however, the Woocommerce Multilingual is a paid plugin. Is it OK to share with us your plugin zip file (including translation manager and WPML translation? 
ads_extension_woocommerce@fb.com

**Comment by elaxfr** [comment] 2019-05-13 13:20
@yurabogdanov did you finally get a solution to manage multiple currencies in TF shop?

**Comment by yurabogdanov** [comment] 2019-05-13 20:45
@elaxfr nope, we've just started using different solution

**Comment by elaxfr** [comment] 2019-05-14 07:13
OK thank you. You use a custom feed?

**Comment by elaxfr** [comment] 2019-06-10 07:49
@yurabogdanov can I ask you which solution you found?
Thank you :)

**Comment by lgfogle** [comment] 2020-04-06 23:16
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!

**Closed by lgfogle** 2020-04-06 23:17 UTC
Labels: bug, compatibility, help wanted
