### ISSUE TITLE
Product variations and images are not synching

### ISSUE THREAD

**Issue by AllenTTS** [facebookincubator/facebook-for-woocommerce#45] opened 2017-09-21 11:12 UTC
Hi,

I've synchronized some product of my webshop, but variations are not synchronizing. People can see that there are options to choose, but can't select them. Example: https://www.facebook.com/commerce/products/1659319230745279/
Besides this, not all images are synchronizing. 

Any idea how to solve these issue?

Thanks,
Allen

**Comment by AllenTTS** [comment] 2017-09-21 11:26
Saw that i had an old version. Just updated the plugin and deleted the product en synchronized it again. Still not resolved. new example: https://www.facebook.com/commerce/products/1494009897313077/

**Comment by dmitridr** [comment] 2017-09-21 19:40
Troubling. Thanks for flagging this. Could you send us a screenshot of how the configuration of the product looks on the WooCommerce side? Then we can try to reproduce and fix the problem.

**Comment by AllenTTS** [comment] 2017-09-21 19:55
Of course!

![schermafbeelding 2017-09-21 om 21 49 59](https://user-images.githubusercontent.com/32164045/30715623-4a534b9a-9f17-11e7-98fb-29160ff9fcc4.png)
![schermafbeelding 2017-09-21 om 21 49 45](https://user-images.githubusercontent.com/32164045/30715624-4a6bf8fc-9f17-11e7-8da3-59b9ee623dea.png)

Product link: https://babykleding.today/product/mom-plus-dad-romper/

**Comment by dmitridr** [comment] 2017-09-22 23:14
Hello, looks like because you select `any` as the option, it's not syncing correctly. This was a problem we had in older versions and we should have fixed in 1.6.0.

I checked your site and it seems like you have version 1.5.1, could you upgrade to [1.6.1](https://github.com/facebookincubator/facebook-for-woocommerce/releases/latest)? If our fix worked then it should fix your problem.

cc @mengyingdu

**Comment by AllenTTS** [comment] 2017-09-23 14:29
Hi,
I've updated to 1.6.1 and following is happening.

- Still only first main picture is published.
- I've to create all variations manually, only than variations are shown on Facebook shop.
- When selecting check out on website, only the general product (no variation) is pushed

**Comment by mengyingdu** [comment] 2017-09-25 15:46
Hi AllenTTS,

1. picture issue: We will look into that. 
2. variation: We fix variation 'any' value issue in this way:
Before 1.6.1, checkout url and picture can't work if variation value is 'any'. 
1.6.1, checkout url and picture work and we redirect shoppers to original product page to select. This is because we have different object structure in backend from Woo. We may implement this based on priority of feature request.

Thanks.

**Comment by AllenTTS** [comment] 2017-09-25 21:12
Hi,

1. thanks
2. visitors are redirected to check out page and have to remove the product first and then have to find product page and select the variation here.

Allen

**Comment by mengyingdu** [comment] 2017-09-26 02:56
Hi,

Gallery image sync issue has been solved and we will release in next update.
However, i can't repro the checkout url issue. It works for me (redirect to product page and they can select attribute)

**Comment by AllenTTS** [comment] 2017-09-26 10:22
thanks

**Comment by mengyingdu** [comment] 2017-09-29 00:33
Hi @AllenTTS ,

We just release v1.6.2 to fix variable product gallery images unable to sync issue. Can you try it?
Let us know whether it works.
[v1.6.2](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.6.2)
Thanks!

**Closed** 2017-09-29 21:16 UTC
Labels: bug

**Comment by rastroks** [comment] 2017-12-25 23:07
How can I show on Facebook products with only a price? Those products that have a presence in the warehouse. Thanks!
