### ISSUE TITLE
Facebook extension error: Facebook for WooCommerce Unsupported post request. Object with ID '#' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api 

### ISSUE THREAD

**Issue by hatcheddesigns** [facebookincubator/facebook-for-woocommerce#411] opened 2018-04-15 23:59 UTC
Hello please advise on the below error: 

Facebook extension error: Facebook for WooCommerce
Unsupported post request. Object with ID '1334684519986763' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api 

thanks.

**Comment by sammul** [comment] 2018-04-16 23:25
@hatcheddesigns are you the person who set up the extension on your website?

**Comment by hatcheddesigns** [comment] 2018-04-17 00:47
@sammul yes

**Comment by hatcheddesigns** [comment] 2018-04-17 00:47
yes

*Carly Rawiri*
* Hatched Designs – Website Designer*
https://hatcheddesigns.com.au
[image: Facebook] <http://www.facebook.com/hatchedwebsitedesign> [image:
Twitter] <https://twitter.com/Hatcheddesigns> [image: Linkedin]
<http://www.linkedin.com/profile/view?id=139064012&trk=nav_responsive_tab_profile>
[image:
Instagram] <http://instagram.com/hatcheddesigns#>
ABN: 75507748700

**Comment by sammul** [comment] 2018-04-17 18:15
Seems similar with this issue #400 
Would you mind trying what @dmitridr suggested?

**Comment by hatcheddesigns** [comment] 2018-04-18 00:07
Thanks, we tried the update, where is this found?

Reconfigure > Advanced Options > Delete on the plugin's config page

*Carly Rawiri*
* Hatched Designs – Website Designer*
https://hatcheddesigns.com.au
[image: Facebook] <http://www.facebook.com/hatchedwebsitedesign> [image:
Twitter] <https://twitter.com/Hatcheddesigns> [image: Linkedin]
<http://www.linkedin.com/profile/view?id=139064012&trk=nav_responsive_tab_profile>
[image:
Instagram] <http://instagram.com/hatcheddesigns#>
ABN: 75507748700

**Comment by hatcheddesigns** [comment] 2018-04-18 05:52
My client has realised it was because she deactivated her fb marketer from
her account as admin, can she just reconfigure it on her own account now?

*Carly Rawiri*
* Hatched Designs – Website Designer*
https://hatcheddesigns.com.au
[image: Facebook] <http://www.facebook.com/hatchedwebsitedesign> [image:
Twitter] <https://twitter.com/Hatcheddesigns> [image: Linkedin]
<http://www.linkedin.com/profile/view?id=139064012&trk=nav_responsive_tab_profile>
[image:
Instagram] <http://instagram.com/hatcheddesigns#>
ABN: 75507748700

**Comment by sammul** [comment] 2018-04-19 02:34
@hatcheddesigns if she is the admin on the page, she can go delete the setting following Reconfigure > Advanced Options > Delete. And then re-do the set up on herself

**Comment by hatcheddesigns** [comment] 2018-04-19 05:52
Thank you the client has asked: 

I cant without loosing all of the campaigns im currently running though, can i?
We have a lot of dynamic ads running which are really preforming.

Carly, 

Hatched

**Comment by sammul** [comment] 2018-04-19 16:12
@hatcheddesigns What's her name? I'm trying to find out what role she has on the page

**Comment by hatcheddesigns** [comment] 2018-04-19 22:10
Mel rothero she is the page owner...

Carly, 

Hatched

**Comment by sammul** [comment] 2018-04-20 15:17
@hatcheddesigns I checked the business, there are 2 pages with same. The setup was through page 1623740501178030, which she has no role on. Please add admin role for her on this page.

**Comment by dmitridr** [comment] 2018-04-20 20:50
Hi @hatcheddesigns 

Seems like the problem is due to permissions. If the person who originally went through the setup flow loses permission on the page or changes their password, the API token which was generated will no longer be valid.

As @sammul said above, one way to solve is to reset. If you do not want to do this, there's a way you can reset only the token, but it requires a bit of technical work. The client needs to follow these steps:

(1) Go to the configuration page for the plugin.
(2) Open the JS console, (Ctrl + Shift + J) on Chrome.
(3) Type : `window.facebookAdsToolboxConfig.tokenExpired = true;` hit Enter. This will trick our system into thinking your token needs to be reset.
(4) Click `Reconfigure`. 
(5) Go to `Advanced Options`
(6) There should be an `Update Token` option visible.
(7) Click `Update Token` which should generate a new token and set it in WooCommerce.
(8) If the error doesn't go away, try a `Force Resync`.

If this doesn't work, unfortunately the best way to solve this is a complete reset. If you have running campaigns, those would need to be re-created with the new catalog. During a reset, you *may* be able to preserve the existing catalog if, for example, you transfer all permissions on this catalog to a 3rd user prior to doing the reset.

Hope that helps.

**Comment by dmitridr** [comment] 2018-06-13 18:37
I'm closing this out since there hasn't been a response in a while. Hope you solved your problem! If not please open a new issue on us and reference this one.

**Closed by dmitridr** 2018-06-13 18:37 UTC
Labels: question
