### ISSUE TITLE
FB Page not showing while Woocommerce integration + business manager page

### ISSUE THREAD

**Issue by nishantgautam194** [facebookincubator/facebook-for-woocommerce#496] opened 2018-05-20 09:56 UTC
When running the setup of FB for woocommerce integration, Facebook page is not showing up in drop down menu.The page i want to add is in fb business manager.While other pages are showing up which are not in business manager.Please suggest.

Thanks,
Nishant

**Comment by mengyingdu** [comment] 2018-05-21 00:03
[Note : This is an Automated Message]

Hello,

Thanks for your interest in our plugin!
Due to a high volume of issues we may not be able to get to yours immediately.

If this is a feature request, or feedback, please reply with
`Feature Request` or `Feedback` and it will be categorized accordingly, and
we will read it and reply when we can.

If you are experiencing problems, read on.

First. Please check to see if your issue is not a duplicate of another one.
To search our issues, use the search feature at the top of the GitHub issues page.
We have nearly 500 existing and past issues, so it is fairly likely someone else has already reported your problem.
If you do find a relevant issue, please comment in that issue, and close this one.
It helps us prioritize issues to tackle by looking at the number of people with the same problem.

If your issue is unique, and you are sure, then read on.
We require the following information in order to help you:
- WooCommerce Version
- Wordpress Version
- Plugin Version. Please Note that we do not support outdated versions of the plugin.
- A Screenshot of where you see the problem. If it is on Facebook, a screenshot of Facebook,
if it is on WooCommerce, a screenshot of WooCommerce. If it is in multiple places, multiple screenshots.
- The URL of your website.
- The URL of your page.
- The URL(s) where you took your screenshot(s).
- (If applicable) Detailed steps you took in order to see the problem.

Please be advised, it may take us some time to get to your issue.
In the meantime, below are generic approaches you can take that may solve the issue :
- Upgrade to the latest version.
- Force Resync
- Reset the plugin using `Reconfigure > Advanced Options > Delete` and setup again.
- Try to deactivate other plugins which you think could be interfering and repeating the above.

When you have the above data for us, please include
`Debug Ready` in your reply. We will get to it and debug it as soon as we can.

Thanks for your patience,
Dev Team (@dmitridr, @mengyingdu, @sammul, @jieminz22)

**Comment by mengyingdu** [comment] 2018-06-30 21:40
@nishantgautam194 
We do see permission problems if a page is connected with business manager. We talked with the interface team but not solution yet. If you can try disconnect the page with business manager, and then setup , it should fix.

**Comment by mengyingdu** [comment] 2018-08-17 22:04
## Automated Support Message - Issue Closed

Hello,

Because it has been 30 days since this issue was updated and you have not included `Debug Ready` in your reply, our automated system will now close your issue.
If you are still having this problem, please open a new issue and reference this one.

For more information on our response times and support policy, visit [Facebook Support on GitHub](https://github.com/facebookincubator/facebook-for-woocommerce/wiki/Facebook-Support-on-GitHub).

Thank you,
The Facebook Dev Team

**Closed by mengyingdu** 2018-08-17 22:04 UTC
Labels: Automated : Need More Info

**Comment by DJSavill** [comment] 2019-09-03 19:26
Hi, Im having exactly the same problem,

However, I don't see anywhere on Facebook's side to disconnect WooCommerce from it, and have found no step by step guid online anywhere.

The WooCommerce Facebook plugin is so ridiculously basic and terrible with next to no options.

Any ideas how to fix when your page isn't showing in the dropdown menu?

**Comment by nlksg** [comment] 2019-09-04 04:58
I also having the same problem.  Not all my page showing up in the fb-woo setup page.  I can't select the fb page which I want to link.  the page (fb.me/pinya.tech)
