### ISSUE TITLE
Oops, something went wrong.

### ISSUE THREAD

**Issue by monogios** [facebookincubator/facebook-for-woocommerce#1452] opened 2020-08-06 09:39 UTC
I have updated to the latest version, and when I try to re-connect as required, I’m getting this error message on final step:

Oops, something went wrong.
This may be because of a technical error that we’re working to get fixed. Try reloading this page.

**Comment by lgfogle** [comment] 2020-08-10 14:39
Hey @monogios,

Thanks for reaching out! I'm so sorry about the issues with reconnecting to Facebook. We're working with their team to resolve this problem and will be in touch with more information as soon as we can!

Thank you,
Lindsey

**Comment by lgfogle** [comment] 2020-08-14 15:49
Hey @monogios,

The Facebook team has released a few fixes on their end that may resolve this issue - could you please try again and let me know if that works? There are a few pending problems that they are still working hard to address, but wanted to see if the work they've already done has fixed the particular problem that was blocking your connection.

Thank you!
Lindsey

**Comment by lgfogle** [comment] 2020-08-18 16:39
Closing due to no response - @monogios please let us know if you're still encountering any connection issues on the latest version!

**Closed by lgfogle** 2020-08-18 16:39 UTC
Labels: bug

**Comment by gausie** [comment] 2020-08-25 16:04
I'm still getting this

**Comment by DaliborIlic** [comment] 2020-10-12 11:22
@lgfogle 
Not working with the latest update

**Comment by simonporter007** [comment] 2020-10-28 10:56
Hi @DaliborIlic,

As the plugin does not control this part of the connection process where the error is occurring, we're not best placed to assist. That said, if you could please reach out to our support team on the forums, they would be happy to take a closer look at your general setup to see if there is anything they can suggest that might be the cause!

You can reach out to the team here: https://wordpress.org/support/plugin/facebook-for-woocommerce/

Cheers,
