### ISSUE TITLE
debug wordpress

### ISSUE THREAD

**Issue by okhali** [facebookincubator/facebook-for-woocommerce#1659] opened 2020-10-27 17:40 UTC
[27-Oct-2020 17:04:14 UTC] PHP Parse error: syntax error, unexpected ')' in /home/thimqtrf/public_html/wp-content/plugins/facebook-for-woocommerce/includes/Products.php on line 1181

**Comment by okhali** [comment] 2020-10-27 17:41
I deactivate  this plugin, for now, I wait for your answer

**Comment by EzooDeen** [comment] 2020-10-28 01:41
The plugin have new updated 2.1.1 version. You can reinstall back the plugin. Download the updated version through woocommerce [https://woocommerce.com/products/facebook/](url) . Upload it back on your wordpress. It works fine for me.

**Comment by simonporter007** [comment] 2020-11-09 15:40
Duplicate of #1652

**Closed by simonporter007** 2020-11-09 15:40 UTC
