### ISSUE TITLE
Updating  product slows down website a lot

### ISSUE THREAD

**Issue by javismiles** [facebookincubator/facebook-for-woocommerce#121] opened 2017-10-29 21:03 UTC
Updating any product with your plugin active makes it go so so so so slow, 
but so slow that often it crashes with a 500 timeout error,
folks, these tasks should be asynchronous or in any case its crazy that your plugin slows down product updating so so so much

**Comment by mengyingdu** [comment] 2017-10-30 19:21
Hey @dmitridr, can you take a look at javismiles's issue ? I forward his detailed site information to you.

**Comment by dmitridr** [comment] 2017-11-01 01:30
Agree. Seems like a duplicate of #119. We'll see what we can do about the perf.

**Comment by mengyingdu** [comment] 2017-11-08 23:45
duplicate of #119

**Closed** 2018-03-11 21:05 UTC
Labels: duplicate, enhancement

**Comment by kkeennaa** [comment] 2018-05-24 05:42
Horrible plugin. My site loads so much slower because of it.
