### ISSUE TITLE
Unsupported Post Request Error

### ISSUE THREAD

**Issue by gchterry** [facebookincubator/facebook-for-woocommerce#62] opened 2017-09-29 09:10 UTC
Hi

Recently i see this error
How to solve?

Facebook extension error: Facebook for WooCommerce
Unsupported post request. Object with ID '1631440026867215' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api

**Comment by mengyingdu** [comment] 2017-09-29 20:50
Hi,

It seems you deleted this product (1631440026867215) and replaced it with (1597413983654617). Both of them are 荷花公道杯. Did you ever delete/copy same product?
I can't repro this error. 
Can you give us more information?

Thanks!

**Comment by dmitridr** [comment] 2017-10-03 00:41
Hello,

As @mengyingdu says, we will need more information to figure this out....
- Can you tell us your version #?
- Can you send a screenshot of the product for which you have this problem?

In general doing 'Force Resync' should clear out all old ids. Also, we recommend upgrading to 1.6.2 if you have not already, as the 'unsupported post request' was a much larger problem in older versions.

**Comment by lsigle** [comment] 2017-10-11 07:30
Hello @gchterry,

If you have either clicked "duplicate" in your product category or clicked the "copy to a new draft" inside a product's "edit page", you will see this error message. To fix the issue is very simple. You will just need to "Reset Facebook metadata" inside the new product listing before you click Update. You will find this link inside the "edit page" of the product you are receiving the error. It should be between the Product Tags and the Product Image on the right hand side. I have attached a couple images to help you locate.
![woocommerce error1](https://user-images.githubusercontent.com/18108649/31427211-57e2b08a-ae1b-11e7-9e42-653c9d702a16.JPG)
![woocommerce error](https://user-images.githubusercontent.com/18108649/31427212-57fb68b4-ae1b-11e7-8bb0-9268f9bf36b7.JPG)

Hope this helps,
Lissa

**Comment by dmitridr** [comment] 2017-10-31 20:37
Thanks @lsigle for the workaround! Closing this.

**Closed by dmitridr** 2017-10-31 20:37 UTC
Labels: question, workaround

**Comment by concretesocial** [comment] 2019-01-15 03:12
This is in effect a glorified 404 error. I think Facebook could have easily created a better message. We've write an article on this: https://concretesocial.io/blog/articles/facebook-unsupported-post-request/
