### ISSUE TITLE
integration tab not loading

### ISSUE THREAD

**Issue by glazebro** [facebookincubator/facebook-for-woocommerce#243] opened 2018-01-30 17:01 UTC
I could use a little help debugging. so I installed the plugin and it worked for a little bit. I synced some products to facebook but I don't think the whole process completed. That was yesterday. since then the integration tab in woocommerce will not load at all. I get the white screen of death. If I disable the plugin it will load. I have tried uninstalling and reinstalling the plugin but there must be some junk somewhere. I am unable to generate a log with any errors regarding the issue. any thoughts on what to do? I really want to use this plugin as I have on other sites and it is great when it works.

**Comment by mengyingdu** [comment] 2018-01-30 17:38
Hi @glazebro ,

Can you upload a screen shot, eg. what you have seen in your integration tab?
Your store url? Or facebook page url?

Thanks.

**Comment by glazebro** [comment] 2018-01-30 17:54
I am going to close this issue for now. I am realizing that I have some major issues and can't single it down to this plugin. Thanks for your reply

**Comment by glazebro** [comment] 2018-01-30 22:07
ok sorry to put this on hold. I think I do still have the persisting issue. what I thought was wrong earlier was with my theme and I have since fixed that issue and fairly easily. Here is a screenshot but it is basically just a 500 error. This is my facebook url https://business.facebook.com/Coupon-Deal-Explorer-145263292803286/shop/ 

you will see I had it working for a bit as there are products imported. The integration tab in woocommerce is just completely erroring at this point though. 
![screen shot 2018-01-30 at 4 06 29 pm](https://user-images.githubusercontent.com/6797173/35594105-a0a5f3cc-05d7-11e8-9cb3-f94e3b8ab483.png)

and here is the current url for my site http://couponDealExplorer.com

**Comment by glazebro** [comment] 2018-01-30 22:09
here is my status report from woocommerce as well `
### WordPress Environment ###

Home URL: http://coupondealexplorer.com
Site URL: http://coupondealexplorer.com
WC Version: 3.3.0
Log Directory Writable: ✔
WP Version: 4.9.2
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.1.13
PHP Post Max Size: 100 MB
PHP Time Limit: 280
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.58 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.0
WC Database Prefix: cde_
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.
Total Database Size: 85.25MB
Database Data Size: 65.38MB
Database Index Size: 19.87MB
cde_woocommerce_sessions: Data: 0.01MB + Index: 0.00MB
cde_woocommerce_api_keys: Data: 0.00MB + Index: 0.01MB
cde_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
cde_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
cde_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB
cde_woocommerce_order_itemmeta: Data: 0.00MB + Index: 0.00MB
cde_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB
cde_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
cde_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
cde_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB
cde_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
cde_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
cde_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
cde_woocommerce_log: Data: 0.00MB + Index: 0.00MB
cde_adsw_activities: Data: 0.02MB + Index: 0.00MB
cde_adsw_ali_meta: Data: 7.45MB + Index: 0.09MB
cde_ads_abandoned_emails: Data: 0.00MB + Index: 0.00MB
cde_ads_abandoned_flow: Data: 0.00MB + Index: 0.00MB
cde_ads_activities: Data: 0.00MB + Index: 0.00MB
cde_ads_ali_meta: Data: 0.00MB + Index: 0.00MB
cde_ads_attributes: Data: 0.00MB + Index: 0.00MB
cde_ads_categories: Data: 0.00MB + Index: 0.00MB
cde_ads_email_templates: Data: 0.00MB + Index: 0.00MB
cde_ads_orders_item: Data: 0.00MB + Index: 0.00MB
cde_ads_products: Data: 0.00MB + Index: 0.00MB
cde_ads_products_meta: Data: 0.00MB + Index: 0.00MB
cde_aiowps_events: Data: 0.00MB + Index: 0.00MB
cde_aiowps_failed_logins: Data: 0.27MB + Index: 0.07MB
cde_aiowps_global_meta: Data: 0.00MB + Index: 0.00MB
cde_aiowps_login_activity: Data: 0.00MB + Index: 0.00MB
cde_aiowps_login_lockdown: Data: 0.00MB + Index: 0.00MB
cde_aiowps_permanent_block: Data: 0.00MB + Index: 0.00MB
cde_commentmeta: Data: 0.64MB + Index: 0.48MB
cde_comments: Data: 1.74MB + Index: 0.48MB
cde_failed_jobs: Data: 0.00MB + Index: 0.00MB
cde_links: Data: 0.00MB + Index: 0.00MB
cde_mailchimp_carts: Data: 0.00MB + Index: 0.00MB
cde_options: Data: 9.05MB + Index: 2.88MB
cde_payment_discount: Data: 0.00MB + Index: 0.00MB
cde_payment_transaction: Data: 0.00MB + Index: 0.00MB
cde_postmeta: Data: 33.16MB + Index: 13.12MB
cde_posts: Data: 11.79MB + Index: 1.42MB
cde_queue: Data: 0.00MB + Index: 0.00MB
cde_revslider_css: Data: 0.09MB + Index: 0.00MB
cde_revslider_layer_animations: Data: 0.00MB + Index: 0.00MB
cde_revslider_navigations: Data: 0.00MB + Index: 0.00MB
cde_revslider_sliders: Data: 0.02MB + Index: 0.00MB
cde_revslider_slides: Data: 0.14MB + Index: 0.00MB
cde_revslider_static_slides: Data: 0.00MB + Index: 0.00MB
cde_termmeta: Data: 0.34MB + Index: 0.23MB
cde_terms: Data: 0.14MB + Index: 0.24MB
cde_term_relationships: Data: 0.29MB + Index: 0.63MB
cde_term_taxonomy: Data: 0.18MB + Index: 0.16MB
cde_usermeta: Data: 0.01MB + Index: 0.01MB
cde_users: Data: 0.00MB + Index: 0.01MB
cde_wc_download_log: Data: 0.00MB + Index: 0.00MB
cde_wc_webhooks: Data: 0.00MB + Index: 0.00MB
cde_yith_wcwl: Data: 0.00MB + Index: 0.00MB
cde_yith_wcwl_lists: Data: 0.00MB + Index: 0.01MB
cde_yoast_seo_links: Data: 0.02MB + Index: 0.01MB
cde_yoast_seo_meta: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

attachment: 2480
custom_css: 1
customize_changeset: 1
feature: 5
jetpack_migration: 2
mc4wp-form: 1
nav_menu_item: 125
nth_stblock: 4
oembed_cache: 2
page: 12
post: 7
product: 1113
product_variation: 14627
project: 1
revision: 1
shop_order: 1
wpcf7_contact_form: 2

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (33) ###

Query Monitor: by John Blackbourn – 2.17.0
Redux Framework: by Team Redux – 3.6.7.7
Ultimate Addons for Visual Composer: by Brainstorm Force – 3.16.12
AddToAny Share Buttons: by AddToAny – 1.7.23
AliDropship Woo Plugin: by Vitaly Kukin & Yaroslav Nevskiy & Pavel Shishkin – 0.7.2
All In One WP Security: by Tips and Tricks HQ
Peter Petreski
Ruhul
Ivy – 4.3.1

Contact Form 7: by Takayuki Miyoshi – 4.9.2
Enhanced E-commerce for Woocommerce store: by Tatvic – 1.2.1.2 – Not tested with the active version of WooCommerce
Envato Market: by Derek Herman – 1.0.0-RC2
Facebook for WooCommerce: by Facebook – 1.7.9 – Not tested with the active version of WooCommerce
Facebook Messenger for WordPress: by Brontobytes – 2.0
Features: by WooThemes – 1.5.0
Head & Footer Code: by Aleksandar Urosevic – 1.0.7
WPBakery Visual Composer: by Michael M - WPBakery.com – 5.1.1
MailChimp for WooCommerce: by MailChimp – 2.1.3 – Not tested with the active version of WooCommerce
MailChimp for WordPress: by ibericode – 4.1.14
MetaSlider: by Team Updraft – 3.6.8
Nexthemes Plugins: by Nexthemes – 1.4.3
PixelYourSite: by PixelYourSite – 5.1.0 – Not tested with the active version of WooCommerce
Plugins Garbage Collector: by Vladimir Garagulya – 0.10.3
Projects: by WooThemes – 1.5.0
Slider Revolution: by ThemePunch – 5.4.5.1
Testimonials: by WooThemes – 1.5.4
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.14.3

W3 Total Cache: by Frederick Townes – 0.9.6
WooCommerce PayPal Powered by Braintree Gateway: by WooCommerce – 2.1.0 – Not tested with the active version of WooCommerce
WooCommerce js cookie fix: by Rynaldo – 1.0 – Not tested with the active version of WooCommerce
WooCommerce Services: by Automattic – 1.11.0
WooCommerce: by Automattic – 3.3.0
Yoast SEO: by Team Yoast – 6.2
WP-Optimize: by David Anderson
Ruhani Rabin
Team Updraft – 2.1.1

YITH WooCommerce Compare: by YITHEMES – 2.2.3 – Not tested with the active version of WooCommerce
YITH WooCommerce Wishlist: by YITHEMES – 2.2.0 – Not tested with the active version of WooCommerce

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #147 - /
Cart: #148 - /cart/
Checkout: #149 - /checkout/
My account: #150 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: TheShopier Child
Version: 1.0.0
Author URL: http://nexthemes.com/
Child Theme: ✔
Parent Theme Name: TheShopier
Parent Theme Version: 1.4.3
Parent Theme Author URL: https://themeforest.net/user/themeyeti
WooCommerce Support: ✔

### Templates ###

Overrides: theshopier/archive-product.php version 2.0.0 is out of date. The core version is 3.3.0
theshopier/woocommerce/cart/cart-totals.php
theshopier/woocommerce/cart/cart.php version 3.1.0 is out of date. The core version is 3.3.0
theshopier/woocommerce/cart/cross-sells.php
theshopier/woocommerce/cart/mini-cart.php version 3.1.0 is out of date. The core version is 3.3.0
theshopier/woocommerce/cart/shipping-calculator.php version 2.0.8 is out of date. The core version is 3.2.0
theshopier/woocommerce/checkout/form-checkout.php
theshopier/woocommerce/checkout/form-coupon.php version 2.2 is out of date. The core version is 3.3.0
theshopier/woocommerce/checkout/form-login.php
theshopier/woocommerce/checkout/thankyou.php version 3.0.0 is out of date. The core version is 3.2.0
theshopier/woocommerce/content-product.php
theshopier/woocommerce/content-product_cat.php
theshopier/woocommerce/content-single-product.php
theshopier/woocommerce/content-widget-product.php version 2.5.0 is out of date. The core version is 3.3.0
theshopier/woocommerce/global/breadcrumb.php
theshopier/woocommerce/loop/add-to-cart.php version 3.0.0 is out of date. The core version is 3.3.0
theshopier/woocommerce/loop/loop-end.php
theshopier/woocommerce/loop/loop-start.php version 2.0.0 is out of date. The core version is 3.3.0
theshopier/woocommerce/loop/orderby.php version 2.2.0 is out of date. The core version is 3.3.0
theshopier/woocommerce/loop/pagination.php version 2.2.2 is out of date. The core version is 3.3.0
theshopier/woocommerce/loop/price.php
theshopier/woocommerce/loop/rating.php
theshopier/woocommerce/myaccount/my-account.php
theshopier/woocommerce/myaccount/navigation.php
theshopier/woocommerce/order/order-details-customer.php version 3.0.0 is out of date. The core version is 3.3.0
theshopier/woocommerce/order/order-details-item.php
theshopier/woocommerce/order/order-details.php version 3.0.0 is out of date. The core version is 3.3.0
theshopier/woocommerce/single-product/add-to-cart/external.php
theshopier/woocommerce/single-product/add-to-cart/grouped.php version 3.0.7 is out of date. The core version is 3.3.0
theshopier/woocommerce/single-product/add-to-cart/simple.php
theshopier/woocommerce/single-product/add-to-cart/variable.php
theshopier/woocommerce/single-product/product-image.php
theshopier/woocommerce/single-product/product-thumbnails.php
theshopier/woocommerce/single-product/related.php
theshopier/woocommerce/single-product/short-description.php version 1.6.4 is out of date. The core version is 3.3.0
theshopier/woocommerce/single-product/tabs/tabs.php
theshopier/woocommerce/single-product/title.php
theshopier/woocommerce/single-product/up-sells.php
theshopier/woocommerce/single-product.php

Outdated Templates: ❌Learn how to update
`

**Comment by glazebro** [comment] 2018-01-30 23:03
not sure what happended but it is now working

**Comment by mengyingdu** [comment] 2018-02-01 23:50
Hi @glazebro,

Sorry for the delayed response. I checked your site (i think you deactivate our plugin), your facebook page (there is no shop section). And your setting is shown as disabled in our db. I have some findings after investigating remote log from your site:

1. duplicate sku err (01/29): 
workaround:
If you duplicate a product that has been synced to FB there is definitely a problem, as mentioned in #62 you'd have to reset FB metadata after duplicating. I see you already tried that and the problem is with the first product, which is strange.

One potential workaround is that you could try 'Force Resync' after you are done saving all the products, which could resolve the issue, but could be annoying to do that every time after duplicating because resync takes a while.

2. permission error (01/30, 01/31):
This is a bug we just fixed in [v1.7.11](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.7.11) 

I would suggest you:
deactivate and delete old plugin -->
install and activate the latest one --> 
re-config your facebook setting (path to find it: woocommerce-> settings->integrations->facebook for woocommerce -> re-config facebook settings) -->
'get started' -> 
finish set-up

I see after try on 01/29 which ended up with error, you tried again. Thanks for your patience and offering us the detailed information to help us investigate. Let me know if you need more help! 

Thanks.

**Comment by dmitridr** [comment] 2018-03-23 00:33
I'm following up on older issues. Looks like there was no follow up here for a while. Please open a new issue on us if this is still a problem.

**Closed by dmitridr** 2018-03-23 00:33 UTC
