### ISSUE TITLE
Changed price to display including taxes - Facebook shop displays wrong prices

### ISSUE THREAD

**Issue by kevberot** [facebookincubator/facebook-for-woocommerce#462] opened 2018-05-04 00:05 UTC
Hey guys,

We recently changed our site's woocommerce settings to display the prices of our products inclusive of tax and we forced a resync with facebook to update the prices.

For some reason some products updated the prices correctly and some others didn't, they still show the price non inclusive of tax (even though the price is displaying correctly on the website). 

url:  www.campingplus.com.au
facebook: https://www.facebook.com/campingplus.australia/

Can you helps us figure out if we re missing something here? 

Thank you!

**Comment by sammul** [comment] 2018-05-04 05:51
@kevberot Are you using any plugin for the pricing? I randomly checked one product: https://campingplus.com.au/redback-work-boots-uabk/?attribute_pa_size=9-7 it's saying $120, but when I add to cart, it becomes $109.
<img width="1102" alt="screen shot 2018-05-03 at 10 51 20 pm" src="https://user-images.githubusercontent.com/4251631/39614412-88408dba-4f24-11e8-91a1-0b2036d3f5b8.png">

**Comment by dmitridr** [comment] 2018-05-07 22:42
Any updates here? I think @sammul is on to something there. If some plugin is changing the display price it could be affecting the price the plugin pulls to FB. If you can identify the plugin : disable it temporarily then do a `Force Resync`, it should fix the price discrepancy.

If that still doesn't help, could you link to us an example of the product that has the discrepancy and we can take a look?

The product @sammul linked seems strange since it says [120.00 on FB](https://www.facebook.com/commerce/products/1920678364671785/) and on your site but 109 in the cart, so I'm not sure it's one of the problematic ones or not...?

**Comment by dmitridr** [comment] 2018-06-22 21:14
Closing as there has not been a reply for a while here. Please open a new issue on us and reference this one if the issue is still occurring and you'd like to continue discussion!

**Closed by dmitridr** 2018-06-22 21:14 UTC
Labels: compatibility
