### ISSUE TITLE
Facebook Pixel Plugin disables backend page search functionality

### ISSUE THREAD

**Issue by iwakun** [facebookincubator/facebook-for-woocommerce#354] opened 2018-03-27 16:22 UTC
For some reason, the native Wordpress "Search Pages" functionality on the backend "Pages" stops working when this plugin is activated.

**Comment by mengyingdu** [comment] 2018-03-27 23:21
Hi @iwakun ,

Can you follow the support section of the front page (readme) when you open an issue? This can help us quickly jump in and help you figure out the problems.

Thanks.

**Comment by ddzieduch** [comment] 2018-04-16 10:55
At the end of search result add all elements. Which means that if there is no searched element, the list is filled with all elements.

Wordpress 4.9.5

**Comment by mengyingdu** [comment] 2018-05-07 16:27
Hi @iwakun @ddzieduch ,

What's your store url and fb page?
Can u follow the instruction of support section to describe your problems with more details?
Screenshots will help a lot.

Thanks.

**Comment by ddzieduch** [comment] 2018-05-07 17:10
@mengyingdu 

The problem is with every search functionality in media library, list of pages and posts, and in front end.

I don't use WooCommerce.

Symptoms: 
Login to Wordpress dashboard, go to Media, try search something "jkdjfkdjfkdjkf", all items are displayed. Try again with disabled Facebook Pixel 1.6.0 and 1.7.11 plugin, no search result is displayed.

**Comment by dmitridr** [comment] 2018-05-09 00:48
Hi,

We no longer support the Facebook Pixel plugin as part of Facebook for WooCommerce (we split it off). But there is no open source repository for it yet. I will forward your concern to the team that manages that plugin and will update if there is a fix.

**Comment by ddzieduch** [comment] 2018-05-24 20:36
Do you already have a solution? It is annoying to disable the plugin every time to use the search engine. Editors can not do this.

**Comment by jwlsinx** [comment] 2018-05-24 22:58
A new version of the plugin has been uploaded. You will need to download it again from [Events Manager](https://business.facebook.com/events_manager/).

The plugin name was changed recently so you may need to delete the old plugin (otherwise you will have two).

**Comment by dmitridr** [comment] 2018-05-31 22:01
Closing as this seems to be resolved.

**Closed by dmitridr** 2018-05-31 22:01 UTC
Labels: bug
