### ISSUE TITLE
Can not sync products out of stock

### ISSUE THREAD

**Issue by abbaco** [facebookincubator/facebook-for-woocommerce#1790] opened 2021-03-02 16:00 UTC
Hello, when I set an item as "out of stock" in woocommerce, the product seems doesn't sync to facebook and the facebook entry still has the "in_stock" availability on facebook store. 

How can I make that woocommerce change the availability of a facebook product when Woocommerce reach out of stock? I saw in the Facebook for Woocommerce documentation that out of stock items are not sync. 

Thanks.

**Comment by budzanowski** [comment] 2021-03-12 04:42
Hi @abbaco,

I have tested the "out of stock" functionality and it looks like it works correctly. I have tested the following scenarios:
1. Manual changing from "in stock" to "out of stock" and in the other direction.
2. Using "Enable stock management at product level" and changing stock from 1 to 0 manually.
3. Doing a purchase that reduces the stock to 0.

In all of those scenarios, the Facebook catalog has correctly reported the "in stock" or "out of stock" status.

If you are experiencing your issue in another scenario, please explain in detail the steps you take to reproduce the issue.
Another thing that could be useful is doing a conflict check with your plugins: https://docs.woocommerce.com/document/how-to-test-for-conflicts/ are you using and stock and inventory management plugins?

**Comment by budzanowski** [comment] 2021-03-15 10:22
Closing this for now. Please reopen if the problem persists.

**Closed by budzanowski** 2021-03-15 10:22 UTC
Labels: needs investigation
