### ISSUE TITLE
API key is no longer valid

### ISSUE THREAD

**Issue by Sonehvk** [facebookincubator/facebook-for-woocommerce#96] opened 2017-10-18 16:39 UTC
**Your API key is no longer valid. Please click "Re-configure Facebook Settings > Advanced Options > Delete Settings" and setup Facebook for WooCommerce again.**

Hi, 
I have this error message and I find no solution.
Do you have any idea?
Facebook for Woocommerce ver. 1.6.4
Woocommerce ver 3.1.2
Wordpress ver. 4.8.2

**Comment by dmitridr** [comment] 2017-10-20 00:27
Hello,

This usually happens if you have reset your FB password recently. If you follow the steps described in the error message and delete the plugin and set up again, you can get a new API key. ... Are you not seeing the 'Reconfigure Facebook Settings' button when the error appears?

I realize this is a hassle, which is why we are working on building a way to do this without having to delete everything using a button to get a new API key, but that will not be ready for some time yet.

**Comment by dmitridr** [comment] 2017-10-31 22:56
Going to keep this open for now and close when our updated solution is ready (ETA 1-2 months). We're prioritizing more serious bugs for now which do not have any workaround.

**Comment by MilkmanWes** [comment] 2017-11-29 15:16
> Facebook extension error: Facebook for WooCommerce
Error validating access token: The session has been invalidated because the user changed their password or Facebook has changed the session for security reasons.

Reading this issue and the comment by @dmitridr I think this may be what is affecting my wifes shop. Can you tell me if this is indeed the same issue? We do not see the reconfigure FB button and my wife has removed and reinstalled the extension and the error has not changed.

If this is not another symptom of the same issue discussed here let me know and I will start a new issue.

**Comment by mengyingdu** [comment] 2017-12-04 01:25
Hi @MilkmanWes ,

It seems similar to this issue. Are you not seeing the 'Reconfigure Facebook Settings' button when the error appears? Have you ever actually change your FB password?
If you can tell us your Facebook Page or website url , it helps me check your remote log.

Thanks.

**Comment by mengyingdu** [comment] 2018-01-05 21:44
Hi, 
We has fixes for API invalid issues in [v1.7.4](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.7.4). Can you upgrade and try it?

**Comment by Saul-I** [comment] 2018-01-18 08:14
Hi,
Still having problem with v.17.5 and 17.6 !

**Comment by mengyingdu** [comment] 2018-01-18 21:24
Hi @Saul-I ,

Can you tell us your shop url or Facebook page ? I can look into our remote log to see what's wrong with your site.

Thanks.

**Comment by dmitridr** [comment] 2018-03-23 00:06
Closing this because there has been a long time since we've received a reply, please open a new issue on us if this is still a problem. 

This could also be caused by incorrect business permissions being set on the page. You must be an Admin on the page not just a Business Admin.

**Closed by dmitridr** 2018-03-23 00:06 UTC
Labels: bug, workaround

**Comment by morethanwords1980** [comment] 2018-06-08 08:46
Hi I just have a question about this issue: if I deactivate and reactivate the plugin through the guided procedure, won't it erase all the previous products in the catalogue, including campaigns and links to the Facebook shop page? Thank you!
