### ISSUE TITLE
Purchase Event Not Firing - Woocommerce

### ISSUE THREAD

**Issue by efsCuevas** [facebookincubator/facebook-for-woocommerce#592] opened 2018-07-24 17:04 UTC
Hello,

I've been trying to make the purchase event work for a couple of weeks and I don't seem to see where the problem is. Instead I created a customized purchase event, which is not the perfect solution.

![image](https://user-images.githubusercontent.com/22932878/43154163-aa49e7d2-8f73-11e8-8321-33a646505ef0.png)

The rest of events are working properly. I tried deactivating & deleting the plugin, and reinstalling but nothing changes.

Tried a purchase test a while ago and this is what it's being shown on Facebook Pixel Helper

![image](https://user-images.githubusercontent.com/22932878/43154343-5809d8be-8f74-11e8-92df-306ece6c0914.png)

Website is https://dvalentina.com

I would appreciate some help here.

Thank you very much!
Gonzalo

**Comment by gervet** [comment] 2018-07-24 20:47
In the last Update, the products syncing and the purchase event are not working. :(

**Comment by mengyingdu** [comment] 2018-07-24 21:38
## Automated Support Message

Hello,

Thanks for your interest in our plugin!

If your issue is a feature request or feedback for the developers, reply with `Feature Request` or `Feedback`.
If you are a developer or have a question for the developers related to code, reply with `Developer Question`.
If you are running ads with us, include `Advertiser` in your reply.

If you have encountered a bug or a problem with the plugin, the steps below contain information to help you resolve the issue yourself and provide us information we need to help you with your problem.

## Search Existing Issues

**First, please [search our issues](https://github.com/facebookincubator/facebook-for-woocommerce/issues?q=) to see if your problem has been reported before.**
There may already be a workaround or a solution to your problem. You can search our issues using [the search bar near the top of our issues page](https://github.com/facebookincubator/facebook-for-woocommerce/issues?q=); be sure to search both _open_ and _closed_ issues.
If you do find a similar issue, leave a comment on that issue and close this one. Your comment helps us prioritize which existing issues are important and urgent.

## Common Resolution Methods

**If you are experiencing a problem or bug and have not found any similar issue, please try the following:**

* Upgrade to the latest version of the plugin.
* Try to `Resync` products using the button on the plugin config page
* Reset the plugin by selecting `Reconfigure > Advanced Options > Delete`, and setting up this plugin again.
* Try to deactivate other plugins that you think may be interfering, then reset and set up again.

## Necessary Information

**If the above steps did not help, please provide the following information in your next comment in order for us to debug your problem:**

* WooCommerce version
* WordPress version
* Plugin version (please note: we only support up-to-date versions of the plugin)
* A screenshot of where you see the problem (for example: if it is on Facebook, a screenshot of Facebook, if it is on WooCommerce, a screenshot of WooCommerce. If it is in multiple places, multiple screenshots.)
* The URL of your website
* The URL of your page
* The URL(s) of where you took your screenshot(s)
* (If applicable) Detailed steps you took in order to see the problem

Please include `Debug Ready` in your reply so our automated system can flag your issue for manual review. Please note that due to a high volume of issues, we may not be able to respond immediately.

Thanks for your patience,
The Facebook Dev Team (@mengyingdu, @dmitridr, @sammul, @jieminz22)

**Comment by efsCuevas** [comment] 2018-07-25 10:57
Thanks for your reply.
Please find below the requested information:

WooCommerce version: 3.4.3
WordPress version: 4.9.7
Plugin version (please note: we only support up-to-date versions of the plugin): 1.9.2
A screenshot of where you see the problem (for example: if it is on Facebook, a screenshot of Facebook, if it is on WooCommerce, a screenshot of WooCommerce. If it is in multiple places, multiple screenshots.) - Screenshots in the thread above
The URL of your website - https://dvalentina.com
The URL of your page - https://business.facebook.com/dvalentinajewelry/
The URL(s) of where you took your screenshot(s) - https://dvalentina.com/checkout/order-received/....
(If applicable) Detailed steps you took in order to see the problem - in the thread above

Debug Ready

**Comment by mengyingdu** [comment] 2018-07-26 21:19
@efsCuevas 

I found permission error from your site so that you failed to delete your old catalog (which cause you unable to sync later because the feed is also belong to the old / dead catalog)

One potential reason is your page is business page and connected with business manager. Can u disconnect them and try from scratch? 

delete settings --> get started

Let me know if it works.

**Comment by efsCuevas** [comment] 2018-07-27 09:34
@mengyingdu 

Thanks a lot for your reply. I performed what you mentioned and no changes within the purchase event.

![image](https://user-images.githubusercontent.com/22932878/43313630-e7aa3964-9190-11e8-9a04-0c29e5ac3e79.png)

FYI - just updated woocommerce to version 3.4.4

Looking forward to your reply.

Best,
Gonzalo

**Comment by mengyingdu** [comment] 2018-07-28 00:39
@efsCuevas 
It looks weird since other events fired correctly. 
If you look at these [lines](https://github.com/facebookincubator/facebook-for-woocommerce/blob/master/facebook-commerce-events-tracker.php#L45-L48), we hooked on thank you page and gateway purchase.

1. What else plugins are you using?
2. When you tested it as in the screenshot, which purchase method was used?
3. Did you customized your thank you page?

**Comment by efsCuevas** [comment] 2018-07-28 07:13
@mengyingdu  thanks for your reply

This is the list of plugins that are currently active:

Advanced Custom Fields PRO
Advanced Order Export For WooCommerce
All In One SEO Pack
ATUM Inventory Management for WooCommerce
Cookie Notice
Duplicate Post
Facebook for WooCommerce
GeoTargeting Lite
MailChimp for WooCommerce
Product Sales Report for WooCommerce
Really Simple SSL
StorePep WooCommerce App Integration
WooCommerce
WooCommerce Checkout Field Editor
WooCommerce Email Customizer with Drag and Drop Email Builder
WooCommerce Google Analytics Integration
WooCommerce Multilingual
WooCommerce PayPal Checkout Gateway
WooCommerce SSL Seal
WooCommerce Stripe Gateway
Wordfence Security
WP Fastest Cache
WP Live Chat Support
WP Live Chat Support - Mobile and Desktop App
WP Live Chat Support Pro
WP Mail Logging
WPFront Notification Bar
WPML Multilingual CMS
WPML String Translation
WPML Translation Management

Regarding the purchase method, I tried both stripe and paypal with the same result.

As for the Thank You, this was customized - maybe this is where the issue lies.

Thanks again for looking into this.

Best,
Gonzalo

**Comment by dmitridr** [comment] 2018-08-06 23:45
Hi @efsCuevas ,

Thanks for the extra info. If you'd want to help us try further, you can try de-activating all of the above plugins which are related to purchase and testing a purchase to see if it works. But I suspect the problem is in the custom thank you page...

Can you go into detail about how it was customized? Are you using a plugin to customize the thank you page? Is there a page rendered right before the thank you page is rendered when the user purchases?

As @mengyingdu mentioned we only fire the event on `woocommerce_thankyou` so if your custom thank you page does not trigger the event `woocommerce_thankyou` this is why the purchase is not firing.

--- 

That's one possibility, the other possibility I can see is that we are not firing the event because we are falsely seeing a duplicate event. If you are familiar with the wordpress plugin editor, could you try editing the plugin and removing [these lines](https://github.com/facebookincubator/facebook-for-woocommerce/blob/v1.9.2/facebook-commerce-events-tracker.php#L294-L297), then checking the purchase event again?

**Comment by efsCuevas** [comment] 2018-08-29 10:58
Hi @dmitridr 

Sorry for the late response.

Regarding the thank you page, no plugin was used to customize it and, after speaking to the developer, there is no page rendered before the thank you page is rendered.

"As @mengyingdu mentioned we only fire the event on woocommerce_thankyou so if your custom thank you page does not trigger the event woocommerce_thankyou this is why the purchase is not firing." - How can I check this?

In the meanwhile I tried the second possibility and the purchase event and unfortunately the purchase event is not working

![image](https://user-images.githubusercontent.com/22932878/44783571-0eafb480-ab8b-11e8-8fda-ac47af259be6.png)

Please let me know how I can check if the page triggers the event woocommerce_thankyou

Thanks.

Best,
Gonzalo

**Comment by mengyingdu** [comment] 2018-09-11 14:54
Hi @efsCuevas ,

When I went to your site, I found you upgrade from 1.9.2 to 1.9.5 now.

I tested 'add to cart' and 'initiate checkout'

Difference from your screen shot: initiate checkout fire correctly
<img width="349" alt="screen shot 2018-09-11 at 7 52 23 am" src="https://user-images.githubusercontent.com/24535640/45368166-d1d6bb00-b597-11e8-8c1c-c567a103bf51.png">

Can you double check purchase still has problem after you upgrade? I can't test purchase

**Comment by efsCuevas** [comment] 2018-09-11 15:04
Hi @mengyingdu,

Thanks for your reply.
Unfortunately the purchase event is not firing

![image](https://user-images.githubusercontent.com/22932878/45368791-be9e0c80-b5e4-11e8-8d5a-9db0c3a17735.png)

Looking forward to your feedback,
Gonzalo

**Comment by efsCuevas** [comment] 2018-09-18 12:01
Hi @mengyingdu 

Double checking that you received this.

Best,
Gonzalo

**Comment by mengyingdu** [comment] 2018-09-18 21:53
1. Can you try to find your local log file ? I didn't find any log from your site related to this issue.
2. Also, can you set WP_DEBUG = true and WP_DEBUG_DISPLAY = false in your server config. Then add this line : 
WC_Facebookcommerce_Utils::log('debug -- purchase event fired '); 
after [this line](https://github.com/facebookincubator/facebook-for-woocommerce/blob/master/facebook-commerce-events-tracker.php#L358)
3. Can you confirm whether it can log into your log file?

**Comment by efsCuevas** [comment] 2018-09-18 22:41
Hi @mengyingdu 

1. The local log files can be found here: https://drive.google.com/open?id=1ObiO1c1xuQmFdYOHv3NmcqB_vDmC7vk8
2. Done
3. Do you mean to give you access to the log file in our server?

Thanks
Gonzalo

**Comment by efsCuevas** [comment] 2018-09-18 22:44
Also, I'm getting this message on the dashboard

![image](https://user-images.githubusercontent.com/22932878/45720597-1ae4cb80-bba5-11e8-8f16-453cf987ab8a.png)

**Comment by mengyingdu** [comment] 2018-09-19 02:26
Also, can  you try another difference checkout approach? 
i found you installed paypal express.

**Comment by efsCuevas** [comment] 2018-09-19 07:44
@mengyingdu tried paypal express and no purchase event triggered unfortunately

![image](https://user-images.githubusercontent.com/22932878/45737988-8b183f00-bbef-11e8-8ade-12c83b0dc074.png)

Here you have the latest debug.log file - maybe there's something there that needs to be addressed
https://drive.google.com/open?id=1ObiO1c1xuQmFdYOHv3NmcqB_vDmC7vk8

**Comment by efsCuevas** [comment] 2018-09-28 10:59
Hi @mengyingdu 

Did you have time to look into this?

Thanks
Gonzalo

**Comment by efsCuevas** [comment] 2018-10-11 09:55
Hi @mengyingdu 

We would really appreciate your help here.
We contacted two different developers and can't find the problem.

Thanks
Gonzalo

**Comment by mengyingdu** [comment] 2018-10-17 22:16
I didn't find anything related to facebook-for-woocommerce from your log. 
Not sure whether it helps, but most error/warnings is from 
* plugins/wpfront-notification-bar
* WordPress database error from Slider Revolution
* shipping_first_name was called incorrectly. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::do_wc_ajax, do_action('wc_ajax_checkout'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::checkout, WC_Checkout->process_checkout, WC_Checkout->process_order_payment, WC_Gateway_PPEC_With_SPB->process_payment, WC_Gateway_PPEC->process_payment, WC_Gateway_PPEC_Checkout_Handler->do_payment, WC_Gateway_PPEC_Checkout_Handler->handle_payment_response, WC_Order->payment_complete, WC_Order->save, WC_Order->status_transition, do_action('woocommerce_order_status_processing'), WP_Hook->do_action, WP_Hook->apply_filters, PacklinkPlugin->hook_woocommerce_order_status_processing, PacklinkPlugin->exportOrder, PacklinkPlugin->getShipmentsDatas, WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong


The third one seems to cause your problem. @efsCuevas

**Comment by efsCuevas** [comment] 2018-11-14 11:19
@mengyingdu Thanks for your help here.

We finally fixed it - you were right as the third cause was the problem.

Best,
Gonzalo

**Comment by lgfogle** [comment] 2020-04-06 23:17
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!

**Closed by lgfogle** 2020-04-06 23:17 UTC
Labels: Automated : Multiple Reports, bug
