### ISSUE TITLE
Several folks finding oversized wp_options value wc_facebook_google_product_categories

### ISSUE THREAD

**Issue by seanconklin** [facebookincubator/facebook-for-woocommerce#1708] opened 2020-11-20 17:23 UTC
Referencing: https://wordpress.org/support/topic/wp_options-wc_facebook_google_product_categories/

This seems like a top priority issue.

This auto-loading row in wp_options `wc_facebook_google_product_categories` is critically oversized and can crash smaller environments. Typical size is < 100k chars and this row is ~700k chars.

**Comment by limestreet** [comment] 2020-11-25 07:41
Hi,
I think the simple solution for that would be to use `update_option( self::OPTION_GOOGLE_PRODUCT_CATEGORIES, $categories, 'no' )` instead of `update_option( self::OPTION_GOOGLE_PRODUCT_CATEGORIES, $categories )` here -> https://github.com/facebookincubator/facebook-for-woocommerce/blob/master/includes/Admin/Google_Product_Category_Field.php#L67

In other words just disable autoloading of that option.

I think option size itself is not the issue here, the problem is the option loaded on every page call. A link to quite good article about that -> https://kinsta.com/knowledgebase/wp-options-autoloaded-data/

I hope that helps a bit to fix the issue

Best,
Patryk

**Comment by seanconklin** [comment] 2020-11-25 22:49
That Kinsta article is an excellent read. I appreciate how they quantify "...ideally, you want [combined autoload values] to be between 300 KB to 1MB".

Autoload should be ON for any options used on all or nearly all front end pages, as this preloading saves query volume. Autoload should be OFF for any options used on few pages specifically for cron or the back end administrative area. I can't be sure which is the best for this specific cache, but I'm sure it will be apparent to the plugin developer.

Size of the option is another matter entirely. I rarely find options over 100k chars, and when I do it's a strong indication the plugin is doing things inefficiently. Oversized values can cause site migration issues such as max_allowed_packet, lead to query performance issues, and contribute to PHP errors related to memory_limit. All good reasons to keep the size down or split into multiple options if necessary.

**Comment by limestreet** [comment] 2020-11-26 06:59
From reading the code I see the option is designed to be updated once a week - so no reason for "autoloading".
The entirely new topic is that the data is stored twice:
- in option itself
- in transient (for a week)

So it's not good...
Possible solutions would be to:
- just use transients
- just use option

If updates need to be done on schedule - then there is cron available -> https://developer.wordpress.org/plugins/cron/

**Comment by GeoJunkie** [comment] 2021-01-15 13:32
Just adding a note that there are several folks impacted by this issue on the WordPress.org forum: https://wordpress.org/support/topic/memory-limit-reached-after-last-update/

A workaround being used is to rename the `fb_google_category_to_attribute_mapping.json`, which prevents the memory issues, but may have other unseen impacts.

**Comment by webhouse-dev** [comment] 2021-02-13 17:36
Any updates on optimisation of this table?

**Comment by DanielRuf** [comment] 2021-02-18 13:11
My two cents from https://wordpress.org/support/topic/memory-limit-reached-after-last-update/page/2/#post-14068573

I suggest to convert the JSON file to a CSV file and parse it line by line which is the most memory-efficient solution.

**Comment by lewebsimple** [comment] 2021-02-18 13:20
How about a custom database table ?

**Comment by haszari** [comment] 2021-03-23 03:04
Thanks for reporting this, and thanks to @limestreet for the insight. 

As of v2.3.3 the option is no longer autoloaded 🎉, so I'm closing this issue. See #1791 for details of the fix. 

If this issue is still affecting your store, please [log a new issue](https://github.com/facebookincubator/facebook-for-woocommerce/issues/new/choose) with details of how to reproduce the bug.

**Closed by haszari** 2021-03-23 03:04 UTC
Labels: feature: product sync, google product categories

**Comment by AmeenJalali** [comment] 2021-11-29 08:59
@haszari 
We're using the latest version of "Facebook for WooCommerce", so can I delete all Facebook autoload data?

SELECT * 
FROM `wp_options` 
WHERE `autoload` = 'yes'
AND `option_name` LIKE '%wc_facebook_google_product_categories%'

Is it safe to use that?
