### ISSUE TITLE
woocommerce products not uploading to facebook + event error

### ISSUE THREAD

**Issue by tekraid** [facebookincubator/facebook-for-woocommerce#514] opened 2018-05-30 01:03 UTC
hi, would like some help on my page [metabackpack.com](https://metabackpack.com/). I have the facebook for woocommerce plugin but the products do not seem to be uploading into the facebook catalog. my facebook pixel is 

Meta Backpack's Pixel
Pixel ID: 1973855296204717

My pixel seems to be firing correctly on my site.

Here is the errors that its showing: 

Events
Missing content_type parameter from "ViewContent" in Meta Backpack's Pixel
Required parameter content_type is missing from more than 20% of ViewContent events in the last day
To fix this:
Make sure the pixel code is installed correctly in your website
Make sure the event is sending all the required params: content_ids, content_type. Learn more.
For Facebook Pixel you can download the Facebook Pixel Helper for Google Chrome to debug your pixel fires or view parameters from latest ViewContent events in Events Manager
Missing content_ids or contents parameter from "ViewContent" in Meta Backpack's Pixel
Required parameter content_ids or contents is missing from more than 20% of ViewContent events in the last day
To fix this:
Make sure the pixel code is installed correctly in your website
Make sure the event is sending all the required params: content_ids, content_type. Learn more.
For Facebook Pixel you can download the Facebook Pixel Helper for Google Chrome to debug your pixel fires or view parameters from latest ViewContent events in Events Manager
Missing "AddToCart, Purchase, ViewContent" events in Meta Backpack's Pixel
Data Sources
Your Data Feed File Can't Be Empty in Initial product sync from WooCommerce. DO NOT DELETE.

**Comment by RainingJing** [comment] 2018-05-30 01:32
[Note : This is an Automated Message]

Hello,

Thanks for your interest in our plugin!
Due to a high volume of issues we may not be able to get to yours immediately.

If this is a feature request, or feedback, please reply with
`Feature Request` or `Feedback` and it will be categorized accordingly, and
we will read it and reply when we can.

If you are experiencing problems, read on.

First. Please check to see if your issue is not a duplicate of another one.
To search our issues, use the search feature at the top of the GitHub issues page.
We have nearly 500 existing and past issues, so it is fairly likely someone else has already reported your problem.
If you do find a relevant issue, please comment in that issue, and close this one.
It helps us prioritize issues to tackle by looking at the number of people with the same problem.

If your issue is unique, and you are sure, then read on.
We require the following information in order to help you:
- WooCommerce Version
- Wordpress Version
- Plugin Version. Please Note that we do not support outdated versions of the plugin.
- A Screenshot of where you see the problem. If it is on Facebook, a screenshot of Facebook,
if it is on WooCommerce, a screenshot of WooCommerce. If it is in multiple places, multiple screenshots.
- The URL of your website.
- The URL of your page.
- The URL(s) where you took your screenshot(s).
- (If applicable) Detailed steps you took in order to see the problem.

Please be advised, it may take us some time to get to your issue.
In the meantime, below are generic approaches you can take that may solve the issue :
- Upgrade to the latest version.
- Force Resync
- Reset the plugin using `Reconfigure > Advanced Options > Delete` and setup again.
- Try to deactivate other plugins which you think could be interfering and repeating the above.

When you have the above data for us, please include
`Debug Ready` in your reply. We will get to it and debug it as soon as we can.

Thanks for your patience,
Dev Team (@mengyingdu, @sammul, @jieminz22, @dmitridr)

**Comment by angelo-msg** [comment] 2018-08-10 11:16
Hi, it seems I have the same problem... my products are external producs though (amazon affiliate links)

**Comment by jieminz22** [comment] 2018-09-10 17:46
## Automated Support Message - Issue Closed

Hello,

Because it has been 30 days since this issue was updated and you have not included `Debug Ready` in your reply, our automated system will now close your issue.
If you are still having this problem, please open a new issue and reference this one.

For more information on our response times and support policy, visit [Facebook Support on GitHub](https://github.com/facebookincubator/facebook-for-woocommerce/wiki/Facebook-Support-on-GitHub).

Thank you,
The Facebook Dev Team

**Closed by jieminz22** 2018-09-10 17:46 UTC
Labels: Automated : Multiple Reports, Automated : Need More Info
