### ISSUE TITLE
HTML Tags Stripped from Product Description

### ISSUE THREAD

**Issue by nitinver12** [facebookincubator/facebook-for-woocommerce#439] opened 2018-04-27 07:08 UTC
product description in facebook not showing html tags like p ,div etc which is added in product description in woocommerce product page .how to show tags in facebook description .
![screenshot](https://user-images.githubusercontent.com/38779156/39354961-7bda359e-4a29-11e8-86b9-5e418630680c.png)

**Comment by milosmili** [comment] 2018-04-27 14:14
About: Facebook For WooCommerce WordPress plugin. 
Tested with version 1.8.3

Current version: 1.8.6: installed but causing HTPP 500 Error. Removed and re-installed 1.8.3.

URL to download: https://woocommerce.com/products/facebook/

We decided to write this out of frustration due to inconsistent, slow, and inadequate plug-in support.

The plugin is supposed to facilitate and ease transfer of your Woo products to your FB page. It is using FB Pixel technology so that every product and each product’s variation & related image is properly identified and assigned a FB URL.

Prerequisites:
A.	Create a business FB page : https://www.facebook.com/pages/create
B.	You have to create FB Pixel : https://www.facebook.com/business/help/314143995668266
C.	Create a FB business catalog : https://www.facebook.com/business/help/1397294963910848
D.	Check if all your products’ attributes & variations are properly set and assigned.

NOTE# 1: We’d suggest doing a FULL backup of your site that before you start.

1.	Login to FB
2.	In your WP admin area select WooCommerce -> Settings -> Integration
3.	Select Configure (Reconfigure) Facebook Settings
4.	Select Facebook Page you wish your products to show up
5.	Select Facebook Pixel
6.	Once steps 5 & 6 are done your FB will start transferring your FB catalog will start populating with ALL your products

NOTE #2: Depending of the number of products you have it may take anywhere from few hours to several days and perhaps weeks. The plugin does not provide any info or indication about the transfer speed, no indication on transfer progress, no alerts when transfer is done, success or failure.


NOTE #3: Most probably the initial transfer won’t include all of your products and/or all of your products’ variations & images. Also most probably the transfer might got stuck somewhere between FB and your site.

If this happens NEVER EVER select FORCE PRODUCT RESYNC as it will re-sync ALL your products and then you might start living in the Agony City: it might cause MySQL DB errors, http 500 Error, data corruption, and perhaps your ISP might think you’re spamming. The plugin is hard on consumption and sucks a considerable amount of GB for the transfer.

Instead of using Force Product Resync select ADVANCED OPTIONS -> DELETE SETTINGS. This will clear the current plugin settings and you should start from the step #3. Repeat as many times as you need. If after few re-configurations you still not getting all of your products with all variations & images proceed to step 7.

7.	Now there is no other option but to update each of your products. Slightly change a text, or add additional image and click on UPDATE button. This will transfer all of your product’s data again to your FB page. The new transfer might take between few minutes or hours and is often followed by the following:

Is it really is being processed? Well, Yes and No

8.	How To Test If Transfer Is Completed

8.1.	Login to your FB account an hour after completing steps 1. To 6. 
8.2.	Open your FB page where your products are listed
8.3.	Click on any product link
8.4.	Do you see the above product’s info? If you do not, meaning your product is 100% transferred
8.5.	If you DO see it:
8.5.1.	Open another Web browser, like Firefox
8.5.2.	Copy and paste your FB page URL from the other browser (where you’ re currently logged in) but DO NOT login to your FB account
8.5.3.	Click on the same product
8.5.4.	Do you see the above product’s info? Most probably you won’t …so that means your product is being processed 100%.

Finale Note: The plugin requires extensive amount of effort and time in order to have all set and executed. However it facilitates transfer to FB and thus transfer to your Instagram profile as well.

Check it out: https://www.facebook.com/pg/Topphonestuff-479032609180608/shop

Our Web Site: https://TopPhoneStuff.com/

We certainly hope this will help someone!

Milos, Sandra, Gabriel, Alexander and many other hard-working gals & guys @ TopPhoneStuff.Com

**Comment by mengyingdu** [comment] 2018-05-06 18:39
Hi @nitinver12 ,

We will clean up html tag when generate product data, which is by design. The reason is, if any advertiser wants to create Ads after setting up, the dynamic product ads will automatically extract your product description. However, DPA is not allowed to have html tag in description.

Thanks.

**Comment by mengyingdu** [comment] 2018-05-06 18:41
Hi @milosmili ,

Really appreciate your detailed feedback. We are iterating on improvement.
Thanks for understanding and using our plugin.

**Comment by dmitridr** [comment] 2018-06-13 21:46
@milosmili This is a great guide. If you haven't already, I encourage you to post it in a separate issue and we can tag it for visibility of other users.

@nitinver12 We strip HTML formatting because the FB shop does not support it either for ads as @mengyingdu said or for shops. There should be at least one other open issue on this, if I find it I will link it here. I've marked this as a feature request but chances are we will not support tags. We do provide a field `Facebook Description` in WooCommerce where you can add a custom description for your product on Facebook, in case the formatting is not to your liking and you wish to adjust it. Hope that helps.

**Comment by lgfogle** [comment] 2020-04-06 23:16
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!

**Closed by lgfogle** 2020-04-06 23:16 UTC
Labels: feature-request, shops-feature

**Comment by lgfogle** [comment] 2020-04-07 00:06
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
