### ISSUE TITLE
facebook pixel "add to cart" can not be actived

### ISSUE THREAD

**Issue by nguyenanh17** [facebookincubator/facebook-for-woocommerce#190] opened 2017-12-16 17:47 UTC
Dear everybody
I used facebook-for-woocommerce v1.6.0, i see this version is very ok but when i change or upload new product, it can not be synced to facebook product catalogue.
When i upgraded it to v1.7.1, i see a big problem, the facebook helper can not receive the pixel "add to cart" when i add a product to cart and can not receive other value (product id, total price in the cart)
Please help me.
Thank you much

**Comment by mengyingdu** [comment] 2017-12-18 17:47
Hi @nguyenanh17,

Since you upgrade to v1.7.1 from 1.6.0, there maybe too many changes which cause your problem. Can you try our latest version [v1.7.3](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.7.3) and then:
1. go to "WooCommerce Settings" --> "integration" --> facebook for woocommerce --> re-configure facebook settings
2. "force product re-sync"

Let me know whether it works.

Thanks.

**Comment by mengyingdu** [comment] 2017-12-20 09:03
could be similar to #192

**Comment by mengyingdu** [comment] 2017-12-22 17:12
Hi @nguyenanh17 ,

If you opt-in 'redirect to cart after add' like in issue #192 , can you try the workaround i suggested in that issue? I confirmed in my test store, and it works.

Thanks.

**Comment by dmitridr** [comment] 2018-03-23 00:27
Closing this as this is a duplicate with #192 and #219

**Closed by dmitridr** 2018-03-23 00:27 UTC
Labels: workaround
