### ISSUE TITLE
## same problem the pixel not registered the purchase action ##

### ISSUE THREAD

**Issue by jerome2612** [facebookincubator/facebook-for-woocommerce#230] opened 2018-01-23 02:31 UTC
hello 
we alrealdy talk about this issue i already install the version 1.7.4 and now the 1.7.5 
the  pixel not register at all the purchase action with fb add and direct purchase 
the pixel register add to cart // initiate payement but NO the purchase 
do you have any lead about that 
looking forward

**Comment by stelladex** [comment] 2018-01-23 13:39
Hello! Same issue, purchase pixel and initiate check out are active but not registering any purchases with FB conversion or direct purchase.  We have ceased our FB ads pending update.

![screen shot 2018-01-23 at 13 31 06](https://user-images.githubusercontent.com/35731704/35278603-7d2b72cc-0042-11e8-9a6b-ac870a9e4377.png)

**Comment by sammul** [comment] 2018-01-24 00:56
@jerome2612 @stelladex 
Can you guys share your website url so we can try out at least AddToCart to debug?

**Comment by jerome2612** [comment] 2018-01-24 04:10
https://truktil.com/

**Comment by stelladex** [comment] 2018-01-24 07:48
Sure, https://rogergracietv.com

 

Many thanks

Diane

**Comment by sammul** [comment] 2018-01-24 18:02
@jerome2612 I checked your pixel data on our side, it has sent 2 purchases in the past 28 days

**Comment by sammul** [comment] 2018-01-24 18:05
@stelladex I checked your pixel data on our side, it has sent 2 purchases in the past week. You need to adjust the time window to see more pixel data. The screenshot you sent only includes one day's event, so there might not be purchases on that day

**Comment by stelladex** [comment] 2018-01-24 18:13
Yes, we know it was only for that day, as an example.  For info, we have had well over 100 purchases since we made the update to 1.7.5 on 19th Jan and the pixel stopped recording purchases.

 

On the screenshot there were at least 20 purchases.

 

How can that be the issue closed?

**Comment by sammul** [comment] 2018-01-24 18:27
@stelladex I had a closer look at your pixel data. I did see the purchases dropped since Jan 18th. Do you remember which version were you on previously? You can try to install the older version to see if it can be fixed.

**Comment by stelladex** [comment] 2018-01-24 18:30
Yes, we went back to 1.7.4, but that didn’t fix it weirdly, yet it was running fine on that before we went to 1.7.5.  We’ve installed 1.7.5. via woo, then un-installed it and reinstalled from Github files.  Still no difference.

**Comment by sammul** [comment] 2018-01-24 18:33
@stelladex Thanks for letting us know. One more question, did you install any other plug-in or change your website at the same time? Just want to make sure that the only change on your side was upgrading our plug-in

**Comment by stelladex** [comment] 2018-01-24 18:36
No problem, really appreciate the help.  Actually, looking back I think we may have done a Stripe gateway plugin update on the same day, but nothing new installed or changes made other than that.

**Comment by stelladex** [comment] 2018-01-24 21:10
We tried reverting to 1.7.3 on 19th first, as that was the last version we had stored locally, but that didn’t work, so then we went to 1.7.4 to try that, then back to 1.7.5 again.

**Comment by stelladex** [comment] 2018-01-24 21:20
One other thing that I thought of is that we only have one product (membership video plans), so when a purchase is made our woo settings are set to go straight to check out when something is added to the cart rather than to continue shopping So we never see any data for add to cart, but see initiate check out instead, then purchase.

**Comment by sammul** [comment] 2018-01-24 21:24
@stelladex that makes sense. If you want to retarget people, just use view content but not purchase, or initiate check out but not purchase.
So far we suspect the issue might because our pixel code is not fully compatible with Stripe plug-in. One way to verify this is disable Stripe and try place an order to see if pixel can be fired. Not sure if you are comfortable to test this, but it will definitely help us understand where the issue comes from.

**Comment by stelladex** [comment] 2018-01-24 21:41
I’m sorry, we can’t do that as we have recurring monthly subscription payments going through all the time via Stripe tokens. Stripe is our only gateway, so we wouldn’t get the purchase pixel to fire without an active gateway, would we?

 

We really aren’t that concerned about having our store linked to FB page, our main aim is running conversion ads.  Do you think we might be better off deleting this plug in and using FB for Wordpress set up instead?

**Comment by sammul** [comment] 2018-01-24 22:01
@stelladex You can definitely try FB for Wordpress if only care about pixel events. I'm not 100% sure if it will work. So let us know if it works for you. If it's not, I can also help you report this to the owner of that plug-in. We can get more resource to figure it out.
So far, the best suspicion is the latest version of Stripe couldn't work with our pixel code.

One more suggestion from us is: If it's easy for you to downgrade to previous version of Stripe, you can do that and see if purchase can be fired. If yes, I suggest you to contact Stripe plug-in as well.
But I understand it's might be too much work for you. I'll tag this issue as a bug and we will try look into the compatibility between our plug-in and Stripe to see what we can do on our side. But this might take some time.

**Comment by stelladex** [comment] 2018-01-24 22:09
OK, thanks for your help.  I’ll speak to my colleague tomorrow to see if we can revert to the  previous version of Stripe to test and will let you know the outcome anyway.

**Comment by jerome2612** [comment] 2018-01-24 23:32
i had more purchase than 2 hopfully for me :-) 
this problem continue since long time if you read all my precedent post about this subject with @mengyingdu
the problem for exemple the pixel event register one view conten one add to cart one initiate payement but NOT THE PURCHASE
so it's impossible for mr to get my real stat from power editor
i use wp +shoper theme nothing fancy 
i already start there to explain this situation since more than 1 month 
hope you can help with this 
looking forward

**Comment by mengyingdu** [comment] 2018-01-25 19:21
Hi @stelladex ,

Super thanks for your feedback and follow-up information. There may be a easier way to fix this and test if you can change this in Wordpress 'plugin editor' (It's a sub-tab under plugin tab on the left of your dashboard)

Select 'facebook-for-woocommerce' --> 'facebook-commerce-events-tracker.php' file -> remove these [line](https://github.com/facebookincubator/facebook-for-woocommerce/blob/master/facebook-commerce-events-tracker.php#L254-L256)

The commit is to fix some 'thankyou page' can't be fired, instead we a payment complete hook and prevent double fire there. Given we had another fix for general events, we can remove that now. I think the Stripe gateway plugin update maybe incompatible with the woo payment hook.

Let me know if it works or you need more help.
Thanks.

**Comment by stelladex** [comment] 2018-01-25 19:54
Hi

 

Thanks so much for this, we are out of hours here in the UK now but will try it tomorrow and feed back

Diane

**Comment by jerome2612** [comment] 2018-01-25 23:20
@ mengyingdu 
Hello there this is it also for me?? I not use STRIPE but paypal ?
looking forward

**Comment by dmitridr** [comment] 2018-01-25 23:54
We reproduced the issue on our test servers with Stripe and have a fix ready to ship. Should have a new release in a few hours, we think it will fix the issue for Paypal too.

**Comment by dmitridr** [comment] 2018-01-26 00:07
We have the new version ready, can you install it from the zip file in our [latest releases section](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.7.7), or upgrade to it through the wordpress updater?

We know it fixes the problem for Stripe, but not sure about Paypal, would be good to have confirmation there.

**Comment by jerome2612** [comment] 2018-01-26 02:05
I did the update fv1.7.7) for now i don't have advertisement running so let's wait my next campaign i let you post soon as possible i have results 
thank for your help 👍

**Comment by dmitridr** [comment] 2018-01-26 19:44
Sure. I recommend v1.7.8, actually. v1.7.7 has a bug that affects a small % of users of the store, we fixed it just now.

**Comment by stelladex** [comment] 2018-01-29 07:43
Hi 

 

All sorted with the very last update!

 

Many thanks for your help.

Diane

**Comment by jerome2612** [comment] 2018-01-30 10:59
hello there not enough results to say if 100% solve
I just not understand why FB register for one puchase the add to cart and the initiate check out 
I mean should be ONLY the final result the purchase 
is it a bug or normal? 
looking forward

**Comment by jerome2612** [comment] 2018-02-03 10:29
hello there is it possible this update have a issue with the custom audience ??
because now I can NOT create any custome audience and all my old custom audience disapear 
looking forward

**Comment by dmitridr** [comment] 2018-03-13 21:57
I'm closing this because the issue in the opening comment has been resolved. We have a separate thread for the custom audience issue as well. #242 I think.

**Closed by dmitridr** 2018-03-13 21:57 UTC
Labels: bug
