### ISSUE TITLE
Add to Cart event is missing : Depending on redirect to cart page store setting

### ISSUE THREAD

**Issue by revendo** [facebookincubator/facebook-for-woocommerce#219] opened 2018-01-17 17:59 UTC
All necessary events seem to be working, but the add to cart event is not present. 

> We haven't detected the event AddToCart coming from your Pixel

**Comment by tahoff** [comment] 2018-01-17 20:15
Hello @revendo, do you use another extension for the add to cart functionality?

**Comment by revendo** [comment] 2018-01-18 10:47
The only extension we're using that could cause an issue is `Enhanced Ecommerce Google Analytics Plugin for WooCommerce`. Could that be a problem? If yes, could you recommend similar plugin for Google Analytics which is compatible to `facebook-for-woocommerce`?

**Comment by sammul** [comment] 2018-01-27 22:12
@revendo Can you share your website url with us so we can debug the issue?

**Comment by revendo** [comment] 2018-01-27 22:43
Sure: https://revendo.ch

**Comment by sammul** [comment] 2018-01-27 22:55
@revendo I did verify that AddToCart is not firing on your website. We will try to resolve it asap. Thanks for reporting

**Comment by sammul** [comment] 2018-01-27 23:00
@revendo would you mind try deactivate _Enhanced Ecommerce Google Analytics Plugin for WooCommerce_ and then try adding a product to see whether AddToCart can be fired? This can help us understand on your side if it's indeed caused by incompatibility with this plug-in

**Comment by revendo** [comment] 2018-01-28 21:36
I disabled the plugin `Enhanced E-commerce for Woocommerce store` but it doesn't seem to change the behavior.

**Comment by mengyingdu** [comment] 2018-01-29 19:28
seems similar to #192

**Comment by mengyingdu** [comment] 2018-01-29 19:30
Hi @revendo ,

Did you check "Enable AJAX add to cart buttons on archives" : Woocommerce -> settings ->display -> Add to cart behaviour?

**Comment by revendo** [comment] 2018-01-30 10:56
Yes, I did enable this function. Should I disable it?

**Comment by TimBHowe** [comment] 2018-01-30 15:17
Hey,
I have run into the same issue myself. 

I think the problem is that the [`inject_add_to_cart_event`](https://github.com/facebookincubator/facebook-for-woocommerce/blob/master/facebook-commerce.php#L294) which handles the ['AddToCart'](https://developers.facebook.com/docs/ads-for-websites/pixel-events/v2.11) event is added to the `woocommerce_add_to_cart` action. This action fires when an item is added to the cart, but if you have your store set to [Redirect to cart page upon adding a product to your cart](https://docs.woocommerce.com/document/configuring-woocommerce-settings/#section-5) this causes the action to be fired through ajax and redirect user to the cart before injecting the pixel code for the event.

This also could be causing issue with add-to-cart URLs. Example: https://www.yourwebsite.com/?add-to-cart=123.

You might want to revert it back to firing the issue on ['woocommerce_after_cart'](https://github.com/facebookincubator/facebook-for-woocommerce/commit/bf1965288c196694825e46ea5d368366b94eb1c5#diff-1e47101d4ffb440f08405b2a3cfc7d4eL213) action to allow this option to work.

Hope this helps.

**Comment by mengyingdu** [comment] 2018-01-30 17:49
Hi @TimBHowe and @revendo ,

We use 'woocommerce_after_cart' before, however, there is another double firing problem. Thanks to a pull request which enable to fire this as soon as you hit the button. However, you need to disable 'Redirect to cart page upon adding a product to your cart'.

**Comment by willgorham** [comment] 2018-01-31 01:52
Hi @mengyingdu 

Redirecting to the cart is a core feature of WooCommerce, and is important for many stores. I think FB for WC should be able to handle this action. Maybe raising an issue with WC core to make it easier to detect Add To Cart actions / redirects to the cart page could be helpful?

**Comment by mengyingdu** [comment] 2018-01-31 03:27
Hi @willgorham,

Thanks for your input and our team will consider that and talk to our product manager.

**Comment by mengyingdu** [comment] 2018-01-31 03:31
Hi @revendo and @TimBHowe ,

There is some workaround for you if you prefer using 'redirecting to cart' behavior:
In plugin editor, search for 'facebook-for-woocommerce', then change [these line](https://github.com/facebookincubator/facebook-for-woocommerce/blob/master/facebook-commerce.php#L301-L302) like [this](https://github.com/facebookincubator/facebook-for-woocommerce/blob/v1.6.5/facebook-commerce.php#L220-L221).

As I mentioned in #192, we can change it to be compatible in dual cases. However, this may add more db read which is performance unfriendly. We will consider @willgorham suggestion or figure out some other approach to fix it.

Let me if it works.

Thanks.

**Comment by willgorham** [comment] 2018-01-31 03:37
@mengyingdu Thanks for taking this into consideration.

Just to clarify your workaround: won't this fire the AddToCart event to every cart page view? (Even if a product hasn't just been added.)

**Comment by TimBHowe** [comment] 2018-01-31 14:08
I wrote up a quick function to get the 'AddToCart' event to fire on the 'woocommerce_after_cart' action without editing the plugin.  https://gist.github.com/TimBHowe/40f7fe01db0e6546d9403a19fbaf34f1

The point @willgorham brought up is correct. The 'AddToCart' event fires every time the a non empty cart page is visited with the total of all the items in the cart. This is probably why it was patched in 1.6.6 

We are going to keep looking into it on our end.

**Comment by dmitridr** [comment] 2018-02-15 22:43
@TimBHowe Nice fix!! Would you be willing to send us a pull request to incorporate it fully? I think there's something we can do here that accommodates both approaches, essentially detecting the store's add to cart setting, and firing add to cart in the right place based on that setting.

**Comment by belladonnaboutique** [comment] 2018-02-19 17:41
Hi there,

On my store now when I click Add to Cart, the pixel works for Add to Cart function. However, it only works when Add to Cart is clicked, and then an upsell pop up appears. If an upsell pop up does NOT appear, and the visitor is then re-directed to the cart, the pixel does NOT fire. 


I have attached screen shots to show. 
![screen shot 2018-02-19 at 12 32 37 pm](https://user-images.githubusercontent.com/35646111/36390625-b8c1e80e-1571-11e8-989b-b2e8b71fa4c3.png)
![screen shot 2018-02-19 at 12 33 07 pm](https://user-images.githubusercontent.com/35646111/36390653-cd7c4276-1571-11e8-8d34-19bd0b106528.png)

**Comment by belladonnaboutique** [comment] 2018-02-19 17:43
Notice the Add to Cart function missing from the cart page.

Also, please notice the View Content error. I checked the warning, and have attached a screen shot. It says there is an error in the url coding, but I am not sure how this is possible because the url is exactly the same and I am not sure how to fix this. 
![screen shot 2018-02-19 at 12 41 21 pm](https://user-images.githubusercontent.com/35646111/36390952-8366e9b0-1572-11e8-9aee-0dd811e8f304.png)

**Comment by dmitridr** [comment] 2018-03-14 01:16
Thanks for the additional report. Agree that's not good behavior. We'll prioritize a fix that works for both cases (upsell and no upsell). The `ViewContent` issue seems like a separate problem, I'd open a separate issue for that if you can.

**Comment by dmitridr** [comment] 2018-04-06 23:58
Ok so we finally fixed this issue. Here's what we did:

- If your store setting is redirect to cart, we fire the event on the Cart being viewed.
- If your store setting is not redirect to cart, we fire the event via AJAX when the button is clicked.

The fix is in v1.8.4 and later versions available [here](https://github.com/facebookincubator/facebook-for-woocommerce/releases/latest). Thanks for your patience!

**Closed by dmitridr** 2018-04-06 23:58 UTC
Labels: Do this ASAP, bug

**Comment by willgorham** [comment] 2018-04-08 02:34
@dmitridr Thank you!

**Comment by madjedo** [comment] 2018-04-25 21:00
Hi, can you upload this update to woocommerce also so we can update via the wordpress dashboard aswell?

Thanks!

**Comment by saurabh-shirude** [comment] 2021-12-09 06:41
Hi, I am facing a similar issue with a website (Add to cart event missing: depending on redirect to cart page store setting). Can someone please help?
