### ISSUE TITLE
Site Speed Issues

### ISSUE THREAD

**Issue by mshafiqtahir** [facebookincubator/facebook-for-woocommerce#18] opened 2017-08-17 20:49 UTC
I am using this plugin with paid campaign but I am facing a lot of site speed issues because my site requests increased. This plugin adds 10, 12 live requests due to these live requests my server response time increased as well as load time and page size increased. Due to this, our clients complain us about our site speed in most countries site load time greater than 15sec.
I have tested my site on different hosting server. We have VPS only for this site but all in vain. Currently, we have uploaded our site into cloud server but getting same results.

**Comment by tahoff** [comment] 2017-08-19 00:30
This plugin only adds non-blocking Javascript calls, so this hopefully shouldn't affect the user experience. We will continue to monitor this report and work on performance improvements in future versions.

**Comment by dmitridr** [comment] 2017-09-19 01:17
Hello,

A couple of points:

- The live requests (I assume you mean the pixel fires) are necessary for you to retarget the users who visited your site on Facebook.
- These requests should not increase page rendering time. They will increase overall load time because there will be JS code to wait for the reply from Facebook (for fetching fbevents.js).
- We also have our demo servers in the cloud and do not observe any delay in response time. So we cannot repro your issue.

If this is unacceptable, but you still would like to use our extension, I can think of a very technical workaround that would involve you editing our plugin directly and would involve a lot of trial and error on your part. The approach would be to avoid JS entirely, and use the [`<img>`](https://github.com/facebookincubator/facebook-for-woocommerce/blob/master/facebook-commerce-pixel-event.php#L55) tag to fire the pixel. I can go into more detail if you are interested, but it is highly unlikely that we will issue a fix for this, unless it is a problem for many others as well, especially seeing that we cannot reproduce the problem.

**Comment by mshafiqtahir** [comment] 2017-09-19 06:10
Hi,

I am also talking about load time and our response time is also fine. But
as you know load time meter a lot regarding user experience. As google
recommended that page load time should less than 5 seconds but your
extension increased the load time which will adversely effects our site.

**Comment by dmitridr** [comment] 2017-10-09 22:29
Hi,

I understand your concern, but unfortunately there is not much we can do about that.
There are some things you can do however if you'd like to compromise, for example you could install ['Facebook for Wordpress'](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.6.3) which has a much simpler pixel install, which will result in less quality of signal for ads, but slightly higher site performance.

You could also hack the extension to [remove the JS code added by the pixel](https://github.com/facebookincubator/facebook-for-woocommerce/blob/master/facebook-commerce-pixel-event.php#L29) and replace it with the `<img>` tag seen in the code [here](https://github.com/facebookincubator/facebook-for-woocommerce/blob/master/facebook-commerce-pixel-event.php#L55), which should take no time at all load. But it will limit you to `PageView` events only.

**Comment by dmitridr** [comment] 2017-10-31 19:09
Closing as there is unfortunately not much we can do here. I'd reiterate that a lightweight version of this plugin with only `img` tags would probably be the best way to go for site speed, but it would be a huge change and there would be some loss of functionality. Too large of a change for us to consider including for now.

**Closed by dmitridr** 2017-10-31 19:09 UTC
Labels: wontfix
