### ISSUE TITLE
How to delete the plugin or change the pixel

### ISSUE THREAD

**Issue by Jho-Facebook** [facebookincubator/facebook-for-woocommerce#188] opened 2017-12-12 14:35 UTC
I have a small issue with the plugin. We are a Ad Agency and send the pixel and instructions to the company´s developer. He did it but because he doesn´t have access to our Facebook Ads account, he associated the Woocommerce for Facebook with the pixel ID for his personal Facebook Ads Account.

Now we can´t change the pixel:
![captura](https://user-images.githubusercontent.com/34481275/33889962-0fd229ca-df52-11e7-84b1-f933ad5683a1.PNG)

So because we can´t give access to our Facebook Ads Accounts to the developer. How can we change the pixel ID? Do we have to delete or remove the initial settingsof this plugin? Will affect the current ads?

Hope you can help me with this.

**Comment by tahoff** [comment] 2017-12-13 01:10
If you want to re-complete setup, the developer will need to open the popup, go to "Advanced Settings" and click the button to delete settings. This will enable you to re-complete setup with the correct pixel.

This will potentially affect ads in two ways:
1. If you're currently using that original pixel for optimization, and you change the pixel, then the ads will not perform as well.
2. If you're using the product catalog which was created as part of the Shop, then those ads will no longer deliver (because the catalog will be deleted when you delete the settings).
If you don't have ads of either type, then you should be fine.

**Comment by tahoff** [comment] 2017-12-15 15:00
I'll close this issue for now. Please let us know if this strategy doesn't work for you.

**Closed by tahoff** 2017-12-15 15:00 UTC
Labels: question

**Comment by PeterHygge** [comment] 2018-03-07 10:07
Hi, I followed these steps but the old pixel remains the only option in setup. Any idea?

**Comment by VonTalavang** [comment] 2018-05-15 11:52
How can I change the pixel?
I delete the plugin... reinstalled.... nothing changes

**Comment by NFerguson07** [comment] 2018-06-30 21:57
I was able to get the other pixel account up. I tried both the woocommerce and facebook plugin. I had to delete those and manually insert the code into my header (using another plugin called "Insert headers and footers". 
However now I am not sure how to setup my events for purchase, add to cart, etc..
Any help would be greatly appreciated

**Comment by rbreaves** [comment] 2019-04-23 19:06
Definite oversight by the guys at Facebook. The removal of the plugin data does not remove the invalid Pixel information from a personal account. The plugin will continue to try and use the data from the personal account. Please re-open this ticket and resolve it. (Not particularly hopeful though, considering how old this ticket is.)

**Comment by srameshr** [comment] 2019-04-24 18:59
Shit, I just came across this.
There is no way to change FB pixel id once you have set it. Even deleting Facebook For Woocommerce plugin will still retain old plugin Id

**Comment by allaserik** [comment] 2019-05-01 09:19
Same problem, I can choose the right page in Facebook For Woocommerce plugin's settings but the next step to choose the pixel it only shows me another site's pixel (which shouldn't be there in the first place) that i have and i can't choose the correct site's pixel. 
I'll look into the database and maybe fix it by force.

**Comment by allaserik** [comment] 2019-05-08 03:06
Bueller

**Comment by Joaoaso** [comment] 2019-05-24 21:16
Same problem in two websites, need help to fix it.

**Comment by feLiruc** [comment] 2019-06-06 12:58
A 2 years problem, and nobody came with any sollution? :(
I'm experiencing the same issue with my installation... lost 2 days trying to fix it.

**Comment by allaserik** [comment] 2019-06-06 13:08
How did you fix it?

**Comment by Joaoaso** [comment] 2019-06-06 13:12
the only solition that I find was create a new facebook fan page and start over.

**Comment by allaserik** [comment] 2019-06-06 13:19
Ok so switch to one and then other the one that is correct? So you can
overwrite with new.

**Comment by Joaoaso** [comment] 2019-06-06 13:29
The problem is not in the plugin but in the facebook fans pages. I deleted all the pixel connections and even then nothing, and as facebook does not allow to delete the pixel I turned around otherwise.

I had two stores as this same problem. For one I changed facebook page that had no pixel link and to another store create a new page.

P.S - I called the store to another page and then tried to go back to the old one but the problem continues.

**Comment by izieizwan** [comment] 2020-01-16 05:21
> Same problem, I can choose the right page in Facebook For Woocommerce plugin's settings but the next step to choose the pixel it only shows me another site's pixel (which shouldn't be there in the first place) that i have and i can't choose the correct site's pixel.
> I'll look into the database and maybe fix it by force.

For Facebook for Woocommerce plugin, go to Plugin Installed > Facebook for Woocommerce > Setting. Hit "Ctrl + Shift + J". Then write this code "delete_all_settings();" and hit enter.

Your FB Pixel installed from Facebook for Woocommerce will dissappear. If the FB Pixel still there, it means that you've installed the FB Pixel from another plugin.

**Comment by ernestsawyer** [comment] 2020-04-21 19:14
Hi friends, the easiest way is to go to MySQL database via either Phpmyadmin or your favorite DB software, click on search in DB and type in your pixel ID, it will return you 3 results in <prefix>options table. 

woocommerce_facebookcommerce_settings
woocommerce_facebookcommerce_legacy_settings
facebook_config

Delele all 3. Plugin will then allow you to the make set-up from scratch.

**Comment by athanlive** [comment] 2020-05-07 03:35
It took me quiet a while to figure this one out, not sure if my solution will help everyone else, but here you go. Keep in mind new pixel means new data.

Go to Catalog Manager, pick the catalog you are having issues, go to Settings from the left side, click edit Event Sources, add the second pixel you want associated with the account. Then on woocommerce you can remove the plugin and add it again. During setup, make sure the account you are using has full access to the pixel you want to use (and most importantly make sure the Pixel has an Ad account in the assets assigned - ad account that you also have access to, otherwise the pixel will not show up in the options to select it during setup // Business Settings -> Data Sources -> Pixels, 3rd tab connnected assets).
If all the above are correct then the pixel you want to use will be available. If the Pixel is not available to you then it means you have not setup the pixel right (that was my case) - When in woocommerce facebook setup, just go back to the firs step, and click "edit" next to the pixel selected. Again, if the pixel is not setup right it wont work - The store is not permanently linked to a pixel so no issues on the plugin, it just that the business pixel requires a little extra setup with billing, needs ad account etc...

Hope this helps, if anyone still needs help

**Comment by fotogaaf** [comment] 2020-06-11 21:01
@ernestsawyer 

You are my hero: so simple buth effective!
In addidtion i had to change the fb page also stored in de db

**Comment by mcrwanek** [comment] 2020-06-25 17:37
> @ernestsawyer
> 
> You are my hero: so simple buth effective!
> In addidtion i had to change the fb page also stored in de db

@fotogaaf  hi, could you please tell me where and which info related to the fb page you also deleted?
thank you, unfortunately deleteing rows with old pixel didn't help, facebook for wooceommerce still shows old pixel even though there is no such entry in MySQL....

**Comment by ernestsawyer** [comment] 2020-06-25 19:38
@mcrwanek hi, have you tried to search your DB for entries with your profile page name? For quicker solution, feel free to contact me via e-mail at ernest@sawyer.sk. I can update my answer regarding to what we will find out. Regards

**Comment by fotogaaf** [comment] 2020-06-26 14:16
@mcrwanek

Search for the businesspageNR in the database and delete those entries
You can also contact me directly : fotogaaf@gmail.com

**Comment by jricher96** [comment] 2020-07-06 01:14
1) delete plugin "facebook for woocommerce"
2) install plugin "Pixel Caffeine"
3) Create new fb ID OR fb Page OR Both,
4) Get FB Pixel ID (from new fb page, see no. 3)
5) Add new id in "Pixel Caffeine"

You are good to go in 20mints. :)

**Comment by RemTod** [comment] 2020-11-30 06:37
This is the problem where i want the second button to be a buy now button but still has the "add to cart" function. I cant change the second button text because of the same class that maybe the template harcode the text.
https://ibb.co/jhRM3Gj

it was supposed to be like this. The "buy now" button should be act like the add to cart button.
https://ibb.co/Cb0xnH1
