### ISSUE TITLE
Pixel installed and receiving events but error in the linked catalogue

### ISSUE THREAD

**Issue by baRToooo** [facebookincubator/facebook-for-woocommerce#636] opened 2018-08-20 17:40 UTC
Hi all

I have a pixel set up in a Wordpress Woocommerce project: www.armogan.com. 

The pixel is working fine: 
![image](https://user-images.githubusercontent.com/5033899/44356601-1b0f7f80-a4b0-11e8-8cb2-84cedfd580d5.png)

Receiving plenty of events. 

However, when trying to link this pixel with a catalogue, this is not working:
![image](https://user-images.githubusercontent.com/5033899/44356671-485c2d80-a4b0-11e8-8e16-bf156b531a14.png)

The catalogue is however linked to the Facebook account and the content_ids match: 
![image](https://user-images.githubusercontent.com/5033899/44356766-96713100-a4b0-11e8-86fc-f2556691c5a0.png)

This is the link to that product: https://www.armogan.com/product/racing-blue-sr40s. 

There is however an error when trying to debug with Pixel Helper: 
![image](https://user-images.githubusercontent.com/5033899/44356862-dafccc80-a4b0-11e8-934b-33c33cc09ce2.png)

The pixel is being loaded in with GTM. 

Any ideas?

**Comment by jieminz22** [comment] 2018-08-20 18:05
## Automated Support Message

Hello,

Thanks for your interest in our plugin!

If your issue is a feature request or feedback for the developers, reply with `Feature Request` or `Feedback`.
If you are a developer or have a question for the developers related to code, reply with `Developer Question`.
If you are running ads with us, include `Advertiser` in your reply.

If you have encountered a bug or a problem with the plugin, the steps below contain information to help you resolve the issue yourself and provide us information we need to help you with your problem.

## Search Existing Issues

**First, please [search our issues](https://github.com/facebookincubator/facebook-for-woocommerce/issues?q=) to see if your problem has been reported before.**
There may already be a workaround or a solution to your problem. You can search our issues using [the search bar near the top of our issues page](https://github.com/facebookincubator/facebook-for-woocommerce/issues?q=); be sure to search both _open_ and _closed_ issues.
If you do find a similar issue, leave a comment on that issue and close this one. Your comment helps us prioritize which existing issues are important and urgent.

## Common Resolution Methods

**If you are experiencing a problem or bug and have not found any similar issue, please try the following:**

* Upgrade to the latest version of the plugin.
* Try to `Resync` products using the button on the plugin config page
* Reset the plugin by selecting `Reconfigure > Advanced Options > Delete`, and setting up this plugin again.
* Try to deactivate other plugins that you think may be interfering, then reset and set up again.

## Necessary Information

**If the above steps did not help, please provide the following information in your next comment in order for us to debug your problem:**

* WooCommerce version
* WordPress version
* Plugin version (please note: we only support up-to-date versions of the plugin)
* A screenshot of where you see the problem (for example: if it is on Facebook, a screenshot of Facebook, if it is on WooCommerce, a screenshot of WooCommerce. If it is in multiple places, multiple screenshots.)
* The URL of your website
* The URL of your page
* The URL(s) of where you took your screenshot(s)
* (If applicable) Detailed steps you took in order to see the problem

Please include `Debug Ready` in your reply so our automated system can flag your issue for manual review. Please note that due to a high volume of issues, we may not be able to respond immediately.

Thanks for your patience,
The Facebook Dev Team (@mengyingdu, @dmitridr, @sammul, @jieminz22)

**Comment by baRToooo** [comment] 2018-08-20 21:48
WooCommerce Version 3.0.9
Wordpress Version 4.8.7
Facebook for WooCommerce Version 1.9.2

Debug Ready

**Comment by baRToooo** [comment] 2018-08-23 08:35
Hi 

By any chance an update on this?

**Comment by jieminz22** [comment] 2018-08-23 20:42
HI @baRToooo,

I checked your website and it doesn't seem AddToCart event is firing. Can you try our latest version of the extension and see if the issue persists?

**Comment by baRToooo** [comment] 2018-08-24 07:17
Hi @jieminz22 

Are you sure? Because in the overview (first screenshot), there are 349 AddToCart events received. 
More details: 

![image](https://user-images.githubusercontent.com/5033899/44570352-d0c32280-a77d-11e8-876a-030ee1b32085.png)

Although it does indeed say on the diagnostics that no Add To Cart events were received: 
![image](https://user-images.githubusercontent.com/5033899/44570528-74143780-a77e-11e8-9a5f-244a2e719824.png)

But then why does it seem okay on the overview. 

I updated the Facebook for WooCommerce plugin to the latest version. 

If you have any more tips, more than welcome!

Cheers
Bart

**Comment by jieminz22** [comment] 2018-08-24 18:37
Hi @baRToooo,

You don't need to manually associate the catalog if everything works fine with the plugin. Can you try reset the plugin by selecting Reconfigure > Advanced Options > Delete, and setting up this plugin again? Make sure you are with the latest version when reset.

**Comment by baRToooo** [comment] 2018-08-25 14:08
Hi @jieminz22 

I just tried this, but: 
![image](https://user-images.githubusercontent.com/5033899/44619066-0d2b7700-a881-11e8-9370-b3deeec114a0.png)

I'll try again later.

**Comment by baRToooo** [comment] 2018-08-28 14:12
Hi @jieminz22 

This error keeps appearing. Is this a bug in the plugin? 

Cheers
Bart

**Comment by jieminz22** [comment] 2018-09-10 18:58
Hi @baRToooo,

We can try to remove your settings from our end. Please confirm if you want us to proceed.

**Comment by baRToooo** [comment] 2018-09-11 10:10
Hi @jieminz22 

Go ahead, unless there are any risks we should be aware of?

**Comment by baRToooo** [comment] 2018-09-15 10:51
Hi @jieminz22 

It's https://www.armogan.com/. 

Thanks
Bart

**Comment by baRToooo** [comment] 2018-09-20 07:00
Hi @jieminz22 

Do you have an update on this? 

Thanks

**Comment by jieminz22** [comment] 2018-09-20 22:38
@baRToooo,

Sorry I meant your FB page url. Once we confirmed on it we will delete your settings from our end. Sorry for the delay.

**Comment by baRToooo** [comment] 2018-09-21 08:47
Hi @jieminz22 

It's https://www.facebook.com/armoganwatches. 

Keep me posted

Thanks

**Comment by jieminz22** [comment] 2018-09-21 22:05
Hi @baRToooo,

Settings deleted from our end. Please confirm. Thanks!

**Closed** 2018-10-09 17:30 UTC
Labels: Automated : Debug Ready
