### ISSUE TITLE
Plugin Update not working since version 1.8.3

### ISSUE THREAD

**Issue by Trebacz** [facebookincubator/facebook-for-woocommerce#492] opened 2018-05-19 00:12 UTC
I have been using the plugin for quite awhile. Since 1.8.3, when I try and update the pugin through normal Wordpress plugin update I get the message "Update Failed: Update package not available." This happens on all three of my environments.

Production environment is: https://www.glasshousestore.com/
Facebook page is: https://www.facebook.com/glasshousedecatur/

Current version of Facebook-for-WooCommerce 1.8.3
WooCommerce 3.3.5
Wordpress 4.9.6
PHP 7.2.5

![screenshot_20180518_170615](https://user-images.githubusercontent.com/19363347/40262651-d8790e5c-5abd-11e8-91a1-fabcffea8c46.png)
![screenshot_20180518_170331](https://user-images.githubusercontent.com/19363347/40262653-db1b08b8-5abd-11e8-9cac-43ed9f4681cb.png)

**Comment by mengyingdu** [comment] 2018-05-21 00:03
[Note : This is an Automated Message]

Hello,

Thanks for your interest in our plugin!
Due to a high volume of issues we may not be able to get to yours immediately.

If this is a feature request, or feedback, please reply with
`Feature Request` or `Feedback` and it will be categorized accordingly, and
we will read it and reply when we can.

If you are experiencing problems, read on.

First. Please check to see if your issue is not a duplicate of another one.
To search our issues, use the search feature at the top of the GitHub issues page.
We have nearly 500 existing and past issues, so it is fairly likely someone else has already reported your problem.
If you do find a relevant issue, please comment in that issue, and close this one.
It helps us prioritize issues to tackle by looking at the number of people with the same problem.

If your issue is unique, and you are sure, then read on.
We require the following information in order to help you:
- WooCommerce Version
- Wordpress Version
- Plugin Version. Please Note that we do not support outdated versions of the plugin.
- A Screenshot of where you see the problem. If it is on Facebook, a screenshot of Facebook,
if it is on WooCommerce, a screenshot of WooCommerce. If it is in multiple places, multiple screenshots.
- The URL of your website.
- The URL of your page.
- The URL(s) where you took your screenshot(s).
- (If applicable) Detailed steps you took in order to see the problem.

Please be advised, it may take us some time to get to your issue.
In the meantime, below are generic approaches you can take that may solve the issue :
- Upgrade to the latest version.
- Force Resync
- Reset the plugin using `Reconfigure > Advanced Options > Delete` and setup again.
- Try to deactivate other plugins which you think could be interfering and repeating the above.

When you have the above data for us, please include
`Debug Ready` in your reply. We will get to it and debug it as soon as we can.

Thanks for your patience,
Dev Team (@dmitridr, @mengyingdu, @sammul, @jieminz22)

**Comment by mengyingdu** [comment] 2018-06-17 17:43
You can deactivate -> delete -> install -> upload from [here](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.9.0)

**Comment by dmitridr** [comment] 2018-06-22 23:30
I can't repro this, upgrading from 1.8.5 and 1.8.7 to 1.9.0 worked for me, are you still having this issue? 
We haven't touched the upgrading logic for a long while so it's a surprise if we suddenly broke it.

If I had to guess I would say the request to GitHub for the new version failed for some reason. Perhaps a server configuration?

If you're willing to help us debug, could you try installing an older version, say 1.8.0 and check to see if the upgrade is still broken for you? If so, it's likely a configuration issue on your servers. If it works on 1.8.0 (but not 1.8.3) then I think it's some kind of compatibility bug.

**Closed** 2018-07-04 18:50 UTC
Labels: bug
