### ISSUE TITLE
Facebook for woocom error line 1811

### ISSUE THREAD

**Issue by DickeyMo** [facebookincubator/facebook-for-woocommerce#1653] opened 2020-10-27 04:30 UTC
WordPress version 5.5.1
Current theme: Storefront (version 2.8.0)
Current plugin: Facebook for WooCommerce (version 2.1.0)
PHP version 7.1.24

Error Details
=============
An error of type E_PARSE was caused in line 1181 of the file /home1/newriche/Tactical-Prepper.com/wp-content/plugins/facebook-for-woocommerce/includes/Products.php. Error message: syntax error, unexpected '

The pixel is not receiving.
Contacted my hosting provider, they said they resolved the issue.
Went back to Facebook ads manager and still cant get the pixel to work.
The option to input a new token is no longer visible in my wep dashboard/plugin section.

I have no clue what to do next...any thoughts?

**Comment by discovercrm** [comment] 2020-10-27 06:53
Me too same error had to rename the directory to get my site working again.  not sure if there has been a recent update, was adding new products to woocommerce earlier today without errors.

**Comment by dalhoss** [comment] 2020-10-27 07:21
Hello Team ,

i have the same error there is nay solution for this ,and how can'i get my site working again.

Regards.

**Comment by mateusz-szafraniec** [comment] 2020-10-27 08:15
Quick fix:
rm -rf wp-content/plugins/facebook-for-woocommerce

Deploying without testing, Facebook really?

**Comment by mateusz-szafraniec** [comment] 2020-10-27 08:16
Duplicate of #1652

**Comment by discovercrm** [comment] 2020-10-27 08:31
just rename the directory to facebook-for-woocommerce2 and your site will work until the fix then re-install plugin

**Comment by dalhoss** [comment] 2020-10-27 10:23
Thanks all for your answer is working by changing the name of directory to facebook-for-woocommerce2

**Comment by Morvanmc** [comment] 2020-10-27 18:01
Thanks @discovercrm ! I just rename the directory, as you said and it worked for me! Thank you again!

**Comment by rzqbudiawan** [comment] 2020-10-28 01:47
Thank you verymuch @discovercrm ! I just rename this facebook-for-woocommerce directory to facebook-for-woocommerce2, then I updating plugin (before update plugin, I rename the directory to the start) and it's work! Thank you...

**Comment by DickeyMo** [comment] 2020-10-28 20:37
> Hello Team ,
> 
> i have the same error there is nay solution for this ,and how can'i get my site working again.
> 
> Regards.

I hired a guy on fiverr , he fixed it in 10 min lol best 5 bucks ever!

**Comment by DickeyMo** [comment] 2020-10-28 20:39
> Quick fix:
> rm -rf wp-content/plugins/facebook-for-woocommerce
> 
> Deploying without testing, Facebook really?

yes really...lol all  of my other ads have worked and this one was a dup with minor copy changes for a/b testing..if that answeres your question...really?

**Comment by simonporter007** [comment] 2020-11-09 15:40
Duplicate of #1652

**Closed by simonporter007** 2020-11-09 15:40 UTC
