### ISSUE TITLE
CRITICAL Uncaught ArgumentCountError

### ISSUE THREAD

**Issue by kidpluszmedia** [facebookincubator/facebook-for-woocommerce#1220] opened 2020-03-12 18:49 UTC
Hi,
a complete crash after the upgrade.
I tried to update woocommerce too, but it didn't help.
I had to turn it off.
What's the problem?
Thank!

2020-03-12T18:26:04+00:00 CRITICAL Uncaught ArgumentCountError: Too few arguments to function WC_Facebookcommerce_EventsTracker::set_last_product_added_to_cart_upon_redirect(), 1 passed in /home/firkafal/public_html/wp-includes/class-wp-hook.php on line 288 and exactly 2 expected in /home/firkafal/public_html/wp-content/plugins/facebook-for-woocommerce/facebook-commerce-events-tracker.php:346
Stack trace:
#0 /home/firkafal/public_html/wp-includes/class-wp-hook.php(288): WC_Facebookcommerce_EventsTracker->set_last_product_added_to_cart_upon_redirect('https://firkafa...')
#1 /home/firkafal/public_html/wp-includes/plugin.php(206): WP_Hook->apply_filters('https://firkafa...', Array)
#2 /home/firkafal/public_html/wp-content/themes/oceanwp/inc/woocommerce/woocommerce-config.php(769): apply_filters('woocommerce_add...', 'https://firkafa...')
#3 /home/firkafal/public_html/wp-includes/class-wp-hook.php(288): OceanWP_WooCommerce_Config->localize_array(Array)
#4 /home/firkafal/public_html/wp-includes/plugin.php(206): WP_Hook->apply_filters(Array, Array)
 hiba /home/firkafal/public_html/wp-content/plugins/facebook-for-woocommerce/facebook-commerce-events-tracker.php fájlban a 346 sorban

https://firkafalva.hu
https://www.facebook.com/kreativfoglalkoztato
WordPress 5.3.2
Php 7.2.28
WooCommerce 4,0,0
Facebook for WooCommerce 1.10.1

**Comment by simonporter007** [comment] 2020-03-12 19:01
Hey @kidpluszmedia!

Thanks so much for providing the error stack trace, that's super helpful! What it shows is that there's an issue with the OceanWP theme when calling one of the standard WooCommerce filters we use within the plugin. I thought this looked familiar, and my teammate had investigated this the other day! If you'd like to read more about the root cause, you can [take a look at this thread](https://wordpress.org/support/topic/fatal-error-500-site-caiu/) on the WordPress.org forums.

She has opened up a support request with the OceanWP team regarding this issue already. Though if you'd like to follow along, you can do so here: https://wordpress.org/support/topic/incorrect-usage-of-woocommerce-filter-causing-fatal-error-with-facebook-for-wc/ it sounds like they should be releasing a fix in the next few days!

In the meantime, if you'd like to fix this sooner, Tamara did prepare a patched version of the OceanWP theme. You can download this zip file here: https://cloud.skyver.ge/bLum0NPg
Before you install this version you will need to fully delete your version of the OceanWP theme and install the provided zip file.

Would you please let me know if the patched file addresses the issue, or if you'd like to wait for the official patch version?

Cheers!

**Comment by kidpluszmedia** [comment] 2020-03-12 22:38
Hi Simon!
Thank you very much and also for working at this level and trying to find a
solution. Exemplary attitude. Thank you on behalf of many, many users!
Since I don't have a lot of practice, I'll wait a day or two for the
official update, but if it doesn't come, I'll use the one you sent.
Thank you very much !!





[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
20.
03. 12. 23:37:26

Simon Porter <notifications@github.com> ezt írta (időpont: 2020. márc. 12.,
Cs, 20:01):

**Comment by simonporter007** [comment] 2020-03-12 23:30
Hey @kidpluszmedia!

It's my pleasure! Thanks so much for the kind words. Sounds like a plan then!

I'll close this issue for now, though if you do decide to go ahead with our patched version, let me know if you need further assistance.

Cheers,

**Closed by simonporter007** 2020-03-12 23:30 UTC
