### ISSUE TITLE
Resource interpreted as Document but transferred with MIME type image/gif

### ISSUE THREAD

**Issue by mshafiqtahir** [facebookincubator/facebook-for-woocommerce#12] opened 2017-08-07 11:23 UTC
On Google Chrome we saw error in the console which start execution and never stop until page goes to not responding
Error is : Resource interpreted as Document but transferred with MIME type image/gif: “https://www.facebook.com/tr/”

**Comment by dmitridr** [comment] 2017-09-14 21:29
Could you elaborate on this? In order to address this we would need to reproduce the issue. 
But this is not enough information for us to do so, though from the URL I can guess it's a pixel issue, we have never seen such an issue before.

A link to a page where this occurs would be helpful.

**Comment by myso182** [comment] 2017-10-05 13:53
Hello, we have same problem. Mentioned error is visible on console right after Place order button is clicked on Checkout page. 

Michal

**Comment by dmitridr** [comment] 2017-10-06 00:58
I see, thank you @myso182 . I have confirmed the repro. Though in our case the execution proceeds further after the error is seen.

**Comment by myso182** [comment] 2017-10-06 11:59
Thanks for reply, Dmitri.

Yes, I can confirm that customer is still able to place order despite this error in console. 

Michal

**Comment by bmca4u** [comment] 2017-10-13 05:20
@dmitridr @myso182 @mshafiqtahir  Anybody got a solution for this issue?

Resource interpreted as Document but transferred with MIME type image/gif: "https://www.facebook.com/tr/".

**Comment by dmitridr** [comment] 2017-10-31 19:07
Since this is just a warning in the console, we have prioritized more critical bugs for now. We haven't forgotten about this issue, however. 

In the meantime if anyone has come up with a fix, we're happy to look at pull requests to solve this.

**Comment by dmitridr** [comment] 2017-12-14 22:29
Looks like it's a generic problem with the pixel, not specific to our plugin. Our pixel team is working on a potential fix.

**Comment by alvarotrigo** [comment] 2018-01-08 17:14
Same issue.

**Comment by mengyingdu** [comment] 2018-03-06 18:27
Hi @alvarotrigo, @mshafiqtahir , @myso182 and @bmca4u , 

This should be fixed in early February by our pixel team. Feel free to open an new issue if you still have this problem.

Thanks.

**Closed by mengyingdu** 2018-03-06 18:27 UTC
Labels: bug
