### ISSUE TITLE
I can't Sync Products to facebook store : cURL error SSL_ERROR_SYSCALL errno 0

### ISSUE THREAD

**Issue by chenyangyangvip** [facebookincubator/facebook-for-woocommerce#600] opened 2018-07-28 04:47 UTC
Who can hlep me? 
Always show a hint：
Background syncing products to Facebook. Products remaining: 66

But， All the time, there's no change.

WordPress 4.9.7
WooCommerce version:  3.4.4
Facebook for WooCommerce  1.9.2

https://xiuhair.com/

![image](https://user-images.githubusercontent.com/33614001/43368142-1d135b3e-938b-11e8-80e3-0a2efd615998.png)

![image](https://user-images.githubusercontent.com/33614001/43368254-0f99741e-938d-11e8-8d35-4c4c830a118d.png)

Please Help me!!

**Comment by mengyingdu** [comment] 2018-07-30 21:05
## Automated Support Message

Hello,

Thanks for your interest in our plugin!

If your issue is a feature request or feedback for the developers, reply with `Feature Request` or `Feedback`.
If you are a developer or have a question for the developers related to code, reply with `Developer Question`.
If you are running ads with us, include `Advertiser` in your reply.

If you have encountered a bug or a problem with the plugin, the steps below contain information to help you resolve the issue yourself and provide us information we need to help you with your problem.

## Search Existing Issues

**First, please [search our issues](https://github.com/facebookincubator/facebook-for-woocommerce/issues?q=) to see if your problem has been reported before.**
There may already be a workaround or a solution to your problem. You can search our issues using [the search bar near the top of our issues page](https://github.com/facebookincubator/facebook-for-woocommerce/issues?q=); be sure to search both _open_ and _closed_ issues.
If you do find a similar issue, leave a comment on that issue and close this one. Your comment helps us prioritize which existing issues are important and urgent.

## Common Resolution Methods

**If you are experiencing a problem or bug and have not found any similar issue, please try the following:**

* Upgrade to the latest version of the plugin.
* Try to `Resync` products using the button on the plugin config page
* Reset the plugin by selecting `Reconfigure > Advanced Options > Delete`, and setting up this plugin again.
* Try to deactivate other plugins that you think may be interfering, then reset and set up again.

## Necessary Information

**If the above steps did not help, please provide the following information in your next comment in order for us to debug your problem:**

* WooCommerce version
* WordPress version
* Plugin version (please note: we only support up-to-date versions of the plugin)
* A screenshot of where you see the problem (for example: if it is on Facebook, a screenshot of Facebook, if it is on WooCommerce, a screenshot of WooCommerce. If it is in multiple places, multiple screenshots.)
* The URL of your website
* The URL of your page
* The URL(s) of where you took your screenshot(s)
* (If applicable) Detailed steps you took in order to see the problem

Please include `Debug Ready` in your reply so our automated system can flag your issue for manual review. Please note that due to a high volume of issues, we may not be able to respond immediately.

Thanks for your patience,
The Facebook Dev Team (@mengyingdu, @dmitridr, @sammul, @jieminz22)

**Comment by chenyangyangvip** [comment] 2018-07-31 05:07
Debug Ready

**Comment by chenyangyangvip** [comment] 2018-08-06 16:02
Hi, Can You Help Me?

The problem remains unsolved @mengyingdu

**Comment by dmitridr** [comment] 2018-08-06 23:32
Hello, 

The plugin tried to upload your products using `curl` but failed.
Can you do a plugin reset and try again? The procedure to reset is outlined in #612 

If the same thing happens, please ensure that `curl` is configured correctly and allowed on your webserver. You can also try using an older version of the plugin [1.7.11](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.7.11) that does not use curl, but you may run into other issues because we no longer support this version.

Here's a topic about curl and wordpress that may be useful:
https://wordpress.org/support/topic/curl-error-56-3/
Hope that helps.

**Comment by chenyangyangvip** [comment] 2018-08-07 07:10
@dmitridr Thank you for your help
![image](https://user-images.githubusercontent.com/33614001/43759860-22db1a88-9a53-11e8-99ad-5f050d40fbce.png)

Curl should be fine.
Some products with fewer variants can be uploaded, and products with many variants cannot be uploaded. There are now 66 products that are being uploaded.
I have deleted the configuration and tried it again many times.

**Comment by chenyangyangvip** [comment] 2018-08-07 07:16
@dmitridr I tried to use 1.711, but the error still exists.
![image](https://user-images.githubusercontent.com/33614001/43760522-e5c41f8a-9a54-11e8-80cc-d31c91fa7fb4.png)

**Comment by dmitridr** [comment] 2018-08-10 22:51
Thanks for trying that. I think our best bet into figuring this out is to figure out why curl is not working.
I did some digging into the curl error you have and found this : 
https://stackoverflow.com/questions/15525344/ssl-connect-and-ssl-error-syscall

It seems that if there's an EOF character in one of your products, the product feed we try to upload to Facebook may fail because it breaks SSL. I'm not sure about this though, but we I can create a version of the plugin for you to try and get some more information to see if that's what's going on. I'll attach the version in my next post.

**Comment by dmitridr** [comment] 2018-08-10 23:26
Ok I took a closer look at the logs we have from you as well, I suspect the problem is here : 
https://github.com/facebookincubator/facebook-for-woocommerce/blob/master/includes/fbproductfeed.php#L115

Can you verify that write permissions on your server are enough to allow php to create a feed file inside the plugin directory? If permissions are too strict, this will definitely fail.

Here's the promised special version: 
[facebook-for-woocommerce-v1.9.4.1.zip](https://github.com/facebookincubator/facebook-for-woocommerce/files/2279716/facebook-for-woocommerce-v1.9.4.1.zip)

Can you try running sync with that? Please reset using the #612 beforehand. This special version generates tons of logs so it should help us better understand where your problem is.

You may also have some insight into the problem if you access your server's error logs and note any lines mentioning the plugin.

**Comment by lgfogle** [comment] 2020-04-06 23:18
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!

**Closed by lgfogle** 2020-04-06 23:18 UTC
Labels: bug, curl-doesnt-work
