### ISSUE TITLE
Doubles Products at Checkout

### ISSUE THREAD

**Issue by Respsl15** [facebookincubator/facebook-for-woocommerce#149] opened 2017-11-13 03:08 UTC
Greetings All.

Not sure if this issue has come up for anyone else here yet, but when I add multiple products from my facebook shop and checkout via website then it adds one to the previous product placed in cart (i.e., I select 1-mug, it gets added to the cart. I go back and select 1-shirt, and when I go back to the cart on my website it has added one to my mug (making it 2)). This goes on and one....

Any clue why?

**Comment by tahoff** [comment] 2017-11-14 16:29
@Respsl15, thanks for reporting this issue. Unfortunately, I'm not able to reproduce this issue. Can you send us your store's URL?

Additionally, can you verify that you're using the latest version of Facebook for WooCommerce (1.6.6)?

**Comment by sammul** [comment] 2017-11-15 02:45
Hi, thanks for reporting the issue. Can you share some urls where we can repro the issue? And please tell us know which version are you on? Make sure you update the extension to the latest version if possible. Thanks

**Comment by Respsl15** [comment] 2017-11-15 03:30
Greetings All.

Unfortunately, the site we were working on with the Facebook for
WooCommerce no longer has it on there. I had to switch to another extension
that fulfilled this need. Thank you for looking into it though.

**Comment by sammul** [comment] 2017-11-15 19:05
I'll close the issue for now. If you see this happening in the future, feel free to report again. Thanks!

**Closed by sammul** 2017-11-15 19:05 UTC
