### ISSUE TITLE
Missing "AddToCart" event in Pixel

### ISSUE THREAD

**Issue by CasaOmnia** [facebookincubator/facebook-for-woocommerce#393] opened 2018-04-10 10:21 UTC
the tracking pixel does not receive the add-to-cart and purchase events.

website url:
(https://casaomnia.it)

**Comment by sammul** [comment] 2018-04-11 16:45
Pixel id: 1617562375151430

When did you install the extension?

**Comment by dmitridr** [comment] 2018-04-11 19:33
Hello!

Seems that there are multiple people reporting this issue. Could you try the following:

1. Install the Facebook Pixel Helper tool, and confirm that the event `Purchase` does not appear in the tool when you go through and make a purchase? (I confirmed this myself on your site for AddToCart)
2. Could you try installing the version of the extension v1.8.3 available [here](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.8.3) and seeing if the events AddToCart and Purchase appear? This will help us understand if there is a bug in the new version that is causing your problem.
3. I see your add to cart functionality is different from a lot of other sites, do you have any custom plugins or settings for add to cart that may be interfering with the plugin?
4. Do you have `Google Enhanced E-Commerce` plugin? This has known issues with ours that cause these events not to work.

That will greatly help us get to the bottom of this. Thanks!

**Comment by zupa0514** [comment] 2018-04-24 03:02
The exact same thing was happening to me. I had to delete the plugin and install the version of the extension v1.8.3. Although it's still showing an error on my facebook business manager, at lest the Facebook Pixel Helper is now tracking the AddToCart... 
I hope that Facebook can update the information as soon as possible since the Instagram Shop is NOT WORKING and I'm hoping it's because facebook is still showing an error.

**Comment by zmoss** [comment] 2018-05-20 22:52
I have the same issue. When a user clicks Add To Cart on a product or category page the "Add To Cart" event fails to fire. We have it set so when you click add to cart it redirects to the cart page. Based on the changelog (https://dzv365zjfbd8v.cloudfront.net/changelogs/facebook-for-woocommerce/changelog.txt) this issue was supposed to be fixed in 1.8.4 however it does not look to be working properly.

**Comment by dmitridr** [comment] 2018-06-22 21:06
@zupa0514 Instagram Shop is not supported by the plugin yet. It will be soon though (there will be an option to apply for IG shop within the plugin). 

@zmoss Have you tried the workaround suggested in #219 ?

Do either of you have the `Google Enhanced Ecommerce` plugin? This was preventing AddToCart from properly firing, but was fixed in `1.8.7`.

**Comment by dmitridr** [comment] 2018-11-09 22:42
I'm going to close this since there wasn't a response for a while now. Hope it's fixed for you all, please feel free to send us a new issue with details if not.

**Closed by dmitridr** 2018-11-09 22:42 UTC
Labels: bug
