### ISSUE TITLE
Variation Inconsistencies : Product has outdated variant names after upgrade.

### ISSUE THREAD

**Issue by rKadeUK** [facebookincubator/facebook-for-woocommerce#51] opened 2017-09-22 21:05 UTC
Hi there,

My Woocommerce listing is not showing variations in Facebook correctly. 
See; https://www.facebook.com/commerce/products/1702281196463179/ which do not match the correct variations in https://rkade.uk.com/product/fifa-18/ 

Also the price of the product is not showing as £15.99 – £89.99 (instead showing at just £89.99)

Hope you can help.

**Comment by dmitridr** [comment] 2017-09-22 21:37
Hi,

The price will change if you change the variation selected. The default is 89.99 because of the default selection.

Could you confirm that you have version 1.6.0 or above? We fixed a bunch of variation issues in 1.6.0.
This looks like it could be related to #45

**Comment by rKadeUK** [comment] 2017-09-22 21:43
Hi there,

Thanks for the response, I updated to 1.6.0 a few days ago, I re-uploaded products twice since I updated :) 

To confirm - No default variations are chosen at all...

So not sure about this?

**Comment by dmitridr** [comment] 2017-09-22 21:50
Thanks for confirming, by default I mean the first one I see (the top selection in each selector) when clicking on the first link provided. Selecting other choices yield different prices. 

Was this an issue before you upgraded as well, or a new issue caused by the upgrade?

**Comment by rKadeUK** [comment] 2017-09-22 22:03
Ah I see, Yes, when selecting each variation, the prices appear fine which is great. But it would be useful to see the price range in the main listing in the shop - it did this in the very first release with no issues which is odd. 

And no, this was an issue before updating too. 

Appreciate the support!

**Comment by dmitridr** [comment] 2017-09-22 22:57
Thanks for the information. 

- It seems the price range will display if you select `Select Edition` and `Select Console` in the selectors, I wonder why that's not the default when opening the product and what we changed in order to change this...  
- Looks like there are some slug names being imported for the variants selection. That's weird because we should have fixed that in 1.6.0. You could try deleting the product from FB (via the `Facebook` section in the WooCommerce `Product Edit` page.) and then hitting update, which will recreate the product. You may have to wait (Up to a few hours) for the new item to be approved, since it was re-created.

**Comment by rKadeUK** [comment] 2017-09-24 18:16
Thanks for the input - deleting the product doesn't work (see; http://recordit.co/wQFHXzz22I)

**Comment by rKadeUK** [comment] 2017-09-28 17:51
Thanks for the response, it's odd it's only happening to this product :( 

- Could you try 'Reset Facebook Metadata' on that product? Then afterwards a trivial update (maybe add a space somewhere) to reupload the product to FB? (This should refresh the meta-data)

**RESULT: This has the same issue as deleting the product above.** 

- Could you try duplicating the product, and seeing if the duplicate has the same problem on the FB shop?

**RESULT: Same Issue - links to the current facebook product, not a new one?**

- Can you upload a screenshot of the configuration settings on that product so that we could set up a similar product and try to reproduce the problem?

![image](https://user-images.githubusercontent.com/32174778/30981964-e05f28aa-a47d-11e7-907b-e7352833753e.png)

![image](https://user-images.githubusercontent.com/32174778/30981988-f9920400-a47d-11e7-8977-797af70fdd03.png)

Cheers 👍

**Comment by rKadeUK** [comment] 2017-09-28 17:53
Here's my product catalogue which looks correct 

![image](https://user-images.githubusercontent.com/32174778/30982082-4db5d2e6-a47e-11e7-8234-2c7b20524c38.png)

**Comment by dmitridr** [comment] 2017-10-02 23:34
Hello,

We checked our backend and we had 14 variants even though you only had 10 in your screenshot, which is pretty strange. I've removed the 4 extra variants from our backend, so they shouldn't show up in the shop anymore for that product, but this is a temporary solution. We recommend you try to update the product to make sure those odd variants don't return again.

**Comment by dmitridr** [comment] 2017-10-20 02:03
I'm closing this, since the product appears resolved to me on the shop side. Please re-open if there is some further problem!

**Closed by dmitridr** 2017-10-20 02:03 UTC
Labels: bug
