### ISSUE TITLE
Facebook Settings not Saving on Products in WC [Bug]

### ISSUE THREAD

**Issue by BradleyDB** [facebookincubator/facebook-for-woocommerce#222] opened 2018-01-18 20:59 UTC
My products in WooCommerce (WC) are synced with the Facebook (FB) store, however, only 4 of 14 were showing up (another issue). 

I want 2 of the 4 products not to be viewable, and I want to create my own product "Facebook Description" on the product page in WC. Otherwise, FB just pulls random words from the product page.

The problem is that unselecting "view" and hitting "update" on the product page in WC does not result in the view box remaining unchecked. It is as if I did nothing.
The same happens when I add a FB description - I update the product, then the description vanishes.

This is my first installation of the plug-in so there should be no conflict with previous data.

This is a WP hosted site using:
WP v 4.9.2
WC v 3.2.6
FB plug-in 1.7.5

Subscriptions and Memberships are also running.

**Comment by tahoff** [comment] 2018-01-18 21:50
Thanks for flagging this @BradleyDB. I have a few additional questions for you:
- What is your website's url?
- When you say "FB just pulls random words from the product page" is it significantly different from the product description?
- Did you leave the background window open while syncing? Product upload can take a while.
- Does the bug you reported appear for all product types, or only a specific type?

**Comment by BradleyDB** [comment] 2018-01-18 23:07
Helllo @tahoff :

- https://internshipsaver.com You'll notice it's not a traditional WC store. I mostly use that for the merchant side. Go to /join to see the product page.
- It pulls from the page itself. The products that didn't load were more traditionally laid out products, but as they didn't load I'm not sure if they behaved differently.
- I didn't touch anything until I had a "sync confirmed" message. Took <minute.
- There is only one type of product that loaded to the store so I can't really say.

**Comment by tahoff** [comment] 2018-01-19 03:02
After looking at the "Global Community Professional Membership" product, it looks like it's pulling all of the description content found on https://internshipsaver.com/product/global-community-professional-membership/?v=7516fd43adaa. Do you use a specific extension to format your description that way?

As for the issue about 'Visible' changing itself after clicking update, I can reproduce that for Variable Subscription products. So that's definitely an issue on our end.

**Comment by BradleyDB** [comment] 2018-01-19 03:36
@tahoff The page is built with Elementor Pro, so that's probably causing some conflict with where the description is pulled if the "Facebook Description" is not completed. 
My issue though, is that I'm not able to overwrite that - If I fill out the Facebook Description and update the product, it doesn't save.

**Comment by dmitridr** [comment] 2018-03-23 01:56
Hi @BradleyDB 

I'm following up on older issues that didn't get resolved. Are you still having this problem with the latest version v1.8.2?

**Comment by dmitridr** [comment] 2018-06-13 02:08
Closing this out as there hasn't been a response for 6 months! Feel free to file a new issue on us if this is still a problem though the cause is likely what @mengyingdu mentioned.

**Closed by dmitridr** 2018-06-13 02:08 UTC
Labels: bug
