### ISSUE TITLE
Facebook plugin for WooCommerce not working - crashes my site

### ISSUE THREAD

**Issue by milosmili** [facebookincubator/facebook-for-woocommerce#429] opened 2018-04-24 07:37 UTC
Facebook Page URL:
https://www.facebook.com/Topphonestuff-479032609180608/

WordPress version: 4.9.5

WooCommerce version : 3.3.5 

Facebook Plugin version number: 1.7.3 (previously I had installed version 1.8.5.)

How many products you have:  228

Types of products " simple/variable; some propduct having max. 100 variations

Do you have Duplicate SKUs in your system? No

What kind of customization plugins you're using (if any)? None

At first, 5 days ago I noticed FB disaplyed all my products using ver. 1.8.3, but variations for most of them were not uploaded to my FB page. I was waiting for 2 days by the sync wasn't still completed.

I upgraded to  1.8.5. still the same, but this time plugin won't even sync a single products. I did FORCE SYNC but crashed my hosting Web server.

From https://www.facebook.com/events_manager/partner-integration/woocommerce/?act=25378966&selected_data_sources=PIXEL&selected_screen_section=PARTNER_INTEGRATIONS

I uploaded and installed  & installed ver .1.7.3, was waiting for 2 days for sync to be done, still the same...

How can I have a fresh start ? How to delete all  Facebook IDs related to my products...are they are store somewehre in MySQL db ?

Please advise ASAP.

THx.

Milos

**Comment by mengyingdu** [comment] 2018-05-08 16:07
Hi @milosmili ,

Sorry for the delayed response! I checked your site and our error logging. There are several issues cause your current problems.

1. On 2nd May, when you tried to sync with v1.8.5, there was an internal bug (on Facebook side, not from plugin)  which caused ALL shops can't onboard. Specifically, Facebook is trying to protect users with better privacy policy. However, this change has introduced a bug. **This has already solved and confirmed in #463 
2. There was a bug in v1.8.6 which may cause site crash and has fixed in v1.8.7.

Sorry for the inconvenience to you. Would you mind upgrade to 1.8.7? Then delete your settings and set up. Let me know if you need more help.

Thanks.

**Comment by mengyingdu** [comment] 2018-05-15 15:40
Hi @milosmili ,

Still have problems? Do you need more help? Are you able to launch your wp-admin?

**Comment by dmitridr** [comment] 2018-05-23 00:28
I'm closing this out due to no response. If you still have this problem, please open a new issue on us and reference this one.

As @mengyingdu said, Old versions (pre 1.8.2) have issues with sync. Your best bet is to upgrade to latest version 1.8.7 and completely reset, the new sync method should be fast.

**Closed by dmitridr** 2018-05-23 00:28 UTC
