### ISSUE TITLE
Shop on Facebook showing but all my items are OUT of STOCK

### ISSUE THREAD

**Issue by sfconcas** [facebookincubator/facebook-for-woocommerce#530] opened 2018-06-05 18:24 UTC
@dmitridr 

Hi guys first of all thank you so much for helping me out to get my shop up and running on facebook. I have anther issue now, all my items for some weird reason are OUT OF STOCK. I have forced re sync a few times and nothing, I checked the website and they are all good. Is there anyway you could check this for me please please? 

my shop page is:
https://www.facebook.com/pg/JSLaserCraft/shop/?ref=page_internal
https://business.facebook.com/pg/JSLaserCraft/shop/?ref=page_internal

Thank you in advance 

Regards, 
Simon

**Comment by mengyingdu** [comment] 2018-06-05 18:50
Hi @sfconcas ,

Can confirm, this is not a bug in the plugin but a bug in all FB shops. 1-2 days is the current ETA for a fix from the shops team.

Sorry for the inconvenience.

**Comment by sfconcas** [comment] 2018-06-05 18:51
Hi, 

Thank you so much for the kind reply. Guys you are so amazing. Thank you so much for the reply

**Comment by dmitridr** [comment] 2018-06-06 01:47
#523 is the same issue , so I'll be closing this. When we have an update, we will update in that issue.

**Closed by dmitridr** 2018-06-06 01:47 UTC
Labels: duplicate, shop-bug
