### ISSUE TITLE
[incompatibility][elementor description import]" – " Showing as &#8211;

### ISSUE THREAD

**Issue by benedettogit** [facebookincubator/facebook-for-woocommerce#443] opened 2018-04-27 17:37 UTC
I have this symbol – in the description but it shows as: `&#8211;`
88  –  92  –  96
88  `&#8211;`  92  `&#8211;`  96

https://www.facebook.com/commerce/products/1547751165347481/

**Comment by sammul** [comment] 2018-04-30 17:26
I can see the issue. Assigning to our developer

![screen shot 2018-04-30 at 10 25 29 am](https://user-images.githubusercontent.com/4251631/39440775-e6036646-4c60-11e8-8c6d-c72d80e60912.png)

**Comment by mengyingdu** [comment] 2018-05-04 21:30
Hi @benedettogit ,

It's weird since I can't repo your issue. &#8211 is en dash '-'. So I tried to use a dash in the description, this is what shows up in my test product:

<img width="409" alt="screen shot 2018-05-04 at 2 28 53 pm" src="https://user-images.githubusercontent.com/24535640/39653914-bc595c02-4fa7-11e8-8a86-baec629a6e5b.png">

Any other plugins you are using?

**Comment by benedettogit** [comment] 2018-05-04 22:06
I wrote that dass with elementor in a template using tabs, and i load it in the description with elementor shortcode. here is the .json

`{"version":"0.4","title":"fb shop","type":"section","content":[{"id":"298bdc","settings":{"gap":"no","border_radius":{"unit":"px","top":"0","right":"0","bottom":"0","left":"0","isLinked":true},"box_shadow_box_shadow_type":"yes","box_shadow_box_shadow":{"horizontal":0,"vertical":0,"blur":10,"spread":0,"color":"rgba(0,0,0,0)"},"margin":{"unit":"px","top":"0","right":0,"bottom":"0","left":0,"isLinked":true}},"elements":[{"id":"4857278f","settings":{"_column_size":100,"space_between_widgets":0},"elements":[{"id":"1eedeb13","settings":{"tabs":[{"tab_title":"Guida alla taglia","tab_content":"<p>\u00a0 \u00a0 \u00a0 \u00a0 \u00a0 \u00a0 \u00a0 \u00a0 \u00a0 \u00a0 \u00a0 \u00a0 \u00a0 \u00a0 Taglia\u00a0 \u00a0S\u00a0 \u00a0-\u00a0 \u00a0M\u00a0 \u00a0-\u00a0 \u00a0L<br \/>Circonferenza seno\u00a0 \u00a0 \u00a0 88\u00a0 -\u00a0 92\u00a0 -\u00a0 96<br \/>Circonferenza vita\u00a0 \u00a0 \u00a0 \u00a0 68\u00a0 -\u00a0 72\u00a0 -\u00a0 76<br \/>Circonferenza bacino\u00a0 96 - 100 - 104<\/p>","_id":"123bcf1"}],"icon":"","icon_active":"fa fa-minus","border_color":"#ffffff","space_between":{"unit":"px","size":0},"box_shadow_box_shadow_type":"yes","box_shadow_box_shadow":{"horizontal":-100,"vertical":-100,"blur":0,"spread":0,"color":"rgba(0,0,0,0)"},"title_color":"#7a7a7a","title_typography_typography":"custom","title_typography_font_family":"Roboto","title_typography_font_weight":"bold","content_typography_typography":"custom","_margin":{"unit":"px","top":"-15","right":"-15","bottom":"-15","left":"-15","isLinked":true},"title_typography_text_decoration":"underline"},"elements":[],"isInner":false,"widgetType":"toggle","elType":"widget"}],"isInner":false,"elType":"column"}],"isInner":false,"elType":"section"}]}`

I don't know if it helps. You can copy this code put it in a text file and rename it something like elementor-1337-2018-05-04.json and import in elementor, but you probabelly already know this.

**Comment by mengyingdu** [comment] 2018-05-07 16:42
Hi @benedettogit ,

Thanks for your detailed information. I think the cause here is elementor incompatible with the approach we extract description string.  

1. Given that we're dealing with a high volume of bugs, we unfortunately won't get to this feature request to support elementor for a long time to come, even though we'd like to. However, we'd be happy to review any pull request to add this functionality, please consider sending us one!

2. Here is some workaround for you which you can still use elementor for the description your website, but also have desired description on FB. Can you put the description as you want in the FB description box?
![screen shot 2018-05-07 at 9 42 29 am](https://user-images.githubusercontent.com/24535640/39713249-fd6b4e8c-51da-11e8-9ce9-b060fb4ce1d2.png)


Thanks.

**Closed** 2018-07-04 19:02 UTC
Labels: feature-request
