### ISSUE TITLE
******** Sync Fails Completely : Sync error: value of "default_product" is not correct **********

### ISSUE THREAD

**Issue by JakubPie** [facebookincubator/facebook-for-woocommerce#404] opened 2018-04-13 08:12 UTC
Hi,

since yesterday I have a huge problems with my FB Shop. At the beginning it was not possible to get to my shop on FB (the loading wheel was spinning forever without showing products) and after some time my shop was just empty + tagged products disapeared from my photos. I looked at facebook-for-woo status and configs - everything seemed to be OK. I look into my catalogues manager - all products were there. After another 30 minutes my Woocommerce catalog was empty too. So I started to read this board to get help and I decided to delete my settings, configure them once again and see if it works. FB-for-Woo correctly found all my products, show miniatures in a background, tells me that I already have a shop and my current products will be deleted/overrode etc. but unfortunatelly I am getting 1 Error and 1 Warning and my products are not imported:

![grafik](https://user-images.githubusercontent.com/38345480/38723658-15ac36fa-3f02-11e8-8f60-6823c82d3340.png)
![grafik](https://user-images.githubusercontent.com/38345480/38723692-2cf7b726-3f02-11e8-9309-da8e8da13ef4.png)

I have no idea how to fix it. In my FB store I see of course no products. FB-for-Woo status says that my products are synced. Can it be connected with this week WooCommerce update? My catalog ID: 159859081365344, and the shop: https://www.facebook.com/PetitBibo/

Thanks in advance for your help.

Edit: I have manually change the value of stock in one product and this product starts sync correctly (it is now visible for me in FB shop with "computing" status).

**Comment by dmitridr** [comment] 2018-04-13 22:55
All uploads are broken because of this, this is a FB infrastructure error. We spotted this just now and have a fix ready. We estimate it will be pushed in 12-24 hours. At the latest it will be fixed by Monday. Working on it now.

**Comment by dmitridr** [comment] 2018-04-13 22:59
Clarification : It's not a bug in the Woo plugin, it's a bug in Facebook itself. Once resolved, a `Force Resync` should fix the issue.

**Comment by JakubPie** [comment] 2018-04-14 07:12
OK, thx for fast answer.

**Comment by dmitridr** [comment] 2018-04-14 17:55
Ok the fix is live as of a few hours ago.

Uploads should work now, I recommend a `Force Resync` if you encountered this problem.

**Closed by dmitridr** 2018-04-14 17:55 UTC
Labels: Do this ASAP, bug
