### ISSUE TITLE
Default Product Variant Images Not Displaying In New Collections Category In Facebook Shop 

### ISSUE THREAD

**Issue by ParisStone** [facebookincubator/facebook-for-woocommerce#480] opened 2018-05-14 02:22 UTC
Hello @dmitridr, with reference to #231, in my FB Shop (synced to WooCom), 

Under 'All products' category, the default product variants and corresponding images were able to be displayed correctly, same as the setting in WooCom. 

However, under 'Collections' category, the default product variants and images were not able to be displayed correctly, it chose another variant and image (2 cases it chose the last variant and image, 1 case it chose the next variant and image). But I would like it to show the default product variant and image, just as it would under 'All products' category.

Tried using the 'Use parent image' option on WooCom, it worked showing the default product image only, but not the corresponding variant. Customers were not able to select variants with corresponding images on FB Shop, and when they selected a variant with the incorrect image, pressed the Call To Action Button over to our website, the variants were Added to Cart already, without a chance to really see which images corresponds to what variants.

I initially synced FB Shop with WooCom and just had the 'All products' category, it was working fine. Then I recently added 'Collections' category to FB Shop, and found the above issue.  

WooCom version 3.3.5
WordPress version 4.9.5
FB for WooCom Version 1.8.7

Thanks for your help in advance!
Paris

**Comment by mengyingdu** [comment] 2018-05-16 18:57
[Note : This is an Automated Message]

Hello,

Thanks for your interest in our plugin!
Due to a high volume of issues we may not be able to get to yours immediately.

If this is a feature request, or feedback, please reply with
`Feature Request` or `Feedback` and it will be categorized accordingly, and
we will read it and reply when we can.

If you are experiencing problems, read on.

First. Please check to see if your issue is not a duplicate of another one.
To search our issues, use the search feature at the top of the GitHub issues page.
We have nearly 500 existing and past issues, so it is fairly likely someone else has already reported your problem.
If you do find a relevant issue, please comment in that issue, and close this one.
It helps us prioritize issues to tackle by looking at the number of people with the same problem.

If your issue is unique, and you are sure, then read on.
We require the following information in order to help you:
- WooCommerce Version
- Wordpress Version
- Plugin Version. Please Note that we do not support outdated versions of the plugin.
- A Screenshot of where you see the problem. If it is on Facebook, a screenshot of Facebook,
if it is on WooCommerce, a screenshot of WooCommerce. If it is in multiple places, multiple screenshots.
- The URL of your website.
- The URL of your page.
- The URL(s) where you took your screenshot(s).
- (If applicable) Detailed steps you took in order to see the problem.

Please be advised, it may take us some time to get to your issue.
In the meantime, below are generic approaches you can take that may solve the issue :
- Upgrade to the latest version.
- Force Resync
- Reset the plugin using `Reconfigure > Advanced Options > Delete` and setup again.
- Try to deactivate other plugins which you think could be interfering and repeating the above.

When you have the above data for us, please include
`Debug Ready` in your reply. We will get to it and debug it as soon as we can.

Thanks for your patience,
Dev Team (@dmitridr, @mengyingdu, @sammul, @jieminz22)

**Comment by ParisStone** [comment] 2018-05-18 08:03
@dmitridr <https://github.com/dmitridr>,

Thanks for getting in touch!

(1) Enclosed 2 screenshots.
'All Products - Default Variant.jpg' shows the correct product variant as
specified in WooCom shown in FB's default 'All products' collection.
'Accessories - Non-default Variant.jpg' shows the incorrect product variant
shown in the 'Accessories' collection I created.
When I create a 'Collection' on FB Shop, there is no option to specify
default variant. I specified default variant in WooCom.

(2) URLs below.
https://www.facebook.com/pg/PuristStore/shop/
https://www.puriststore.com/product/pom-pom-earrings/

WooCom version 3.3.5
WordPress version 4.9.6
FB for WooCom Version 1.8.7

Please advise. Thanks in advance!
Paris

**Comment by ParisStone** [comment] 2018-05-18 08:08
@dmitridr, Thanks for getting in touch! 

(1) Enclosed 2 screenshots. 

![all products - default variant](https://user-images.githubusercontent.com/39250943/40223330-3f426f60-5ab5-11e8-8022-1e1d3f980b2b.jpg)
'Default Variant' above is the correct product variant as specified in WooCom shown in FB's default 'All products' collection.

![accessories - non-default variant](https://user-images.githubusercontent.com/39250943/40223349-4882f928-5ab5-11e8-982e-7e43cb2f4c87.jpg)
'Non-default Variant' above is the incorrect product variant shown in the 'Accessories' collection I created.

When I create a 'Collection' on FB Shop, there is no option to specify default variant. I specified default variant in WooCom. 

(2) URLs below.
https://www.facebook.com/pg/PuristStore/shop/
https://www.puriststore.com/product/pom-pom-earrings/

WooCom version 3.3.5
WordPress version 4.9.6
FB for WooCom Version 1.8.7

Please advise. Thanks in advance!
Paris

**Comment by ParisStone** [comment] 2018-05-30 06:50
Hi @dmitridr and @mengyingdu 

Any updates to the issue above?

Regards,
Paris

**Comment by mengyingdu** [comment] 2018-06-26 21:42
Hi @ParisStone and @maternaghan ,

Thanks for updating the details.

Let me clarify the 'default product' display in fb page shop.

We (Facebook shop, our plugin) only support to default product feature (a default variant set in Woo as the default on in Fb shop) for 'ALL collections', but not manual collections. This is for page loading considerations, since it changes the ranking logic.

We may consider to support that in the future but we focus on product stability and quality (bug fixes). 

Thanks.

**Comment by mengyingdu** [comment] 2018-08-17 22:04
## Automated Support Message - Issue Closed

Hello,

Because it has been 30 days since this issue was updated and you have not included `Debug Ready` in your reply, our automated system will now close your issue.
If you are still having this problem, please open a new issue and reference this one.

For more information on our response times and support policy, visit [Facebook Support on GitHub](https://github.com/facebookincubator/facebook-for-woocommerce/wiki/Facebook-Support-on-GitHub).

Thank you,
The Facebook Dev Team

**Closed by mengyingdu** 2018-08-17 22:04 UTC
Labels: Automated : Multiple Reports, Automated : Need More Info
