### ISSUE TITLE
Empty Data

### ISSUE THREAD

**Issue by vipsouq** [facebookincubator/facebook-for-woocommerce#1462] opened 2020-08-14 05:43 UTC
1. Some content_ids sent from pixel fires by this pixel do not match any catalog associated to the pixel, This could be because your catalogs aren't up to date, or because the item IDs in your catalogs don't match the content_ids in your pixel

   2. Your data feed file can't be empty:
Add products to your data feed file and then upload it again. Uploading an empty file will delete all products in your feed. If you want to do this, please delete the feed that they were uploaded from.

**Comment by vipsouq** [comment] 2020-08-14 05:46
Your data feed file can't be empty:
Add products to your data feed file and then upload it again. Uploading an empty file will delete all products in your feed. If you want to do this, please delete the feed that they were uploaded from.

**Comment by lgfogle** [comment] 2020-08-14 15:28
Closing as duplicate of #1461

**Closed by lgfogle** 2020-08-14 15:28 UTC
