### ISSUE TITLE
"Any" string is not translated to other languages in variant selection + Can't boost shared product.

### ISSUE THREAD

**Issue by nikidani86** [facebookincubator/facebook-for-woocommerce#91] opened 2017-10-14 12:47 UTC
Hello, Do i have an option to change the language of the text in the boxes (ex. Check out on the website. ; and buy button.)? My site is working only on a local level, so the english language will be a real problem for my customers.

**Comment by dmitridr** [comment] 2017-10-17 00:47
Hello, 

Which buttons do you mean? Do you mean in the shop?
These buttons should change in language depending on the user's language preference. Are they not doing so for you?

A screenshot of what you are seeing / where the buttons are would help!

**Comment by nikidani86** [comment] 2017-10-17 08:07
Thank you for your fast response.

![screenshot 2](https://user-images.githubusercontent.com/32795013/31652987-aa1b4af2-b329-11e7-8cd8-1bbbfc7d1122.png)
As you can see from this screenshot, The "Check Out On Website" button is in English. 
Also my variations' options are shown mixed: First part is in English while the second is in Bulgarian, which is my default language.

![screenshot](https://user-images.githubusercontent.com/32795013/31652990-aaae9a64-b329-11e7-94fe-383c0a2f69a1.png) 
As you can see from this screenshot, The "BUY" button is in english. 
And there is one more problem here: I am not able to boost a product shared from the Facebook Shop.

**Comment by dmitridr** [comment] 2017-10-31 22:50
Hello again,

It looks like the product is syncing in your default language, but the language you are viewing Facebook in is English, is this correct? 

If so, the buttons in English should be expected behavior... users who are viewing Facebook in the Bulgarian language should see these buttons in Bulgarian. Users who are viewing Facebook in English should see the Facebook interface in English and so on for German, Chinese, etc etc.

The `any razmer` is definitely a bug, I wonder if we can fix that, @mengyingdu what do you think?
Also @sammul do you know why boost is unavailable? Is it because it was shared?

**Comment by mengyingdu** [comment] 2017-11-10 01:22
Hello,

We will only show 'any' rather than the weird combination language for this case in next new version. Thanks for pointing out this. 

More context about the language:
1. FB language: it's default by user(viewer)'s on this page 
2.Your language: in 'attribute name' eg. color, size, etc. Currently, Facebook will use your attribute name directly from your naming in WooCommerce.
3. 'Any' in English: if you set attribute value as 'any value' for a certain product, we use 'any' to represent it and checkout url will be your product page. We can't hardcode to translate to your language at this time. This could done after we support multi-language plugin.

For future improvement, we will translate your attribute name to  FB language to make it more consistent. (3 to 2)

Thanks.

**Comment by mengyingdu** [comment] 2017-11-29 22:39
Hi,

This has been fixed in [v1.7.0](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.7.0), can you upgrade and check whether it works for you?

Thanks.

**Closed by mengyingdu** 2017-11-29 22:39 UTC
Labels: bug
